### ISSUE TITLE
[BUG] <brief bug description>

### ISSUE THREAD

**Issue by kusti420** [libre-tube/LibreTube#103]
importing subscriptions causes it to crash every single time. guess it cant handle 2793 subscriptions

**Comment by kusti420** [comment]
[subscriptions.csv](https://github.com/libre-tube/LibreTube/files/8351497/subscriptions.csv)

**Comment by VarunBanka** [comment]
Greatings of the day!!!

Same with me as well. And I can't subscribe to any channel ether. I am looking forward it to get fixed and in the near future I may switch to libre tube. I'll appreciate if it will get fixed as soon as possible. Btw I was on latest version available on GitHub for android. And I was in android 11 stock rom. It continues in custom rom as well.

Thanks

**Comment by lilcheti** [comment]
I'm on it for a fix

**Comment by lilcheti** [comment]
It's fixed now. if the zip file won't work just unzip it and import the csv.

**Comment by IceDBorn** [comment]
It would be worth trying to import the subscriptions from the web. Just access the instance you're using through the browser and import your subscriptions.

**Comment by lilcheti** [comment]
> version 0.2.4 is the newest right?

Nah I meant in the latest commits.

**Comment by kusti420** [comment]
> > version 0.2.4 is the newest right?
> 
> Nah I meant in the latest commits.

how do i get an apk from that? can only see some files being changed but the latest apk seems to be 0.2.4?

**Comment by kusti420** [comment]
> It would be worth trying to import the subscriptions from the web. Just access the instance you're using through the browser and import your subscriptions.

how exactly could i do that?

**Comment by FireMasterK** [comment]
> how exactly could i do that?

Go to https://piped.kavin.rocks/

Switch instance in the preferences menu if required

Login

Go to feed, then subscriptions then click on import

Follow the instructions, and you can import it

**Comment by kusti420** [comment]
> > how exactly could i do that?
> 
> Go to https://piped.kavin.rocks/
> 
> Switch instance in the preferences menu if required
> 
> Login
> 
> Go to feed, then subscriptions then click on import
> 
> Follow the instructions, and you can import it

just tried that, cant import through a browser either

**Comment by kusti420** [comment]
> > just tried that, cant import through a browser either
> 
> What's the issue you're facing? You should open an issue in https://github.com/TeamPiped/Piped incase you have replicable steps on the official instance
[takeout-20220329T190113Z-001.zip](https://github.com/libre-tube/LibreTube/files/8379935/takeout-20220329T190113Z-001.zip)
[subscriptions.csv](https://github.com/libre-tube/LibreTube/files/8379938/subscriptions.csv)

im unable to import subscriptions. aight ill see if someone has opened a similar issue to mine in https://github.com/TeamPiped/Piped if not then imma make a new one. in the mean time can u test if youre able to import my subscriptions?

**Comment by kusti420** [comment]
idk there is still some problem, it still crashes when i try to import subscriptions. but they somehow got imported it seems. so idk if it can exactly be called done now. but idk if its supposed to load sth in subscriptions tab or what is it doing but it just never seems to finish loading.
2700 subscriptions seems too much for it to handle :D

.![Screenshot_20220410-221845297.jpg](https://user-images.githubusercontent.com/75937552/162636153-59c6d9d5-b6aa-4b1d-9de3-a2afeb04746a.jpg)



FATAL EXCEPTION: main
Process: com.github.libretube, PID: 12372
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=976161979, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:Download/kde connect/takeout-20220329T190113Z-001.zip flg=0x1 }} to activity {com.github.libretube/com.github.libretube.MainActivity}: java.io.FileNotFoundException: /storage/emulated/0/Download/kde connect/takeout-20220329T190113Z-001.zip (Permission denied)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7670)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Download/kde connect/takeout-20220329T190113Z-001.zip (Permission denied)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:265)
	at java.util.zip.ZipFile.<init>(ZipFile.java:187)
	at java.util.zip.ZipFile.<init>(ZipFile.java:201)
	at s2.c0.c(:6)
	at androidx.activity.result.ActivityResultRegistry.a(:1)
	at androidx.activity.ComponentActivity.onActivityResult(Unknown Source:2)
	at androidx.fragment.app.u.onActivityResult(Unknown Source:5)
	at android.app.Activity.dispatchActivityResult(Activity.java:8304)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
	... 11 more

**Comment by FireMasterK** [comment]
I created an account of the official instance and imported it via the web interface, with the username and password as LibreTube103

The feed literally has 17118 videos :exploding_head: and it took 3-4 minutes to import, which is unacceptable

Related issue for me: https://github.com/TeamPiped/Piped/issues/609

**Comment by kusti420** [comment]
yeah seems like it needs to be simplified alot

**Comment by FireMasterK** [comment]
The speedup is now live with https://github.com/TeamPiped/Piped-Backend/pull/242

Libretube needs to use the /import route to benefit from these changes now.

**Comment by lilcheti** [comment]
It's using /import rn is there anything new with it?

**Comment by FireMasterK** [comment]
Nope, I guess the fix will land in the next release

**Comment by kusti420** [comment]
> Nope, I guess the fix will land in the next release

cant wait for it

**Comment by martin-desktops** [comment]
@kusti420  the issue can be closed - 0.2.6 has been released

**Comment by kusti420** [comment]
> @kusti420  the issue can be closed - 0.2.6 has been released

yup, seems to work as it should now, didnt crash when importing subscriptions and didnt fail either and subscriptions tab is now able to load content
