### ISSUE TITLE
Crashes when opens YT channel link

### ISSUE THREAD

**Issue by KurozyOS** [libre-tube/LibreTube#1057]
### Steps to reproduce

1. Open a video
2. Click in description link to other YT channel
3. Pops up options to open link
4. Click on lt

### Expected behavior

Opens YT channel in the application

### Actual behavior

Crashes with error code after entering
`java.lang.RuntimeException: Unable to resume activity {com.github.libretube/com.github.libretube.activities.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4519)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4551)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2112)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.NullPointerException
	at e.b.s(Unknown Source:0)
	at com.github.libretube.fragments.ChannelFragment.D(SourceFile:2)
	at androidx.fragment.app.h0.e(SourceFile:3)
	at androidx.fragment.app.h0.k(SourceFile:9)
	at androidx.fragment.app.b0.D(SourceFile:23)
	at androidx.fragment.app.b0.W(Unknown Source:91)
	at androidx.fragment.app.b0.B(SourceFile:4)
	at androidx.fragment.app.h0.n(SourceFile:6)
	at androidx.fragment.app.h0.k(SourceFile:3)
	at androidx.fragment.app.b0.R(SourceFile:1)
	at androidx.fragment.app.b0.v(SourceFile:3)
	at androidx.fragment.app.t.onPostResume(SourceFile:5)
	at f.h.onPostResume(Unknown Source:0)
	at android.app.Activity.performResume(Activity.java:8294)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4509)
	... 11 more
    `

### LibreTube version

0.4.2

### Android version

Android 11

### Other details

Installed from fdroid and running custom node with piped dockers

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by freak-from-the-computer-club** [comment]
I have a similar problem, only with subscriptions😿

**Comment by mariobrostech** [comment]
I'm having a similar error when trying to open a channel URL in another app that opens LibreTube. For example, if someone texts me a YouTube channel link, tapping on it results in LibreTube opening and then instantly crashing.

Here's my stack trace:
```
type: crash
osVersion: google/barbet/barbet:12/SQ3A.220705.004/2022081600:user/release-keys
package: com.github.libretube:16
process: com.github.libretube

java.lang.RuntimeException: Unable to resume activity {com.github.libretube/com.github.libretube.activities.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4830)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4863)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2254)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.NullPointerException
	at e.b.s(Unknown Source:0)
	at com.github.libretube.fragments.ChannelFragment.D(SourceFile:2)
	at androidx.fragment.app.h0.e(SourceFile:3)
	at androidx.fragment.app.h0.k(SourceFile:9)
	at androidx.fragment.app.b0.D(SourceFile:23)
	at androidx.fragment.app.b0.W(Unknown Source:91)
	at androidx.fragment.app.b0.B(SourceFile:4)
	at androidx.fragment.app.h0.n(SourceFile:6)
	at androidx.fragment.app.h0.k(SourceFile:3)
	at androidx.fragment.app.b0.R(SourceFile:1)
	at androidx.fragment.app.b0.v(SourceFile:3)
	at androidx.fragment.app.t.onPostResume(SourceFile:5)
	at f.h.onPostResume(Unknown Source:0)
	at android.app.Activity.performResume(Activity.java:8233)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4820)
	... 15 more

```

**Comment by Bnyro** [comment]
Could anyone please resend the logs with 0.5.0?

**Comment by KurozyOS** [comment]
Tried it with 0.5.0 and this spits out

`java.lang.RuntimeException: Unable to resume activity {com.github.libretube/com.github.libretube.activities.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4519)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4551)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2112)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.NullPointerException
	at androidx.preference.R$id.toID(Unknown Source:1)
	at com.github.libretube.fragments.ChannelFragment.onCreate(ChannelFragment.kt:3)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:12)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:29)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:138)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:20)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:9)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:8)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:9)
	at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:1)
	at android.app.Activity.performResume(Activity.java:8294)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4509)
	... 12 more
    `
