### ISSUE TITLE
Crashes when video ends in full screen

### ISSUE THREAD

**Issue by KurozyOS** [libre-tube/LibreTube#1072]
### Steps to reproduce

1. Open channel
2. Play latest video
3. Enter full screen
4. Ends video

### Expected behavior

Starts playing another video

### Actual behavior

Shuts down application and when returned it spits

`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at g4.b0.u0(Unknown Source:24)
	at g4.p.run(SourceFile:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
    `

### LibreTube version

0.4.2

### Android version

Android 11

### Other details

Enabled autoplay

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can you please retry it with the latest version and send the debug log again if it still occurs?
In 0.4.2 debug logs were partly obfuscated so it's not really comprehensible what happened, this got resolved in 0.5.0 :)
Thanks in advance :)

**Comment by KurozyOS** [comment]
Sure thing
