### ISSUE TITLE
Making any playlist causes a crash

### ISSUE THREAD

**Issue by Jinux-1** [libre-tube/LibreTube#1096]
### Steps to reproduce

1. Create a Playlist
2. Add any video to it
3. Crash when you try to open the playlist

### Expected behavior

It should show/play the playlist

### Actual behavior

Crash

### LibreTube version

0.4.2

### Android version

Android 12, CalyxOS 3.7.3

### Other details

Crash log when opening libretube again is shown here:

java.lang.NullPointerException
	at g4.q0$a.d(SourceFile:15)
	at g4.j.run(SourceFile:3)
	at android.app.Activity.runOnUiThread(Activity.java:7139)
	at g4.q0.m(SourceFile:10)
	at j8.a.h(Unknown Source:8)
	at y8.h0.run(Unknown Source:86)
	at androidx.lifecycle.f.b(Unknown Source:35)
	at androidx.lifecycle.f.c(Unknown Source:8)
	at androidx.lifecycle.e.run(SourceFile:5)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: y8.f0: [m1{Cancelling}@341e4e3, Dispatchers.Main.immediate]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you please retry it with the latest version? Thank you!

**Comment by Jinux-1** [comment]
Works great on 0.5.0! Sorry i was relying on f-droid auto updates so i didn't realize it wasn't the latest one
