### ISSUE TITLE
Error opening video

### ISSUE THREAD

**Issue by CYF0861** [libre-tube/LibreTube#1108]
### Steps to reproduce

If I click the video of the subscribed content, I will report an error

### Expected behavior

This should open

### Actual behavior

But it flashed back and reported an error

### LibreTube version

0.5.0

### Android version

HarmonyOS 2.0.0

### Other details

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.github.libretube.util.AutoPlayHelper.getNextVideoId(AutoPlayHelper.kt:11)
	at com.github.libretube.fragments.PlayerFragment$setNextStream$2.invokeSuspend(PlayerFragment.kt:9)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:8)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:29)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:1)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:12)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:5)
	at androidx.lifecycle.LifecycleCoroutineScope.launchWhenCreated(Unknown Source:7)
	at com.github.libretube.fragments.PlayerFragment$playVideo$1$1.invoke(PlayerFragment.kt:110)
	at com.github.libretube.extensions.BaseFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:2)
	at android.app.Activity.runOnUiThread(Activity.java:7300)
	at com.github.libretube.extensions.BaseFragment.runOnUiThread(BaseFragment.kt:2)
	at com.github.libretube.fragments.PlayerFragment$playVideo$1.invokeSuspend(PlayerFragment.kt:9)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:5)
	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:2)
	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:2)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5e419d, Dispatchers.Main.immediate]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Cyrzeii** [comment]
I'm also having this issue. Android 11, 0.50

**Comment by Bnyro** [comment]
Does the issue still persist in v0.5.1?

**Comment by CYF0861** [comment]
The problem has been solved in v0.5.1, but new problems have emerged.

This is just a small problem, so I will not give you feedback.


---Original---
From: ***@***.***&gt;
Date: Sat, Sep 10, 2022 00:23 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [libre-tube/LibreTube] Error opening video (Issue #1108)




 
Does the issue still persist in v0.5.1?
