### ISSUE TITLE
Crashes when opens watched video

### ISSUE THREAD

**Issue by KurozyOS** [libre-tube/LibreTube#1127]
### Steps to reproduce

1. Watch till the end https://youtu.be/gN1MZdZsLyE
2. Close video
3. Open it and wait to load

### Expected behavior

Starts playing from beginning because the whole video has been watched

### Actual behavior

Tries to autoplay and crashes the app

`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.github.libretube.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:3)
	at com.github.libretube.update.UpdateChecker$$ExternalSyntheticLambda0.run(Unknown Source:20)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
    `

### LibreTube version

0.5.0

### Android version

Android 11

### Other details

Also feature request: When a video has been completed, next time it is opened to start from the beginning.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We had an other issue for that, already fixed.
