### ISSUE TITLE
Opening channels via subscription list

### ISSUE THREAD

**Issue by KurozyOS** [libre-tube/LibreTube#1131]
### Steps to reproduce

1. Go to Subscriptions tab
2. Click on Subscriptions button on the top
3. When list forms click on random channel

### Expected behavior

Opens the channel

### Actual behavior

`java.lang.ArithmeticException: divide by zero
	at com.github.libretube.util.SetWatchProgressLengthKt$setWatchProgressLength$2.onGlobalLayout(SetWatchProgressLength.kt:5)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1061)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3098)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2057)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8362)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
	at android.view.Choreographer.doFrame(Choreographer.java:813)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
    `

### LibreTube version

0.5.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#1092
