### ISSUE TITLE
I got a error 

### ISSUE THREAD

**Issue by UnknownElen** [libre-tube/LibreTube#1159]
### Steps to reproduce

Idk man sorry

### Expected behavior

I wanted to watch a vid

### Actual behavior

And that error popped up: java.lang.NullPointerException: null cannot be cast to non-null type com.github.libretube.activities.SettingsActivity
	at com.github.libretube.preferences.MainSettings$onCreatePreferences$9$1.invokeSuspend(MainSettings.kt:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2724db7, Dispatchers.IO]
    

### LibreTube version

5.0

### Android version

12 calyx os

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
already fixed iirc...
