### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [libre-tube/LibreTube#1180]
### Steps to reproduce

open video

this is a pretty rare crash

### Expected behavior

-

### Actual behavior

`java.lang.ArithmeticException: divide by zero
	at com.github.libretube.util.SetWatchProgressLengthKt$setWatchProgressLength$2.onGlobalLayout(SetWatchProgressLength.kt:5)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1061)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3369)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2277)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9017)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
	at android.view.Choreographer.doCallbacks(Choreographer.java:946)
	at android.view.Choreographer.doFrame(Choreographer.java:875)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8103)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
    `

### LibreTube version

0.5.0

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
dupe, already resolved
