### ISSUE TITLE
Error saving watch position when videoId is null

### ISSUE THREAD

**Issue by CeasarYT** [libre-tube/LibreTube#1194]
### Steps to reproduce

java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.github.libretube.db.obj.WatchPosition.videoId' on a null object reference
	at com.github.libretube.db.dao.WatchPositionDao_Impl$2.bind(WatchPositionDao_Impl.java:2)
	at androidx.room.EntityDeletionOrUpdateAdapter.handle(EntityDeletionOrUpdateAdapter.java:2)
	at com.github.libretube.db.dao.WatchPositionDao_Impl.delete(WatchPositionDao_Impl.java:3)
	at com.github.libretube.db.DatabaseHelper$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:6)
	at java.lang.Thread.run(Thread.java:919)
    

### Expected behavior

java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.github.libretube.db.obj.WatchPosition.videoId' on a null object reference
	at com.github.libretube.db.dao.WatchPositionDao_Impl$2.bind(WatchPositionDao_Impl.java:2)
	at androidx.room.EntityDeletionOrUpdateAdapter.handle(EntityDeletionOrUpdateAdapter.java:2)
	at com.github.libretube.db.dao.WatchPositionDao_Impl.delete(WatchPositionDao_Impl.java:3)
	at com.github.libretube.db.DatabaseHelper$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:6)
	at java.lang.Thread.run(Thread.java:919)
    

### Actual behavior

java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.github.libretube.db.obj.WatchPosition.videoId' on a null object reference
	at com.github.libretube.db.dao.WatchPositionDao_Impl$2.bind(WatchPositionDao_Impl.java:2)
	at androidx.room.EntityDeletionOrUpdateAdapter.handle(EntityDeletionOrUpdateAdapter.java:2)
	at com.github.libretube.db.dao.WatchPositionDao_Impl.delete(WatchPositionDao_Impl.java:3)
	at com.github.libretube.db.DatabaseHelper$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:6)
	at java.lang.Thread.run(Thread.java:919)
    

### LibreTube version

0.5.0

### Android version

10

### Other details

App is to much laging and many time stops working 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I've been trying a lot of stuff now but never had the issue, can anyone please guide me how to it can be reproduced?
