### ISSUE TITLE
Error trying to open unlisted video / playlist

### ISSUE THREAD

**Issue by pranavsetpal** [libre-tube/LibreTube#1205]
### Steps to reproduce

1. Get a link to an unlisted video / playlist
2. Click on link

### Expected behavior

Should open Libretube with the playlist / video

### Actual behavior

Switches to Libretube but it crashes and it comes back on previous app 

### LibreTube version

0.5.0

### Android version

Android 12

### Other details

java.lang.NumberFormatException: For input string: "PLmDnFwFiSne6k3OHm6wMdZRfRw8aSAiga&index=1"
	at java.lang.Long.parseLong(Long.java:594)
	at java.lang.Long.parseLong(Long.java:636)
	at com.github.libretube.activities.MainActivity.loadVideo(MainActivity.kt:6)
	at com.github.libretube.activities.MainActivity.onStart(MainActivity.kt:36)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1471)
	at android.app.Activity.performStart(Activity.java:8082)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3732)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It looks like that the issue is URL specific, could you please share the full link?

**Comment by pranavsetpal** [comment]
Here's the video -> https://www.youtube.com/watch?v=mfafVRCpdBM&list=PLmDnFwFiSne6k3OHm6wMdZRfRw8aSAiga&index=1

**Comment by Bnyro** [comment]
Thanks, I think I know what's going on now :)
