### ISSUE TITLE
App crashes when open link with time parameter

### ISSUE THREAD

**Issue by hache0099** [libre-tube/LibreTube#1275]
### Steps to reproduce

1. Open a Youtube link with a time parameter (e.g. https://youtube.com/watch?v=dQw4w9WgXcQ&t=43s) with LibreTube

### Expected behavior

The video should play from the specified time

### Actual behavior

The app crashes

### LibreTube version

0.5.1

### Android version

Android 10

### Other details

Log:  

java.lang.NumberFormatException: For input string: "43s"
        at java.lang.Long.parseLong(Long.java:594)
        at java.lang.Long.parseLong(Long.java:636)
        at com.github.libretube.activities.MainActivity.loadVideo(MainActivity.kt:6)
        at com.github.libretube.activities.MainActivity.onStart(MainActivity.kt:36)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
        at android.app.Activity.performStart(Activity.java:7826)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3337)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2048)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7438)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:989)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can only use "t=43", not " 43s"

**Comment by eclairevoyant** [comment]
i believe this is a missing functionality. both youtube (https://youtu.be/RDkWagIW6gw?t=9m14s) and piped (https://piped.kavin.rocks/watch?v=RDkWagIW6gw&t=9m14s). i'm happy to work on a PR if adding this is acceptable.

**Comment by Bnyro** [comment]
Sure, go for it, I guess that'll be a oneliner xD

**Comment by eclairevoyant** [comment]
awesome, thanks!
