### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by WhiteNight121** [libre-tube/LibreTube#1307]
### Steps to reproduce

Was watching a video and the app crashes

### Expected behavior

App should not crash

### Actual behavior

retrofit2.HttpException: HTTP 504 
	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:16)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:2)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:2)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b57b33d, Dispatchers.Main.immediate]
    

### LibreTube version

0.5.1

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
504 is a Gateway timeout, all errors in Retrofit are caught in theory so I don't see any way how this could've been happening/be reporduced. Some more information would be good!

**Comment by WhiteNight121** [comment]
Hello thanks for getting back to me I was just watching a video on LTE and then the app just crashed, I have found the app to over all be slow but been trying to use it more as I love the idea. Let me know what else would help or if u think it's a one time I think I we can close this for now and I'll try to use it more.

**Comment by Bnyro** [comment]
These errors should be caught now with the latest release and shouldn't lead to a crash anymore, I will close the issue for now ')
