### ISSUE TITLE
Restoring crashes the app

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#1380]
### Steps to reproduce

1. Settings > Advanced > Backup & restore
2. Tap restore 
3. Pick a backup

### Expected behavior

It should load the backup, restoring settings and login.

### Actual behavior

The app crashed and when I opened it again, it gave an error message.

### LibreTube version

0.6.0

### Android version

Android 12

### Other details

<details><summary>Error message</summary>
<p>

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	... 1 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('�' (code 65533 / 0xfffd)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"��\u0000\u0005sr\u0000\u0011java.util.HashMap\u0005\u0007���\u0016`�\u0003\u0000\u0002F\u0000
loadFactorI\u0000\u0009thresholdxp?@\u0000\u0000\u0000\u0000\u0000`w\u0008\u0000\u0000\u0000�\u0000\u0000\u00002t\u0000\u0015sponsors_category_keysr\u0000\u0011java.lang.Boolean� r�՜��\u0002\u0000\u0001Z\u0000\u0005valuexp\u0001t\u0000\u000Ctheme_togglet\u0000\u0001At\u0000\u0015break_reminder_togglesq\u0000~\u0000\u0003\u0000t\u0000\u0012checking_frequencyt\u0000\u000260t\u0000\u0012selectAuthInstancet\u0000\u001Dhttps://pipedapi.kavin.rocks/t\u0000\u0008languaget\u0000\u0003syst\u0000\u000Ebuffering_goalt\u0000\u0003200t\u0000\u000Fdata_saver_modeq\u0000~\u0000\u0004t\u0000\u000Eseek_incrementt\u0000\u00015t\u0000\u001Clegacy_subscriptions_columnst\u0000\u00013t\u0000\u0014system_caption_styleq\u0000~\u0000\u0004t\u0000\u000Fauto_fullscreenq\u0000~\u0000\u0008t\u0000\u000Ebreak_remindert\u0000\u000260t\u0000\u0014player_audio_qualityt\u0000\u0004bestt\u0000"[truncated 950 chars]; line: 1, column: 2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:1)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:3)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:41)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:27)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:10)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1)
	at androidx.room.RoomDatabase$$ExternalSyntheticLambda0.onActivityResult(R8$$SyntheticClass:11)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:12)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:48)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:9)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:11)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:11)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:8)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:22)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
	at android.app.Activity.performStart(Activity.java:8315)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	... 3 more
 
</p>
</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you please provide the error log?

**Comment by lonelytheraphosidae** [comment]
It's collapsed under other details.

**Comment by Bnyro** [comment]
Appears to be an issue when backing up certain boolean preferences, probably need to find a different way for it!

**Comment by zeitrechnen** [comment]
The same here with version 0.6.1. I have deselected Home in the navigation bar, maybe the problem is related to this: `bottomNav.menu.findItem(it.id) must not be null`

```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221005.003/2022101500:user/release-keys
package: com.github.libretube:20
process: com.github.libretube

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.libretube/com.github.libretube.ui.activities.MainActivity}: java.lang.NullPointerException: bottomNav.menu.findItem(it.id) must not be null
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3677)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3814)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7904)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.NullPointerException: bottomNav.menu.findItem(it.id) must not be null
    at com.github.libretube.ui.activities.MainActivity.onCreate(MainActivity.kt:65)
    at android.app.Activity.performCreate(Activity.java:8341)
    at android.app.Activity.performCreate(Activity.java:8320)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1389)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3658)
    ... 14 more

```

**Comment by Bnyro** [comment]
> The same here with version 0.6.1. I have deselected Home in the navigation bar, maybe the problem is related to this: `bottomNav.menu.findItem(it.id) must not be null`
> 
> ```
> type: crash
> osVersion: google/bluejay/bluejay:13/TP1A.221005.003/2022101500:user/release-keys
> package: com.github.libretube:20
> process: com.github.libretube
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.libretube/com.github.libretube.ui.activities.MainActivity}: java.lang.NullPointerException: bottomNav.menu.findItem(it.id) must not be null
>     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3677)
>     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3814)
>     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
>     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
>     at android.os.Handler.dispatchMessage(Handler.java:106)
>     at android.os.Looper.loopOnce(Looper.java:201)
>     at android.os.Looper.loop(Looper.java:288)
>     at android.app.ActivityThread.main(ActivityThread.java:7904)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
>     at com.android.internal.os.ExecInit.main(ExecInit.java:49)
>     at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
>     at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
> Caused by: java.lang.NullPointerException: bottomNav.menu.findItem(it.id) must not be null
>     at com.github.libretube.ui.activities.MainActivity.onCreate(MainActivity.kt:65)
>     at android.app.Activity.performCreate(Activity.java:8341)
>     at android.app.Activity.performCreate(Activity.java:8320)
>     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1389)
>     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3658)
>     ... 14 more
> 
> ``` 

Your issue is related to #1551, I'll need to find a way to make these backups work again at the next release. For now you need to clear the app data and setup all your settings manually, sorry!

**Comment by Bnyro** [comment]
Shouldn't be an issue anymore.
