### ISSUE TITLE
Error appearing sometimes out of the blue when using LibreTube (watching or searching for a video)

### ISSUE THREAD

**Issue by olgak0096** [libre-tube/LibreTube#1415]
### Steps to reproduce

I didn't notice anything special. I was normally using this app. Then it crashed. This happened to me many times and recently, on Sept 28th, I saved the error message.

### Expected behavior

java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.github.libretube.db.obj.WatchPosition.videoId' on a null object reference
	at com.github.libretube.db.dao.WatchPositionDao_Impl$2.bind(WatchPositionDao_Impl.java:2)
	at androidx.room.EntityDeletionOrUpdateAdapter.handle(EntityDeletionOrUpdateAdapter.java:2)
	at com.github.libretube.db.dao.WatchPositionDao_Impl.delete(WatchPositionDao_Impl.java:3)
	at com.github.libretube.db.DatabaseHelper$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:6)
	at java.lang.Thread.run(Thread.java:764)

### Actual behavior

It just crashes and exits.

### LibreTube version

0.5.0

### Android version

Android 9 - Pie

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Got fixed with 0.6.0
