### ISSUE TITLE
App crash - Watch History

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1481]
### Steps to reproduce

If you delete to many videos in the watch history the app will crash.

### Expected behavior

App should delete the history 

### Actual behavior

App crashes

### LibreTube version

0.6.0

### Android version

Android 12 One UI 4.1

### Other details

The number of videos you can delete is different every time.

https://user-images.githubusercontent.com/97352673/193547954-824f8d30-90a1-4c5a-b56f-01acf8ad4a38.mp4

Error Message:

java.lang.IndexOutOfBoundsException: Index: 16, Size: 16
at java.util.ArrayList.remove(ArrayList.java:503)
at com.github.libretube.ui.adapters.WatchHistoryAdapter$$ExternalSyntheticLambda2.onClick(R8$$SyntheticClass:3)
at android.view.View.performClick(View.java:7792)
at android.view.View.performClickInternal(View.java:7769)
at android.view.View.access$3800(View.java:910)
at android.view.View$PerformClick.run(View.java:30218)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
The number of videos you can delete is different every time.
