### ISSUE TITLE
Unable to open LT

### ISSUE THREAD

**Issue by Flam3z** [libre-tube/LibreTube#1551]
### Steps to reproduce

I just updated to the latest version and the icon shows on screen then the app just seems to crash each time.

### Expected behavior

Expect to be taken to the subscriptions page upon opening the app.

### Actual behavior

App crashes and android tells me its a "cache issue" but after clearing cache the issue still persists.

### LibreTube version

0.6.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Upload some logs to track down the cause of the issue.
Also can you try fresh installing? Uninstall then reinstall

**Comment by steewbsd** [comment]
I have the same problem after updating.

**Comment by Bnyro** [comment]
Could you please try to clear the app data?

**Comment by steewbsd** [comment]
I can confirm cleaning the data fixes it.

**Comment by Bnyro** [comment]
It's probably caused by an update to the navigation bar items code which is incompatible with the previous one.
I'll probably just pin the issue since only people that changed the navigation bar order/items should be affected!

**Comment by steewbsd** [comment]
Indeed, I changed the order of the navigation bar. I suppose this is also the cause for the OP. It's a good idea to pin it for now!

**Comment by Bnyro** [comment]
Pinned now, sorry for the trouble.
Obviously I wasn't able to spot the issue when testing because I didn't change the order of the navigation bar items in the previous version, I'll try to avoid such issues by adding code for migrating such things next time!

**Comment by karachikorai** [comment]
Hello Team,

Here is the full error Stack. Same issue. LT crashes on opening or while opening any videos.

java.lang.NullPointerException
	at androidx.appcompat.R$string.formatShort(Unknown Source:1)
	at com.github.libretube.ui.adapters.TrendingAdapter.onBindViewHolder(TrendingAdapter.kt:12)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:179)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:122)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:27129)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:2348)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.widget.ScrollView.onMeasure(ScrollView.java:699)
	at android.view.View.measure(View.java:27129)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:51)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:103)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:11)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:204)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.view.View.measure(View.java:27129)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:18)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:175)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1278)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4536)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3228)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3533)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by lu-ckystars** [comment]
I am also experiencing this issue, on two different pixels

**Comment by Bnyro** [comment]
see #1698
