### ISSUE TITLE
Libre tube crashes

### ISSUE THREAD

**Issue by tashijayla** [libre-tube/LibreTube#1574]
### Steps to reproduce

Try to open the app

### Expected behavior

The app to open

### Actual behavior

The app crashes

### LibreTube version

0.6.1

### Android version

Android 13

### Other details

I'm running GrapheneOS

```
type: crash
osVersion: google/redfin/redfin:13/TP1A.221005.002/2022101500:user/release-keys
package: com.github.libretube:20
process: com.github.libretube

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.libretube/com.github.libretube.ui.activities.MainActivity}: java.lang.NullPointerException: bottomNav.menu.findItem(it.id) must not be null
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3677)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3814)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.NullPointerException: bottomNav.menu.findItem(it.id) must not be null
	at com.github.libretube.ui.activities.MainActivity.onCreate(MainActivity.kt:65)
	at android.app.Activity.performCreate(Activity.java:8341)
	at android.app.Activity.performCreate(Activity.java:8320)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1389)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3658)
	... 14 more

```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KurozyOS** [comment]
Think it is relevant to #1551

**Comment by Bnyro** [comment]
Yes, that's the same issue! Please delete the app data.

**Comment by xIUPITERx** [comment]
Why did you change the title of the issue?

**Comment by Bnyro** [comment]
Lol, wtf is going on here

**Comment by tashijayla** [comment]
> Why did you change the title of the issue?

Because someone noted that it was the same as another persons issue, and because someone marked my issue as closed, so i didn't think it would matter if i make my own issue as closed, i posted Lot's of device information, on my device it says only share crash logs with people you trust and unfortunately GitHub posts are public i think and forever so I wanted to remove my personal information, in future would it be better if i only change the report and not the title?, and what is the best way for me to get crash log's to app developers?

**Comment by Bnyro** [comment]
1. Well, it would still be more transparent if you just left it as it was, no need to delete everything you wrote down then as it still could be helpful for others.
2. The crash logs can just be pasted into the issue template as they don't include any personal information (otherwise there would never be a field for it).

**Comment by tashijayla** [comment]
> 1. Well, it would still be more transparent if you just left it as it was, no need to delete everything you wrote down then as it still could be helpful for others.
> 2. The crash logs can just be pasted into the issue template as they don't include any personal information (otherwise there would never be a field for it).

Thank you for all the info, and sorry for all the confusion, I was trying to be helpful but instead ended up wasting your time, I'll try and do better in future, I'm still new to GitHub and learning how to get involved with projects to hopefully help out
