### ISSUE TITLE
Attempt to invoke interface method

### ISSUE THREAD

**Issue by mjain234** [libre-tube/LibreTube#1587]
### Steps to reproduce

Just launch the app ,also the app doesn't get crashed, instead show this error logs:

java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.exoplayer2.Player.clearMediaItems()' on a null object reference
	at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ComponentListener.onStop(MediaSessionConnector.java:8)
	at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onStop(MediaSessionCompat.java:3)
	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1611)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7824)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

Why this is about?
    

### Expected behavior

NIL

### Actual behavior

NIL

### LibreTube version

0.6.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Noticed that too already, probably the player doesn't get destroyed properly when the background-playing service gets finished or stopped. Not a priority for now though as it doesn't have any serious negative impacts on the app's behavior.
