### ISSUE TITLE
Crash when clicking specific video from history

### ISSUE THREAD

**Issue by Flam3z** [libre-tube/LibreTube#1667]
### Steps to reproduce

Issue occured randomly when i selected a specific video.

### Expected behavior

To be able to buffer and play the video.

### Actual behavior

Everytime I try and click on the video it crashes.

### LibreTube version

0.6.1

### Android version

Android 12

### Other details

Error Log: java.lang.NullPointerException
	at androidx.appcompat.R$string.formatShort(Unknown Source:1)
	at com.github.libretube.ui.adapters.TrendingAdapter.onBindViewHolder(TrendingAdapter.kt:12)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:179)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:122)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:27129)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:2348)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.widget.ScrollView.onMeasure(ScrollView.java:699)
	at android.view.View.measure(View.java:27129)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:51)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:103)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:11)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:204)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.view.View.measure(View.java:27129)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:18)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:175)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1277)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4510)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3202)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3507)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2893)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10445)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please use something like "Crash when doing xy" as title instead of the exception title!

**Comment by Flam3z** [comment]
Got it, my apologies

**Comment by VedxP** [comment]
Me too encountered same crash, ig; upon playing video from channel page.

Here's the log:
```
java.lang.NullPointerException
	at androidx.appcompat.R$string.formatShort(Unknown Source:1)
	at com.github.libretube.ui.adapters.TrendingAdapter.onBindViewHolder(TrendingAdapter.kt:12)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:179)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:122)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:26164)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26164)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1449)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.widget.ScrollView.onMeasure(ScrollView.java:462)
	at android.view.View.measure(View.java:26164)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:51)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:103)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:11)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:204)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26164)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:18)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:175)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:826)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4037)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2704)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2989)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2416)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9478)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1242)
	at android.view.Choreographer.doCallbacks(Choreographer.java:996)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:383)
	at android.view.Choreographer.doFrame(Choreographer.java:865)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1227)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
    
```
