### ISSUE TITLE
App crashes when opening YouTube link

### ISSUE THREAD

**Issue by Queuecumbr** [libre-tube/LibreTube#1668]
### Steps to reproduce

App crashes when opening https://youtu.be/HM3xU7LyC7c
I am using GrapheneOS which does use a hardened malloc, so I'm unsure if this would be reproducible on vanilla android since memory accesses would not be as locked down.
Stack trace is as follows:

```
type: crash
osVersion: google/raven/raven:13/TP1A.221005.002/2022102600:user/release-keys
package: com.github.libretube:20
process: com.github.libretube

java.lang.NullPointerException
	at androidx.appcompat.R$string.formatShort(Unknown Source:1)
	at com.github.libretube.ui.adapters.TrendingAdapter.onBindViewHolder(TrendingAdapter.kt:12)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:179)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:122)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:26358)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26358)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26358)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1442)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.widget.ScrollView.onMeasure(ScrollView.java:458)
	at android.view.View.measure(View.java:26358)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:51)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:103)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:11)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:204)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:26358)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26358)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:18)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:175)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:26358)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:26358)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26358)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26358)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26358)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:758)
	at android.view.View.measure(View.java:26358)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3838)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2570)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2834)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

### Expected behavior

Video should play.

### Actual behavior

App crashes immediately upon opening link and displays a stack trace.

### LibreTube version

0.6.1

### Android version

Android 13 (GrapheneOS)

### Other details

Using Pixel 6 Pro with GrapheneOS.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Same issue as #1667, YouTube changed something and now views don't seem to get returned properly from the API I think.

**Comment by xIUPITERx** [comment]
Why is this closed? Is the issue solved?
