### ISSUE TITLE
Failed to share videos with libretube

### ISSUE THREAD

**Issue by 41337** [libre-tube/LibreTube#1689]
### Steps to reproduce

- 1 open youtube
- 2 select a video
- 3 Share video with Libretube Apk

### Expected behavior

Libretube was expected to open the video that was shared

### Actual behavior

It opens the video in sequence displays this error: 

```log
java.lang.NullPointerException
	at androidx.appcompat.R$string.formatShort(Unknown Source:1)
	at com.github.libretube.ui.adapters.TrendingAdapter.onBindViewHolder(TrendingAdapter.kt:12)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:179)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:122)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:26392)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26392)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1441)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.widget.ScrollView.onMeasure(ScrollView.java:458)
	at android.view.View.measure(View.java:26392)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:51)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:103)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:11)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:204)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26392)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:18)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:175)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:829)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3948)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2648)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2946)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2363)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9310)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1129)
	at android.view.Choreographer.doCallbacks(Choreographer.java:926)
	at android.view.Choreographer.doFrame(Choreographer.java:840)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1114)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8298)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
    
```

### LibreTube version

0.6.1

### Android version

12

### Other details

I use a Redmi Note 10S MIUI 13
I'm using the universal build of libretube 
[Problem demo video](https://vimeo.com/765246985) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Don't wonder, I started working on that before the issue got opened x)
