### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by noClaps** [libre-tube/LibreTube#1698]
### Steps to reproduce

1. Download 0.7.0 arm64 release
2. Try to open the app
3. App crashes

### Expected behavior

App should open

### Actual behavior

App crashes

### LibreTube version

0.7.0

### Android version

Android 13

### Other details

```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221005.003/2022102800:user/release-keys
package: com.github.libretube:21
process: com.github.libretube

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.libretube/com.github.libretube.ui.activities.MainActivity}: java.lang.NullPointerException: bottomNav.menu.findItem(it.id) must not be null
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3677)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3814)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: java.lang.NullPointerException: bottomNav.menu.findItem(it.id) must not be null
	at com.github.libretube.ui.activities.MainActivity.onCreate(MainActivity.kt:464)
	at android.app.Activity.performCreate(Activity.java:8341)
	at android.app.Activity.performCreate(Activity.java:8320)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1389)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3658)
	... 12 more

```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please clear the app data, information about the issue can be found at #1551.

**Comment by 4JX** [comment]
@Bnyro I had already encountered this issue when updating to 6.1 before (which the linked issue references) and it is still present from 6.1 to 7.0.

I recon it would be better to keep an issue open about this if its still going to be a problem when updating in the future, as having to delete the app's data is a less than ideal.

Changelog doesn't reference the bottom nav bar's code being changed again, was there something I missed?

**Comment by Bnyro** [comment]
Oh, damn, I thought you just skipped 0.7.0 or so ...
The app crashes because it tries to identify the menu items by there IDs, but it seems like Android just regenerates those each time a release apk is built, and therefore it searches for non-existing IDs. I'll rewrite it to become independent from IDs and be handled in a try catch loop so that this can't happen again next time!

**Comment by Bnyro** [comment]
Oh, damn, I thought you just skipped 0.7.0 or so ...
The app crashes because it tries to identify the menu items by there IDs, but it seems like Android just regenerates those each time a release apk is built, and therefore it searches for non-existing IDs. I'll rewrite it to become independent from IDs and be handled in a try catch loop so that this can't happen again next time!

**Comment by noClaps** [comment]
Sorry, probably should have specified I was coming from 0.6.1
