### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KalpanaChetan** [libre-tube/LibreTube#1702]
### Steps to reproduce

I don't know

### Expected behavior

Open app

### Actual behavior

java.lang.RuntimeException: Unable to start service com.github.libretube.services.DownloadService@56ade65 with null: java.lang.NullPointerException
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3696)
	at android.app.ActivityThread.-wrap21(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException
	at com.github.libretube.services.DownloadService.onStartCommand(DownloadService.kt:16)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3679)
	... 8 more
    

### LibreTube version

0.7.0

### Android version

8

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The app won't start the download service just by opening it, a more detailed description on what caused the issue would be better!

**Comment by KalpanaChetan** [comment]
I open the app and it shows the message .
I copy the message and paste it on github.
If a file related to the bug is store in the mobile.
Please tell me where the file is saved .
I will definitely upload it

**Comment by Bnyro** [comment]
As it doesn't seem to happen anymore and I've no idea how to reproduce I'm gonna close the issue for now!
