### ISSUE TITLE
Having two downloads crash the app

### ISSUE THREAD

**Issue by Deathemonic** [libre-tube/LibreTube#1746]
### Steps to reproduce

1. Download one video and viewing the download page
2. Exit the app
3. Download another video and viewing the download page

### Expected behavior

Just open the download page and not crash

### Actual behavior

Crash and just shows this error message and it's not a one time thing the download page will not open if you have 2 downloads in it. It also still exist on version 0.6.1

### LibreTube version

0.7.0

### Android version

Android 8

### Other details

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.github.libretube.ui.fragments.DownloadsFragment.onViewCreated(DownloadsFragment.kt:67)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:305)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:154)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1085)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:92)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:74)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:4)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:192)
	at android.app.ActivityThread.main(ActivityThread.java:6748)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:867)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by wifi-left** [comment]
When I only downloaded one video, it crashed. And the application cannot be reopened.
I'm using a virtual machine and I don't know if that's the problem.

**Comment by Relwi** [comment]
I can reproduce it @wifi-left, It crashed when is downloading one video.

@Bnyro I was able to fix the error with this example https://stackoverflow.com/a/50032174, but it fixes only when is downloading one video, if you have two or more, the app crashes. I think this issue has to do with the StackOverflow problem (https://stackoverflow.com/q/50032000), so we have a starting point to deal with it.

**Comment by wifi-left** [comment]
It also crashed when I opened the download screen after downloading the video.
But it won't crash when there's no video.

**Comment by Bnyro** [comment]
> @Bnyro I was able to fix the error with this example https://stackoverflow.com/a/50032174, but it fixes only when is downloading one video, if you have two or more, the app crashes. I think this issue has to do with the StackOverflow problem (https://stackoverflow.com/q/50032000), so we have a starting point to deal with it.
>
Thank you for having a look at that <3

The StackOverflow is about removing items but the OP doesn't even do that when opening the downloads tab, does he?

**Comment by Relwi** [comment]
> The StackOverflow is about removing items but the OP doesn't even do that when opening the downloads tab, does he?

No, but in my case was this line that it was giving me the error, when opening the Downloads tab:
https://github.com/libre-tube/LibreTube/blob/e4064c29eac733510fcb9b7cc5dc492863142747/app/src/main/java/com/github/libretube/util/DownloadHelper.kt#L60

**Comment by Bnyro** [comment]
> > The StackOverflow is about removing items but the OP doesn't even do that when opening the downloads tab, does he?
> 
> No, but in my case was this line that it was giving me the error, when opening the Downloads tab:
> 
> https://github.com/libre-tube/LibreTube/blob/e4064c29eac733510fcb9b7cc5dc492863142747/app/src/main/java/com/github/libretube/util/DownloadHelper.kt#L60
>
Oh, you're right, that makes sense!

**Comment by Bnyro** [comment]
I hate when error logs are obfuscated like that ...
