### ISSUE TITLE
Error msg when started, app closed

### ISSUE THREAD

**Issue by csa93tv** [libre-tube/LibreTube#1752]
### Steps to reproduce

1. Open the app
2. Play any videos

### Expected behavior

It should be no error logs in the beginning and the app won't closed when i want to play the videos.

### Actual behavior

1. When open the app, error logs appear
2. When clicking any videos, the app closed

### LibreTube version

0.7.0

### Android version

Android 12

### Other details

java.lang.NullPointerException
	at androidx.appcompat.R$string.formatShort(Unknown Source:1)
	at com.github.libretube.ui.adapters.TrendingAdapter.onBindViewHolder(TrendingAdapter.kt:12)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:179)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:122)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:26393)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26393)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26393)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1441)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.widget.ScrollView.onMeasure(ScrollView.java:458)
	at android.view.View.measure(View.java:26393)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:51)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:103)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:11)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:204)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:26393)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26393)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:18)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:175)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:26393)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:26393)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26393)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26393)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26393)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7095)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:830)
	at android.view.View.measure(View.java:26393)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3952)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2652)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2950)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2369)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9345)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1121)
	at android.view.Choreographer.doCallbacks(Choreographer.java:918)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8268)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The bug was fixed with 0.7.0 hence the stack trace is impossible to reproduce with v0.7.0 although you provided that as version!
