### ISSUE TITLE
Crash on opening Playlist options

### ISSUE THREAD

**Issue by swarnendumaiti** [libre-tube/LibreTube#1893]
### Steps to reproduce

1. Open Playlist
2. Click on '3 dot' button
![Screenshot_20221118-145507](https://user-images.githubusercontent.com/86847643/202668036-8fc28ff9-b08e-45eb-b713-0b7a28928926.png)
![Screenshot_20221118-145510](https://user-images.githubusercontent.com/86847643/202668067-ad83b39d-9414-4444-b31e-7a2d43090814.png)

### Expected behavior

This is the first time I'm clicking the button so I don't know what happens. But it's expected to open the playlist menu.

### Actual behavior

The app crashes.
On next app open the following error result is shown:
![Screenshot_20221118-145527](https://user-images.githubusercontent.com/86847643/202668468-403be169-0337-47b4-b3b3-8df9109915c1.png)

Full error result ⬇️

java.lang.NullPointerException
	at com.github.libretube.ui.views.CustomExoPlayerView$$ExternalSyntheticLambda2.onClick(R8$$SyntheticClass:104)
	at android.view.View.performClick(View.java:7467)
	at android.view.View.performClickInternal(View.java:7444)
	at android.view.View.access$3700(View.java:840)
	at android.view.View$PerformClick.run(View.java:28831)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
    

### LibreTube version

0.7.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by swarnendumaiti** [comment]
The '3 dot' button referred by me above in step 2 refers to the playlist's '3 dot' button not the app's.
![Screenshot_20221118-145510~2](https://user-images.githubusercontent.com/86847643/202669401-de751e49-42ca-4514-83e9-307516b90090.png)

**Comment by swarnendumaiti** [comment]
Does this mean you'll fix it?

**Comment by Bnyro** [comment]
It got fixed in the PR above your last message, yes

**Comment by Bnyro** [comment]
Umm, you know that you need to update the app first before getting fixes? The fix is not even released yet...

**Comment by swarnendumaiti** [comment]
Oops I just forgot that. Sorry sir for me being stupid. 😄
