### ISSUE TITLE
Crash upon deleting videos from the watch history

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#1919]
### Steps to reproduce

1. Watch any video
2. Go to Library > watch history
3. Try to delete any video from watch history 

### Expected behavior

Video should be removed from watch history ( list )

### Actual behavior

App crashes

### LibreTube version

v0.8.0

### Android version

Android 12

### Other details

device info:
Realme 7 with android 12 and Realme ui 3.0 skin

Logs:
java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
	at androidx.room.RoomDatabase.assertNotMainThread(RoomDatabase.java:30)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:1)
	at com.github.libretube.db.dao.WatchHistoryDao_Impl.delete(WatchHistoryDao_Impl.java:8)
	at com.github.libretube.ui.adapters.WatchHistoryAdapter.removeFromWatchHistory(WatchHistoryAdapter.kt:17)
	at com.github.libretube.ui.adapters.WatchHistoryAdapter$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:10)
	at android.view.View.performClick(View.java:7498)
	at android.view.View.performClickInternal(View.java:7471)
	at android.view.View.access$3700(View.java:843)
	at android.view.View$PerformClick.run(View.java:29098)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by soul-winner** [comment]
Same result with Google Pixel 4a

**Comment by NeeRaj-2401** [comment]
@Bnyro , i m facing few more bugs on my same device.. before i open a new issue .. just have a look to  that
1. App shortcuts missing (as it is already implemented)
2. Clicking on notification of playing video or new streams should open the app and the respective activity but doesn't do anything.

**Comment by Bnyro** [comment]
> @Bnyro , i m facing few more bugs on my same device.. before i open a new issue .. just have a look to  that
> 1. App shortcuts missing (as it is already implemented)
> 2. Clicking on notification of playing video or new streams should open the app and the respective activity but doesn't do anything.
> 
>
Just tested but I can't reproduce any of those!

**Comment by NeeRaj-2401** [comment]
> Just tested but I can't reproduce any of those!

Recorded both the issues

https://user-images.githubusercontent.com/88180887/202891572-10665951-3c71-43d4-89da-abb2eb5a1cde.mp4

**Comment by Bnyro** [comment]
The first one is caused by the different app icon you selected (can be fixed), it's really awesome that someone uses the app icon I created although I've no idea of designing, thanks :)
I've no idea why clicking on the notification doesn't work for you, works fine for me in all possible scenarios!

**Comment by NeeRaj-2401** [comment]
> it's really awesome that someone uses the app icon I created although I've no idea of designing, thanks :) 

Among all the others, this one looks best in terms of design , colors and minimal.. 

> I've no idea why clicking on the notification doesn't work for you, works fine for me in all possible scenarios!

So, I am Raising that as an issue..

**Comment by Bnyro** [comment]
Yes, please open new issues for both of them, I doubt I can have a look today
