### ISSUE TITLE
Crash on changing quality.

### ISSUE THREAD

**Issue by swarnenduu** [libre-tube/LibreTube#1934]
### Steps to reproduce

Found the issue on only one channel:

1. Open this video in LibreTube app ⬇️:
https://piped.video/watch?v=6MGmcboFpB8
2. Try to change quality.

### Expected behavior

Able to change quality.

### Actual behavior

App Crashes

Crash log ⬇️

java.lang.NumberFormatException: For input string: "LBRY"
	at java.lang.Integer.parseInt([Integer.java:747](http://integer.java:747/))
	at java.lang.Integer.parseInt([Integer.java:865](http://integer.java:865/))
	at com.github.libretube.ui.fragments.PlayerFragment.qualityToInt(PlayerFragment.kt:21)
	at com.github.libretube.ui.fragments.PlayerFragment.onQualityClicked(PlayerFragment.kt:142)
	at com.github.libretube.ui.views.CustomExoPlayerView$initializeAdvancedOptions$1$2.invoke(CustomExoPlayerView.kt:7)
	at com.github.libretube.ui.adapters.BottomSheetAdapter$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:21)
	at android.view.View.performClick([View.java:7467](http://view.java:7467/))
	at android.view.View.performClickInternal([View.java:7444](http://view.java:7444/))
	at android.view.View.access$3700([View.java:840](http://view.java:840/))
	at android.view.View$[PerformClick.run](http://performclick.run/)([View.java:28831](http://view.java:28831/))
	at android.os.Handler.handleCallback([Handler.java:978](http://handler.java:978/))
	at android.os.Handler.dispatchMessage([Handler.java:104](http://handler.java:104/))
	at android.os.Looper.loopOnce([Looper.java:238](http://looper.java:238/))
	at android.os.Looper.loop([Looper.java:357](http://looper.java:357/))
	at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:8090](http://activitythread.java:8090/))
	at java.lang.reflect.Method.invoke(Native Method)
	at [com.android](http://com.android/).internal.os.RuntimeInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)([RuntimeInit.java:548](http://runtimeinit.java:548/))
	at [com.android](http://com.android/).internal.os.ZygoteInit.main([ZygoteInit.java:1026](http://zygoteinit.java:1026/))

### LibreTube version

0.8.0

### Android version

Android 12 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Flam3z** [comment]
I encounter the same issue on my galaxy S10 running android 12.

**Comment by swarnenduu** [comment]
Yeah @Bnyro said that 'it's caused by them having a LBRY stream available which we currently don't handle properly when listing the available resolutions'.

I just raise the issue so that it's fixed later.
