### ISSUE TITLE
Playback crashes with latest release and non-auto quality

### ISSUE THREAD

**Issue by silentTeee** [libre-tube/LibreTube#1984]
### Steps to reproduce

1. Select video for playback
2. Go to quality, select anything that isn't auto
3. Attempt to continue playback

### Expected behavior

Playback should try to apply new quality and reload

### Actual behavior

Crashes with the following error

```
java.lang.NumberFormatException: For input string: "LBRY"
	at java.lang.Integer.parseInt(Integer.java:747)
	at java.lang.Integer.parseInt(Integer.java:865)
	at com.github.libretube.ui.fragments.PlayerFragment.qualityToInt(PlayerFragment.kt:21)
	at com.github.libretube.ui.fragments.PlayerFragment.onQualityClicked(PlayerFragment.kt:142)
	at com.github.libretube.ui.views.CustomExoPlayerView$initializeAdvancedOptions$1$2.invoke(CustomExoPlayerView.kt:7)
	at com.github.libretube.ui.adapters.BottomSheetAdapter$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:21)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29335)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### LibreTube version

0.8.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by silentTeee** [comment]
Sorry bout that, didn't think to check the "Closed" Issue category, you work _fast!_ 😄

**Comment by Bnyro** [comment]
No worries, I'm used to closing the same issue up to four or five times in some cases :)
