### ISSUE TITLE
NPE when starting DownloadService

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#2191]
### Steps to reproduce

Hey Guys,

Here is the log:

java.lang.RuntimeException: Unable to start service com.github.libretube.services.DownloadService@e35a648 with null: java.lang.NullPointerException
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4709)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2182)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.NullPointerException
	at com.github.libretube.services.DownloadService.onStartCommand(DownloadService.kt:24)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4691)
	... 11 more
    

### Expected behavior

Should not crash

### Actual behavior

Crashed when browsing

### LibreTube version

0.9.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce, any specific video you have been trying to download?
