### ISSUE TITLE
crash after import

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#2306]
### Steps to reproduce

Happened after I mess with import / export configuration & then try to restart the app.

### Expected behavior

It shouldn't crash

### Actual behavior

crashes

### LibreTube version

0.9.0

### Android version

Android 13

### Other details

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:329)
	at com.github.libretube.ui.fragments.SubscriptionsFragment.showFeed(SubscriptionsFragment.kt:131)
	at com.github.libretube.ui.fragments.SubscriptionsFragment$onViewCreated$2.invoke(SubscriptionsFragment.kt:19)
	at com.github.libretube.ui.fragments.SubscriptionsFragment$$ExternalSyntheticLambda1.onChanged(R8$$SyntheticClass:10)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:30)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:56)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:15)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:19)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Kruna1Pate1** [comment]
Looks like importing settings from the `JSON` file can't differentiate between `Int` and `Long` and both are [loaded as `Int`](https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/util/BackupHelper.kt#L92).

**Comment by Bnyro** [comment]
Hmm, then we should probably prioritize Long's as I don't think we use any Int's inside the app for preferences currently.

**Comment by Kruna1Pate1** [comment]
I think we use int for [navigation bar item](https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/util/NavBarHelper.kt#L115-#L128) .

**Comment by Kruna1Pate1** [comment]
Than using long only seems good idea.
