### ISSUE TITLE
Unable to play videos

### ISSUE THREAD

**Issue by Flam3z** [libre-tube/LibreTube#2360]
### Steps to reproduce

The steps to reproduce are kind of inconsistent as some videos I am able to watch with no issues then others just show a play button and when I press it, nothing happens.

2 video examples: https://piped.video/watch?v=LdDECvOmXUc

https://piped.video/watch?v=ES5kImp0geE
### Expected behavior

Should be able to start the video.

### Actual behavior

Play button shows when does not play when pressed.

### LibreTube version

0.9.0

### Android version

Android 12

### Other details
When viewing the quality list, the default is just 0p and I am unable to set a real quality.

If more videos or information is need please let me know.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Kruna1Pate1** [comment]
If you can provide recording or something it would be helpful.

**Comment by Flam3z** [comment]
Heres the recording:

https://user-images.githubusercontent.com/57234536/207247960-09a36183-4df7-4047-ad67-0f6d0e67908d.mp4

**Comment by Bnyro** [comment]
Both videos play fine for me as well :/

**Comment by Bnyro** [comment]
Are you able to select another quality? Or can you check `Use HLS` in the quality settings?

**Comment by Flam3z** [comment]
No, im not able to, it just says 0p

**Comment by Flam3z** [comment]
Now when I clear data and cache and restore everything + login, i get this error when trying to load my subscriptions


> java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:329)
	at com.github.libretube.ui.fragments.SubscriptionsFragment.showFeed(SubscriptionsFragment.kt:131)
	at com.github.libretube.ui.fragments.SubscriptionsFragment$onViewCreated$2.invoke(SubscriptionsFragment.kt:19)
	at com.github.libretube.ui.fragments.SubscriptionsFragment$$ExternalSyntheticLambda1.onChanged(R8$$SyntheticClass:10)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:30)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:56)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:15)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:19)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by Bnyro** [comment]
#2306

**Comment by Bnyro** [comment]
> No, im not able to, it just says 0p
>
What about using HLS though?

**Comment by Flam3z** [comment]
Unable to since importing now gives me a crash loop :/

**Comment by Flam3z** [comment]
> > No, im not able to, it just says 0p
> 
> What about using HLS though?

Nothing works, selecting any does not change it.

**Comment by Bnyro** [comment]
I assume you tried different instances as well?

**Comment by Flam3z** [comment]
Tried it on piped and piped has an odd issues of infinite loading or nothing loads at all. I don't have any heavy extensions that would conflict with the site.

**Comment by Bnyro** [comment]
You're on iOS?

**Comment by Flam3z** [comment]
Im on android 12

**Comment by Bnyro** [comment]
Still not able to reproduce, I hope it's not getting worse for you in the future, but doubt we can do anything about it unfortunately.
