### ISSUE TITLE
Crash during playback

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2373]
### Steps to reproduce

Delete videos from a playlist
2. Watch a video from the playlist
3. App crashes
4. When reopend, deleted videos are back

Play a video

### Expected behavior

Should play to the end

### Actual behavior

Crashes

### LibreTube version

0.9.0

### Android version

Android 13 One UI 5.0

### Other details

retrofit2.HttpException: HTTP 504 
	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:140)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:11)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@59abd19, Dispatchers.IO]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Has the issue been reproducible with the latest version? There have been some past changes that could have resolved it with the release of v0.10.0 and should catch such behavior now.

**Comment by xIUPITERx** [comment]
The main problem seems to be fixed, but the thumbnail of the playlist changed back to the old video after I restarted the app.
