### ISSUE TITLE
Problems with importing playlists, subscriptions

### ISSUE THREAD

**Issue by Wjxfi** [libre-tube/LibreTube#2406]
### Steps to reproduce

try to upload a very large data file.

newpipe

### Expected behavior

data import

### Actual behavior

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	... 1 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('�' (code 65533 / 0xfffd)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"��\u0000\u0005sr\u0000\u0011java.util.HashMap\u0005\u0007���\u0016`�\u0003\u0000\u0002F\u0000
loadFactorI\u0000\u0009thresholdxp?@\u0000\u0000\u0000\u0000\u0000`w\u0008\u0000\u0000\u0000�\u0000\u0000\u0000Vt\u0000&scale_to_square_image_in_notificationssr\u0000\u0011java.lang.Boolean� r�՜��\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000t\u0000\u0015screen_brightness_keysr\u0000\u000Fjava.lang.Float��ɢ�<��\u0002\u0000\u0001F\u0000\u0005valuexr\u0000\u0010java.lang.Number���\u001D\u000B���\u0002\u0000\u0000xp\u0000\u0000\u0000\u0000t\u0000\u001Aresume_on_audio_focus_gainq\u0000~\u0000\u0004t\u0000\u0014use_inexact_seek_keyq\u0000~\u0000\u0004t\u0000\u000Btablet_modet\u0000\u0004autot\u0000\u001Bshow_age_restricted_contentsq\u0000~\u0000\u0003\u0001t\u0000\u001Fscreen_brightness_timestamp_keysr\u0000\u000Ejava.lang.Long;��̏#�\u0002\u0000\u0001J\u0000\u0005valuexq\u0000~\u0000\u0007\u0000\u0000\u0001��S��t\u0000\u001Cclear_queue_confirmation_keyq\u0000~\u0000"[truncated 3070 chars]; line: 1, column: 2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:3)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:42)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:282)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:169)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:42)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:15)
	at com.github.libretube.ui.preferences.BackupRestoreSettings$$ExternalSyntheticLambda5.onActivityResult(R8$$SyntheticClass:103)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:66)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:18)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:329)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:51)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:10)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:57)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:69)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:58)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:34)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:58)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
	at android.app.Activity.performStart(Activity.java:8270)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3785)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2287)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	... 3 more
    

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	... 1 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'SQLite': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (StringReader); line: 1, column: 7]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:69)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:268)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:169)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:42)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:15)
	at com.github.libretube.ui.preferences.BackupRestoreSettings$$ExternalSyntheticLambda5.onActivityResult(R8$$SyntheticClass:103)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:66)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:18)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:329)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:51)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:10)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:57)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:69)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:58)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:34)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:58)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
	at android.app.Activity.performStart(Activity.java:8270)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3785)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2287)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	... 3 more
    

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	... 1 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('�' (code 65533 / 0xfffd)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"��\u0000\u0005sr\u0000\u0011java.util.HashMap\u0005\u0007���\u0016`�\u0003\u0000\u0002F\u0000
loadFactorI\u0000\u0009thresholdxp?@\u0000\u0000\u0000\u0000\u0000`w\u0008\u0000\u0000\u0000�\u0000\u0000\u0000Vt\u0000&scale_to_square_image_in_notificationssr\u0000\u0011java.lang.Boolean� r�՜��\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000t\u0000\u0015screen_brightness_keysr\u0000\u000Fjava.lang.Float��ɢ�<��\u0002\u0000\u0001F\u0000\u0005valuexr\u0000\u0010java.lang.Number���\u001D\u000B���\u0002\u0000\u0000xp\u0000\u0000\u0000\u0000t\u0000\u001Aresume_on_audio_focus_gainq\u0000~\u0000\u0004t\u0000\u0014use_inexact_seek_keyq\u0000~\u0000\u0004t\u0000\u000Btablet_modet\u0000\u0004autot\u0000\u001Bshow_age_restricted_contentsq\u0000~\u0000\u0003\u0001t\u0000\u001Fscreen_brightness_timestamp_keysr\u0000\u000Ejava.lang.Long;��̏#�\u0002\u0000\u0001J\u0000\u0005valuexq\u0000~\u0000\u0007\u0000\u0000\u0001��S��t\u0000\u001Cclear_queue_confirmation_keyq\u0000~\u0000"[truncated 3070 chars]; line: 1, column: 2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:3)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:42)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:282)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:169)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:42)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:15)
	at com.github.libretube.ui.preferences.BackupRestoreSettings$$ExternalSyntheticLambda5.onActivityResult(R8$$SyntheticClass:103)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:66)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:18)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:329)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:51)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:10)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:57)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:69)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:58)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:34)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:58)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
	at android.app.Activity.performStart(Activity.java:8270)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3785)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2287)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	... 3 more
    
![292007](https://user-images.githubusercontent.com/113500363/208212321-c714f740-79b4-4994-b2a4-a22249be15ad.jpg)

### LibreTube version

0.9.1

### Android version

android 12

**Comment by FireMasterK** [comment]
It seems like you're not importing a json/csv file. In NewPipe, you have to export subscriptions in JSON format.
