### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Wjxfi** [libre-tube/LibreTube#2413]
### Steps to reproduce

It just happened

### Expected behavior

It just happened

### Actual behavior

kotlin.UninitializedPropertyAccessException: lateinit property streams has not been initialized
	at com.github.libretube.ui.fragments.PlayerFragment.toggleDescription(PlayerFragment.kt:29)
	at com.github.libretube.ui.activities.AboutActivity$$ExternalSyntheticLambda3.onClick(R8$$SyntheticClass:56)
	at android.view.View.performClick(View.java:7753)
	at android.view.View.performClickInternal(View.java:7730)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29144)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
    

### LibreTube version

0.9.1

### Android version

android 12

**Comment by Bnyro** [comment]
Use the template.
