### ISSUE TITLE
ArrayIndexOutOfBoundsException when switching server under "censored" conditions

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2424]
### Steps to reproduce

1. Connect to a network in which some domains are blocked (including a Piped instance I guess - I cannot give a reproducible step here since I have no influence on the specific network I had the bug in)
2. You should not be able to load the video list
3. Try to switch the used Piped instance

### Expected behavior

You should be able to switch the server by clicking on an list item in the instances list.

### Actual behavior

- The instances list is sometimes empty, if it is not, a ArrayIndexOutOfBoundsException occurs
- _If the video list tries to load in step 2:_ you see a uncaught (I think) Chromium network issue as a toast
- I sometimes had a false "No network" error in step 2 although I could confirm that I have an internet connection

---

Stack trace for the ArrayIndexOutOfBoundsException:
<code>
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at com.github.libretube.ui.base.BasePreferenceFragment$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:15)
at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:9)
at android.widget.AdapterView.performItemClick(AdapterView.java:330)
at android.widget.AbsListView.performItemClick(AbsListView.java:1257)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3270)
at android.widget.AbsListView$3.run(AbsListView.java:4236)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7878)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
</code>

Video:
https://user-images.githubusercontent.com/60609373/208252085-ca2bd11a-6ccc-4cd6-a971-c3a286c41c49.mp4

### LibreTube version

0.9.0

### Android version

Android 13 QPR1

### Other details

I run GrapheneOS.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Would you mind retrying that with the latest debug builds? #2455 might have fixed that!

**Comment by Bnyro** [comment]
From the actions: https://github.com/libre-tube/LibreTube/actions/runs/3755918794

**Comment by Bnyro** [comment]
Assuming it's fixed as there are no recent updates on it.
