### ISSUE TITLE
Unable to Backup & Restore (Error)

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2429]
### Steps to reproduce

Edit 1. I'm using app without signing in
1. I had installed the fdroid version (0.9.0).
2. After seeing recent github update I backed up my data.
Settings > Backup & Restore > App Backup >  checked all entried > Backup
3. Then uninstalled that version (0.9.0).
4. Now, Installed 0.9.1 version from github.
5. Restored that [backed up] data.
Settings > Backup & Restore > App Backup > Restore
6. Got this error.

**Edit 1**. I'm using app without signing in
**Edit 2.** Now I installed that 0.9.0 version from fdroid from which I earlier made the backup. I can't restore my data even to this app from which I made the backup.
Is there any solution or all my data (subscriptions+playlists) is lost ?

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	... 1 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.github.libretube.db.obj.LocalPlaylistWithVideos` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (StringReader); line: 1, column: 42] (through reference chain: com.github.libretube.obj.BackupFile["localPlaylists"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:5)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:5)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:74)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:90)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:773)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:6)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:27)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:31)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:3)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:171)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:86)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:15)
	at com.github.libretube.ui.preferences.BackupRestoreSettings$$ExternalSyntheticLambda7.onActivityResult(R8$$SyntheticClass:94)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:66)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:18)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:329)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:51)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:10)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:57)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:69)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:58)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:34)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:58)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8018)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	... 3 more
    

### Expected behavior

It should restore all my [locally stored] subscriptions and playlists

### Actual behavior

It gave me above mentioned error.

### LibreTube version

0.9.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by tampos4** [comment]
[ Using without account ]

This issue is still not fixed.

### Android version
Android 12

### LibreTube version
0.10.0

### Steps to reproduce

1. Clean install LibreTube 0.10.0
2. Add some videos in a playlist, subscribe some channels, watch any video, change some settings etc.
3. Backup all data (Settings > Backup & restore > App backup > Backup all entries).
4. Clear app data or Uninstall and reinstall the app.
5. Restore from the backed up data (Settings > Backup & restore > App backup > Restore



java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	... 1 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.github.libretube.db.obj.LocalPlaylistItem` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"customInstances":[],"localPlaylists":[{"playlist":{"id":1,"name":"1","thumbnailUrl":"https://pipedproxy.kavin.rocks/vi_webp/E-k2bedh5Io/maxresdefault.webp?host=i.ytimg.com"},"videos":[{"duration":7783,"id":1,"playlistId":1,"thumbnailUrl":"https://pipedproxy.kavin.rocks/vi_webp/E-k2bedh5Io/maxresdefault.webp?host=i.ytimg.com","title":"Bhai | Full Hindi Movie | Suniel Shetty, Sonali Bendre, Pooja Batra, Kunal Khemu, Kader Khan","uploadDate":"2023-01-03","uploader":"Pen Movies","uploaderAvatar":""[truncated 1777 chars]; line: 1, column: 188] (through reference chain: com.github.libretube.obj.BackupFile["localPlaylists"]->java.util.ArrayList[0]->com.github.libretube.db.obj.LocalPlaylistWithVideos["videos"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:5)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:5)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:74)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:90)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:773)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:6)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:27)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:31)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:3)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:27)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:31)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:3)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:171)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:86)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:15)
	at com.github.libretube.ui.fragments.LibraryFragment$$ExternalSyntheticLambda0.onActivityResult(R8$$SyntheticClass:96)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:66)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:18)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:329)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:51)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:10)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:57)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:69)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:58)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:34)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:58)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8018)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	... 3 more

**Comment by Bnyro** [comment]
Sorry, my bad, fixed now!

**Comment by tampos4** [comment]
😑🙂

**Comment by Bnyro** [comment]
I'd recommend you to test it before the release using the debug builds next time, that would have helped getting rid of the issue earlier :)

**Comment by tampos4** [comment]
Yes, I forgot, completely my fault, I should have done that.

Anyways, tested it, this (app backup) issue is fixed now.

But Playlists Export > Import does not work (Settings > Backup & restore > Playlists > Export/Import Playlists).

On importing the Exported playlists, it makes the playlists' folders but doesn't backup the videos in it.

Got these 4 responses (in order) on importing the exported playlists.

![1](https://user-images.githubusercontent.com/103326242/210875174-6269f82b-3175-4e78-9495-b850d62ee4d1.jpg)
![2](https://user-images.githubusercontent.com/103326242/210875216-e9b13e3d-e401-4375-b985-1f0483f887eb.jpg)
![3](https://user-images.githubusercontent.com/103326242/210875237-5e6690df-6719-46a7-84b4-9741f8ae82b4.jpg)
![4](https://user-images.githubusercontent.com/103326242/210875248-b7b28541-e531-4042-85d3-f49cf8718273.jpg)

Changing the instance does not solve it.

**Comment by Bnyro** [comment]
Damn, please create a new issue for that! (You can just copy and paste what your wrote previously)

**Comment by tampos4** [comment]
https://github.com/libre-tube/LibreTube/issues/2608
