### ISSUE TITLE
Error during Android 5.1  Update.

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#2514]
### Steps to reproduce

1.Check out the new version.
2.There is a new version.
3.Download it.(An error occurs)

### Expected behavior

The update should have downloaded without issue.

### Actual behavior

java.lang.RuntimeException: Unable to start service com.github.libretube.services.UpdateService@25392fa7 with Intent { cmp=com.github.libretube/.services.UpdateService (has extras) }: java.lang.SecurityException: need WRITE_EXTERNAL_STORAGE permission to use DESTINATION_FILE_URI: uid 10172 does not have android.permission.WRITE_EXTERNAL_STORAGE.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2951)
	at android.app.ActivityThread.access$2100(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5351)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Caused by: java.lang.SecurityException: need WRITE_EXTERNAL_STORAGE permission to use DESTINATION_FILE_URI: uid 10172 does not have android.permission.WRITE_EXTERNAL_STORAGE.
	at android.os.Parcel.readException(Parcel.java:1546)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:239)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:180)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:502)
	at android.content.ContentResolver.insert(ContentResolver.java:1207)
	at android.app.DownloadManager.enqueue(DownloadManager.java:957)
	at com.github.libretube.services.UpdateService.onStartCommand(UpdateService.kt:145)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2934)
	... 9 more

### LibreTube version

0.9.0

### Android version

Android 5.1

### Other details

This error has existed for a long time, I reported it because it was not solved.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not relevant anymore since the updater got removed.
