### ISSUE TITLE
Failure to Import App Backup

### ISSUE THREAD

**Issue by KaiserCalm** [libre-tube/LibreTube#2662]
### Steps to reproduce

1. I did an app backup with all export options checked
2. Reistalled the app
3. Tried to restore the backup
4. Experienced error below

### Expected behavior

The app restore would work.

### Actual behavior

I get an error, with this log attached:
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=739364671, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/... flg=0x1 }} to activity {com.github.libretube/com.github.libretube.ui.activities.SettingsActivity}: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.github.libretube.db.obj.LocalPlaylistItem` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (StringReader); line: 1, column: 198] (through reference chain: com.github.libretube.obj.BackupFile["localPlaylists"]->java.util.ArrayList[0]->com.github.libretube.db.obj.LocalPlaylistWithVideos["videos"]->java.util.ArrayList[0])
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5323)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5362)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.github.libretube.db.obj.LocalPlaylistItem` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (StringReader); line: 1, column: 198] (through reference chain: com.github.libretube.obj.BackupFile["localPlaylists"]->java.util.ArrayList[0]->com.github.libretube.db.obj.LocalPlaylistWithVideos["videos"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:5)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:5)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:74)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:90)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:773)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:6)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:27)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:31)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:3)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:27)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:31)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:3)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:171)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:86)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:15)
	at com.github.libretube.ui.fragments.LibraryFragment$$ExternalSyntheticLambda0.onActivityResult(R8$$SyntheticClass:96)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:45)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:3)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:6)
	at android.app.Activity.dispatchActivityResult(Activity.java:8628)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5316)
	... 15 more
    
```

### LibreTube version

0.10.0

### Android version

Android 13, DivestOS 20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Resolved in debug builds.
