### ISSUE TITLE
[Crash] Instance Settings not attached to a context

### ISSUE THREAD

**Issue by Ilhamiii** [libre-tube/LibreTube#2751]
### Steps to reproduce

1.Go to settings.
2.Go to the instance section.
4.Go back.
5.Go to Appearance section.
6.Go back
7.Go to general settings.
8.Go back
9.Go to the instance section.
10.Go back
11.Error

### Expected behavior

The application should work without errors.

### Actual behavior

java.lang.IllegalStateException: Fragment InstanceSettings{e9fa1ba} (c25f621f-beaa-4d9c-b04e-288366850a07) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:1031)
	at com.github.libretube.ui.preferences.InstanceSettings$initCustomInstances$1.invokeSuspend(InstanceSettings.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:183)
	at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:190)
	at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1475)
	at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1471)
	at kotlinx.coroutines.JobSupport.invokeOnCompletion(JobSupport.kt:22)
	at kotlinx.coroutines.Job$DefaultImpls.invokeOnCompletion$default(Job.kt:341)
	at kotlinx.coroutines.CancellableContinuationImpl.installParentHandle(CancellableContinuationImpl.kt:308)
	at kotlinx.coroutines.CancellableContinuationImpl.getResult(CancellableContinuationImpl.kt:271)
	at retrofit2.KotlinExtensions.await(KotlinExtensions.kt:127)
	at retrofit2.HttpServiceMethod$SuspendForBody.adapt(HttpServiceMethod.java:231)
	at retrofit2.HttpServiceMethod.invoke(HttpServiceMethod.java:146)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy7.getInstances(Unknown Source)
	at com.github.libretube.ui.preferences.InstanceSettings$initCustomInstances$1.invokeSuspend(InstanceSettings.kt:129)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:219)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:75)
	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:112)
	at androidx.lifecycle.DispatchQueue.dispatchAndEnqueue$lambda-2$lambda-1(DispatchQueue.kt:100)
	at androidx.lifecycle.DispatchQueue.$r8$lambda$G2ay370n_s_ksSHUJaD9zIU8eCw(DispatchQueue.kt:0)
	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@896ec77, Dispatchers.Main.immediate]
    

### LibreTube version

0.10.0 Debug

### Android version

Android 13

### Other details

This error does not always occur.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please provide a video, the steps to reproduce are neither detailed nor reproducable.
