### ISSUE TITLE
App crash when clicking any video ( Error: Device doesn't support pip)

### ISSUE THREAD

**Issue by SuhasDissa** [libre-tube/LibreTube#2771]
### Steps to reproduce

1. Open app and search for a video
2. Click video

### Expected behavior

Play video

### Actual behavior

App crash right after clicking a video

### LibreTube version

0.10.0

### Android version

Android 12 ( Custom ROM from  https://github.com/phhusson/treble_experimentations) 

#### Error log 

```
java.lang.IllegalStateException: setPictureInPictureParams: Device doesn't support picture-in-picture mode.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2434)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.app.IActivityClientController$Stub$Proxy.setPictureInPictureParams(IActivityClientController.java:1983)
	at android.app.ActivityClient.setPictureInPictureParams(ActivityClient.java:320)
	at android.app.Activity.setPictureInPictureParams(Activity.java:2934)
	at com.github.libretube.ui.fragments.PlayerFragment.onViewCreated(PlayerFragment.kt:418)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:256)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:146)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1046)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:82)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:32)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:10)
	at androidx.core.util.DebugUtils.navigateVideo$default(DebugUtils.java:102)
	at com.github.libretube.ui.adapters.SearchAdapter$$ExternalSyntheticLambda2.onClick(R8$$SyntheticClass:33)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityClientController.ensureValidPictureInPictureActivityParams(ActivityClientController.java:778)
	at com.android.server.wm.ActivityClientController.setPictureInPictureParams(ActivityClientController.java:737)
	at android.app.IActivityClientController$Stub.onTransact(IActivityClientController.java:912)
	at com.android.server.wm.ActivityClientController.onTransact(ActivityClientController.java:121)
	at android.os.Binder.execTransactInternal(Binder.java:1179)

```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
I tried disabling picture-in-picture mode in Libre Tube app settings.
Now I can play videos without any errors.
But when I pause the video, the app crashes right away.

**Comment by xIUPITERx** [comment]
Do other apps on your device support PiP?

**Comment by Bnyro** [comment]
That's not an issue of LibreTube, it's an issue of your ROM that it doesn't support PiP properly. Since Android 8, PiP is supported by Android for all devices.

We don't aim to provide extra for support weird, edgy custom ROMs, that don't even support AOSP features.
