### ISSUE TITLE
Error playing latest videos.

### ISSUE THREAD

**Issue by Ilhamiii** [libre-tube/LibreTube#2808]
### Steps to reproduce

1.Enter the channel.
2.Go to the Channels section.
3.Play the latest videos of any channel.
4.Error

### Expected behavior

The button should work without error.

### Actual behavior

kotlinx.serialization.MissingFieldException: Fields [id, name, avatarUrl, bannerUrl, description] are required for type with serial name 'com.github.libretube.api.obj.Channel', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(StreamingJsonDecoder.kt:107)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:25)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:52)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:12)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:57)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:5)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e5c0d8f, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [id, name, avatarUrl, bannerUrl, description] are required for type with serial name 'com.github.libretube.api.obj.Channel', but they were missing
	at com.google.common.math.MathPreconditions.throwMissingFieldException(MathPreconditions.java:115)
	at com.github.libretube.api.obj.Channel.<init>(Channel.kt:74)
	at com.github.libretube.api.obj.Channel$$serializer.deserialize(Channel.kt:176)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(StreamingJsonDecoder.kt:67)
	... 10 more
    

### LibreTube version

0.11.0

### Android version

Android  13

### Other details

https://user-images.githubusercontent.com/121803062/213886490-8e79e3b6-f677-46cb-878f-0380797c7559.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#2813
