### ISSUE TITLE
Crashing when choosing an subscription 

### ISSUE THREAD

**Issue by amadoumx** [libre-tube/LibreTube#2810]
1. Going to "subscription"
2. When choosing **certain** subscriptions app is crashing and I get this report:

kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 250: Expected string literal but 'null' literal was found at path: $.bannerUrl
Use 'coerceInputValues = true' in 'Json {}` builder to coerce nulls to default values.
JSON input: .....eusercontent.com","bannerUrl":null,"description":"An analysi.....
	at kotlinx.coroutines.SupervisorKt.JsonDecodingException(Supervisor.kt:1)
	at kotlinx.coroutines.SupervisorKt.JsonDecodingException(Supervisor.kt:2)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:64)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:34)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:7)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeKeyString(StringJsonLexer.kt:3)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeString(AbstractJsonLexer.kt:3)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:14)
	at org.chromium.net.UploadDataSink.decodeStringElement(UploadDataSink.java:6)
	at com.github.libretube.api.obj.Channel$$serializer.deserialize(Channel.kt:119)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(StreamingJsonDecoder.kt:67)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:25)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:52)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:12)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:57)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:5)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a0430f, Dispatchers.Main.immediate]

**Comment by xIUPITERx** [comment]
Please use the issue template.

**Comment by Bnyro** [comment]
#2813
