### ISSUE TITLE
Crashing when browsing channel

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#2813]
### Steps to reproduce

Hi guys,

The latest version is crashing when browsing any yt channels videos.

Here is the log:

kotlinx.serialization.MissingFieldException: Fields [id, name, avatarUrl, bannerUrl, description] are required for type with serial name 'com.github.libretube.api.obj.Channel', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(StreamingJsonDecoder.kt:107)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:25)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:52)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:12)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:57)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:5)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@777e2c, Dispatchers.Main.immediate]
Caused by: kotlinx.serialization.MissingFieldException: Fields [id, name, avatarUrl, bannerUrl, description] are required for type with serial name 'com.github.libretube.api.obj.Channel', but they were missing
	at com.google.common.math.MathPreconditions.throwMissingFieldException(MathPreconditions.java:115)
	at com.github.libretube.api.obj.Channel.<init>(Channel.kt:74)
	at com.github.libretube.api.obj.Channel$$serializer.deserialize(Channel.kt:176)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(StreamingJsonDecoder.kt:67)
	... 10 more
    

### Expected behavior

Should not crash

### Actual behavior

Crashing

### LibreTube version

0.11.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RickyM7** [comment]
I'm having a similar bug where I try to access a specific channel and the app crashes. It's quite strange, because I can watch the channel's videos normally.

Crash Log:
``
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 218: Expected string literal but 'null' literal was found at path: $.bannerUrl
Use 'coerceInputValues = true' in 'Json {}` builder to coerce nulls to default values.
JSON input: .....eusercontent.com","bannerUrl":null,"description":"o melhor d.....
	at kotlinx.coroutines.SupervisorKt.JsonDecodingException(Supervisor.kt:1)
	at kotlinx.coroutines.SupervisorKt.JsonDecodingException(Supervisor.kt:2)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:64)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:34)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:7)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeKeyString(StringJsonLexer.kt:3)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeString(AbstractJsonLexer.kt:3)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:14)
	at org.chromium.net.UploadDataSink.decodeStringElement(UploadDataSink.java:6)
	at com.github.libretube.api.obj.Channel$$serializer.deserialize(Channel.kt:119)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(StreamingJsonDecoder.kt:67)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:25)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:52)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:12)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:57)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:5)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@757aec6, Dispatchers.Main.immediate]
    ``

**Comment by NotNanook** [comment]
I get the same error message as the last comment while accessing a channel with no defined banner. You can try it for yourself at the GamesWithGabe channel. 
`kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 219: Expected string literal but 'null' literal was found at path: $.bannerUrl`
