### ISSUE TITLE
PIP mode click desktop libretube icon and get error

### ISSUE THREAD

**Issue by nanedi** [libre-tube/LibreTube#2827]
### Steps to reproduce

1. Playing a video
2. PIP
3. Click desktop libretube icon
4. App crashes and get error

### Expected behavior

android.content.ActivityNotFoundException: Unable to find explicit activity class {com.github.libretube/com.github.libretube.ui.activities.MainActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2091)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1749)
	at android.app.Activity.startActivityForResult(Activity.java:5403)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5361)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at android.app.Activity.startActivity(Activity.java:5747)
	at android.app.Activity.startActivity(Activity.java:5700)
	at com.github.libretube.ui.activities.MainActivity.loadIntentData(MainActivity.kt:25)
	at com.github.libretube.ui.activities.MainActivity.onNewIntent(MainActivity.kt:7)
	at android.app.Activity.performNewIntent(Activity.java:8066)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1430)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1443)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3837)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3844)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
    

### Actual behavior

PIP mode click desktop libretube icon and get error

### LibreTube version

0.11.0

### Android version

A12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce.

**Comment by nanedi** [comment]
Oh.

Thanks
