### ISSUE TITLE
Crashed afted adding to queue 

### ISSUE THREAD

**Issue by rahaaatul** [libre-tube/LibreTube#2847]
### Steps to reproduce

• I was listening to a podcast but it was in pip mode.
• Found a YouTube video on chrome browser.
• Tried to add that video to queue by sharing it to LibreTube.
• It crashed.

```
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.github.libretube/com.github.libretube.ui.activities.MainActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2115)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1777)
	at android.app.Activity.startActivityForResult(Activity.java:5427)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5385)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at android.app.Activity.startActivity(Activity.java:5771)
	at android.app.Activity.startActivity(Activity.java:5724)
	at com.github.libretube.ui.activities.MainActivity.loadIntentData(MainActivity.kt:25)
	at com.github.libretube.ui.activities.MainActivity.onNewIntent(MainActivity.kt:7)
	at android.app.Activity.performNewIntent(Activity.java:8134)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1459)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1472)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3984)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3996)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2322)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8220)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
    
```

### Expected behavior

Should have added the video to queue.

### Actual behavior

Crashed.

### LibreTube version

0.11.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce on any of my devices, thus I believe it's probably device related.
