### ISSUE TITLE
Random crash when playing a video in Music mode

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#2897]
### Steps to reproduce

I can't reproduce it

### Expected behavior

To not crash

### Actual behavior

It crashes

### LibreTube version

0.11.1

### Android version

Android 13

### Other details

retrofit2.HttpException:` HTTP 500 
	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:133)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:9)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ac315a2, Dispatchers.IO]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I think that should have been fixed within the last update.
