### ISSUE TITLE
Download error when connection is lost.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#2974]
### Steps to reproduce

1.Download the video.
2.Turn off Wi-Fi
2.An error occurred.
3.When I resumed the download, the error occurred again.

### Expected behavior

An error should not occur.

### Actual behavior

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.github.libretube.services.DownloadService.ACTION_SERVICE_STOPPED flg=0x10 } in com.github.libretube.receivers.DownloadReceiver@56889f
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1816)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.github.libretube/com.github.libretube.ui.activities.MainActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2098)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
	at android.app.Activity.startActivityForResult(Activity.java:5473)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5431)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at android.app.Activity.startActivity(Activity.java:5817)
	at android.app.Activity.startActivity(Activity.java:5770)
	at com.github.libretube.receivers.DownloadReceiver.onReceive(DownloadReceiver.kt:64)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1806)
	... 9 more
    

### LibreTube version

0.11.1

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/124310688/216815201-abfb009a-72fe-4f06-91d4-dad034b5ef5f.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Chex07** [comment]
I have the same problem, it seems to download, but no music or files are downloaded to the phone.

**Bende de aynı problem var, download ediyormuş gibi görünüyor fakat hiç bir müzik yada dosya imniyor telefona.**

**Comment by Bnyro** [comment]
Would  you mind trying to reproduce that with the latest debug version? Thanks!

**Comment by Qaz-7** [comment]
The problem now is a little different. During the download the video cannot be paused or the audio download stops and the other continues. The download should start automatically when the connection is restored.


https://user-images.githubusercontent.com/124310688/217446746-ffbdb303-85ac-498e-8050-8279e895e289.mp4

**Comment by Bnyro** [comment]
It doesn't crash anymore so the initial issue got fixed. Automatic resuming would be another feature request, but there currently aren't any plans for it.
