### ISSUE TITLE
Crash on Opening app while listening to audio

### ISSUE THREAD

**Issue by Sir-Photch** [libre-tube/LibreTube#3007]
### Steps to reproduce

1. Start a video.
2. Select audio Playback
3. Return to home screen
4. (Lock phone, unlock phone)
5. Open Libretube again

### Expected behavior

The app opens.

### Actual behavior

The app & audio playback crashes

### LibreTube version

0.11.1

### Android version

13

### Other details

```
kotlin.UninitializedPropertyAccessException: lateinit property binding has not been initialized
	at com.github.libretube.ui.fragments.AudioPlayerFragment$connection$1.onServiceConnected(AudioPlayerFragment.kt:51)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2188)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2221)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
    
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please provide valid version numbers, latest could refer to stable as well as debug builds and thus is not self-explaining, also not for future readers once newer versions got released.

**Comment by Sir-Photch** [comment]
I've added the version number.

**Comment by Bnyro** [comment]
Since there are no updates I assume this was fixed (I remember doing changes to the view binding logic there.)
