### ISSUE TITLE
App crashes when player is closed.

### ISSUE THREAD

**Issue by faisalcodes** [libre-tube/LibreTube#3067]
### Steps to reproduce

The new ViewBindingPropertyDelegate changes have broken something. (PROBABLY)

1. Play a video
2. Close the video by click on cross button.

### Expected behavior

Should close the player.

### Actual behavior

Crashes.

### LibreTube version

0.12.0

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/62804272/218564104-25b39484-2c7c-4118-81a8-d4a6f6e28d22.mp4

```
java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
	at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:87)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:63)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:52)
	at com.github.libretube.ui.fragments.PlayerFragment.getPlayerBinding(PlayerFragment.kt:126)
	at com.github.libretube.ui.fragments.PlayerFragment.syncQueueButtons(PlayerFragment.kt:1086)
	at com.github.libretube.ui.fragments.PlayerFragment.$r8$lambda$d66kNQWGCX0ZZMRUB3wPXYjt3xY(Unknown Source:0)
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
    
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Isira-Seneviratne** [comment]
I wasn't able to reproduce this issue on my end. Could you post a stack trace if possible?

**Comment by swarnenduu** [comment]
I don't find the issue on my phone(v0.12.0, Android 12). The cross button works fine without any app crash.

**Comment by faisalcodes** [comment]
@Isira-Seneviratne I have updated my post with the stack trace.

**Comment by xIUPITERx** [comment]
> I don't find the issue on my phone(v0.12.0, Android 12). The cross button works fine without any app crash.

I think it's only happening in the debug version.
