### ISSUE TITLE
Crash when searching URL

### ISSUE THREAD

**Issue by rzasharifi** [libre-tube/LibreTube#3076]
### Steps to reproduce

I copied an address from the YT then I paised it in the address bar of the app, then I cleared additional info and at the end i pressed enter.

### Expected behavior

Above steps should lead me to the aim channel

### Actual behavior

It crashed and the app collapsed

### LibreTube version

0.12.0

### Android version

A12

### Other details

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.SearchResultFragment$fetchSearch$1.invokeSuspend(SearchResultFragment.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:42)
	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:23)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8309)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6d1ce42, Dispatchers.Main.immediate]
    -------------------------

Honestly, beleive me or not, non the instances don't work for me so I used VPN during this process.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Can you check if this is resolved? Can't reproduce on latest version

**Comment by rzasharifi** [comment]
I updated to V. 12.1, and it's OK for me, as well.
