### ISSUE TITLE
Error installing version.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3091]
### Steps to reproduce

1.Check out the new version
2.During the update, remove LibreTube from My device recents and go to the app.
3.Error

### Expected behavior

ATTENTION!
There should be no error.Also, after downloading the update, you should see an option to install APK when you check the version.But the download option appears again.This option should appear automatically when you are in the app.

### Actual behavior

java.lang.RuntimeException: Unable to stop service com.github.libretube.services.UpdateService@4887209: java.lang.IllegalArgumentException: Receiver not registered: com.github.libretube.services.UpdateService$onDownloadComplete$1@ccd7c0e
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5142)
	at android.app.ActivityThread.access$2200(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.github.libretube.services.UpdateService$onDownloadComplete$1@ccd7c0e
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1656)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1859)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:788)
	at com.github.libretube.services.UpdateService.onDestroy(UpdateService.kt:3)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5122)
	... 9 more
    

### LibreTube version

Update from 0.11.1 to 0.12.0.

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/124310688/219174768-4584b50f-c92b-446e-a87f-08f56c9eaf38.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Qaz-7** [comment]
#2514 There is such an error.

**Comment by Bnyro** [comment]
We're planning to remove the updater anyways because it conflicts with F-Droid installations and sooner or later Accrescent.

**Comment by Bnyro** [comment]
Not relevant anymore since the updater got removed.
