### ISSUE TITLE
smth not right happens when the video is blocked

### ISSUE THREAD

**Issue by Gerodote** [libre-tube/LibreTube#3103]
### Steps to reproduce

1. Find a video which is blocked i.e. https://m.youtube.com/watch?v=3J1CYzzZjNc&list=PLbpyZ2bHGDX0sP6mvkIhtKSg1cfdtMF8d&index=110

2. See that libretube tells that there's a problem on server side
3. Try to press button share.
4. Get crash
5. check the log
6. check the video using browser
7. see that the video is blocked because of copyright smth
8. ???
9. get depressed because you cannot watch this ;(

### Expected behavior

1. shows that video is blocked and why
2. if it's blocked, at least button share should work and counter of likes, dislikes and views.

### Actual behavior

kotlin.UninitializedPropertyAccessException: lateinit property streams has not been initialized
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda19.onLongClick(R8$$SyntheticClass:114)
	at android.view.View.performLongClickInternal(View.java:7961)
	at android.view.View.performLongClick(View.java:7919)
	at android.widget.TextView.performLongClick(TextView.java:14046)
	at android.view.View.performLongClick(View.java:7937)
	at android.view.View$CheckForLongPress.run(View.java:30821)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
    

### LibreTube version

0.11.1

### Android version

Android 13 Samsung

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not an issue in the most recent version.
