### ISSUE TITLE
The app keeps crashing randomly on reopening

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#3245]
### Steps to reproduce

It keeps crashing randomly when opening the app. 

java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
	at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:131)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:2)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue$1(FragmentViewBindings.kt:3)
	at com.github.libretube.ui.fragments.SearchResultFragment.getBinding(SearchResultFragment.kt:8)
	at com.github.libretube.ui.fragments.SearchResultFragment$fetchSearch$1.invokeSuspend(SearchResultFragment.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:42)
	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:23)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8a80e3d, Dispatchers.Main.immediate]
    

### Expected behavior

Should not crash

### Actual behavior

Crashes

### LibreTube version

0.12.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by nanedi** [comment]
I have a very similar problem.

```
java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
 at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:131)
 at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:2)
 at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue$1(FragmentViewBindings.kt:3)
 at com.github.libretube.ui.fragments.PlayerFragment.getBinding(PlayerFragment.kt:8)
 at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:15)
 at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda20.run(R8$$SyntheticClass:13)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:346)
 at android.os.Looper.loop(Looper.java:475)
 at android.app.ActivityThread.main(ActivityThread.java:7950)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

**Comment by muznyo** [comment]
same here

java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
	at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:131)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:2)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue$1(FragmentViewBindings.kt:3)
	at com.github.libretube.ui.fragments.SearchResultFragment.getBinding(SearchResultFragment.kt:8)
	at com.github.libretube.ui.fragments.SearchResultFragment$fetchSearch$1.invokeSuspend(SearchResultFragment.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:42)
	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:23)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@88f9e55, Dispatchers.Main.immediate]

**Comment by xIUPITERx** [comment]
Not just on reopening, also when the app is in the background without playing something for some time.

**Comment by WreckingBANG** [comment]
And when you close a minimized Video with the X-Button

**Comment by noClaps** [comment]
Having the same problem

<details><summary>Crash report</summary>
<p>

```
java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
	at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:131)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:2)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue$1(FragmentViewBindings.kt:3)
	at com.github.libretube.ui.fragments.PlayerFragment.getBinding(PlayerFragment.kt:8)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:15)
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda20.run(R8$$SyntheticClass:13)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

</p>
</details>

**Comment by gbieging** [comment]
Similar problem

<details><summary>Crash Report</summary>

```
java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
	at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:131)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:2)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue$1(FragmentViewBindings.kt:3)
	at com.github.libretube.ui.fragments.SearchResultFragment.getBinding(SearchResultFragment.kt:8)
	at com.github.libretube.ui.fragments.SearchResultFragment$fetchSearch$1.invokeSuspend(SearchResultFragment.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:42)
	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:23)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f321c6a, Dispatchers.Main.immediate]
```

</details>
