### ISSUE TITLE
Shuffle button error (Empty playlist)

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3248]
### Steps to reproduce

1.Keep your playlist empty.
2.Press the shuffle button.
3.Error

### Expected behavior

Without error

### Actual behavior

java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:8)
	at com.github.libretube.ui.fragments.PlaylistFragment$fetchPlaylist$1$$ExternalSyntheticLambda2.onClick(R8$$SyntheticClass:48)
	at android.view.View.performClick(View.java:7792)
	at android.widget.TextView.performClick(TextView.java:16112)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:10)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    

### LibreTube version

0.12.1

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/124310688/222974465-5b3bb156-3d95-4c96-a6ae-32c00cf5784c.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by nayeemdv** [comment]
Hey i have gone through this issue and as i can understand just a simple check is needed for empty playlist can i create a PR for this???
