### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Baker0o7** [libre-tube/LibreTube#3272]
java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
	at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:131)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:2)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue$1(FragmentViewBindings.kt:3)
	at com.github.libretube.ui.fragments.PlayerFragment.getBinding(PlayerFragment.kt:8)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:15)
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda20.run(R8$$SyntheticClass:13)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7835)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by akano12** [comment]
Follow issue template + same error in https://github.com/libre-tube/LibreTube/issues/3245

**Comment by xIUPITERx** [comment]
Please use the template.
