### ISSUE TITLE
Division by zero when opening video

### ISSUE THREAD

**Issue by x-0D** [libre-tube/LibreTube#3298]
### Steps to reproduce

Install libretube.
Open any video.
Get crash.

### Expected behavior

...

### Actual behavior

App crashes when i trying to open video.

### LibreTube version

0.12.1

### Android version

Android 13

### Other details

```java.lang.ArithmeticException: divide by zero
	at com.github.libretube.extensions.NormalizeKt.normalize(Normalize.kt:6)
	at com.github.libretube.helpers.AudioHelper.getVolumeWithScale$default(AudioHelper.kt:14)
	at com.github.libretube.ui.views.CustomExoPlayerView.initialize(CustomExoPlayerView.kt:158)
	at com.github.libretube.ui.fragments.PlayerFragment$playVideo$1$3.invokeSuspend(PlayerFragment.kt:192)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@af0105b, Dispatchers.Main.immediate]
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Does disabling the swipe gestures in the player settings have any impact?
