### ISSUE TITLE
Java exception on start

### ISSUE THREAD

**Issue by juxuanu** [libre-tube/LibreTube#3316]
### Steps to reproduce

1. Open app

### Expected behavior

No dialog with errors should appear on start.

### Actual behavior

Everything seems to work fine, but I got a dialog with the following content:
```
java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
	at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:131)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:2)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue$1(FragmentViewBindings.kt:3)
	at com.github.libretube.ui.fragments.PlayerFragment.getBinding(PlayerFragment.kt:8)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:15)
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda20.run(R8$$SyntheticClass:13)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
    
```

### LibreTube version

0.12.1

### Android version

Latest GrapheneOS 

### Other details

Default tab is subscriptions feed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by wizhel** [comment]
I got the same problem

**Comment by Bnyro** [comment]
duplicate of #3245
