### ISSUE TITLE
Click the X in the upper left corner to close the video that is playing, then App crash.

### ISSUE THREAD

**Issue by nanedi** [libre-tube/LibreTube#3372]
### Steps to reproduce

Click the X in the upper left corner to close the video that is playing.

### Expected behavior

No.

### Actual behavior

Click the X in the upper left corner to close the video that is playing, then App crash.

### LibreTube version

0.13.0

### Android version

Android 13

### Other details

```
java.lang.NullPointerException
 at com.github.libretube.ui.fragments.PlayerFragment$initializeTransitionLayout$1.onTransitionChange(PlayerFragment.kt:14)
 at com.github.libretube.ui.views.SingleViewTouchableMotionLayout$2.onTransitionChange(SingleViewTouchableMotionLayout.kt:25)
 at androidx.constraintlayout.motion.widget.MotionLayout.fireTransitionChange(MotionLayout.java:73)
 at androidx.constraintlayout.motion.widget.MotionLayout.setState(MotionLayout.java:5)
 at androidx.constraintlayout.motion.widget.MotionLayout.evaluate(MotionLayout.java:276)
 at androidx.constraintlayout.motion.widget.MotionLayout.dispatchDraw(MotionLayout.java:6)
 at android.view.View.updateDisplayListIfDirty(View.java:22067)
 at android.view.View.draw(View.java:22940)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
 at android.view.View.draw(View.java:23212)
 at android.view.View.updateDisplayListIfDirty(View.java:22076)
 at android.view.View.draw(View.java:22940)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
 at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:29)
 at androidx.constraintlayout.motion.widget.MotionLayout.dispatchDraw(MotionLayout.java:63)
 at android.view.View.updateDisplayListIfDirty(View.java:22067)
 at android.view.View.draw(View.java:22940)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
 at android.view.View.updateDisplayListIfDirty(View.java:22067)
 at android.view.View.draw(View.java:22940)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
 at android.view.View.updateDisplayListIfDirty(View.java:22067)
 at android.view.View.draw(View.java:22940)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
 at android.view.View.updateDisplayListIfDirty(View.java:22067)
 at android.view.View.draw(View.java:22940)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
 at android.view.View.updateDisplayListIfDirty(View.java:22067)
 at android.view.View.draw(View.java:22940)
 at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
 at android.view.View.draw(View.java:23212)
 at com.android.internal.policy.DecorView.draw(DecorView.java:836)
 at android.view.View.updateDisplayListIfDirty(View.java:22076)
 at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
 at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
 at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786)
 at android.view.ViewRootImpl.draw(ViewRootImpl.java:4582)
 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4293)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3520)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2289)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8958)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327)
 at android.view.Choreographer.doCallbacks(Choreographer.java:985)
 at android.view.Choreographer.doFrame(Choreographer.java:916)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:346)
 at android.os.Looper.loop(Looper.java:475)
 at android.app.ActivityThread.main(ActivityThread.java:7950)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by nanedi** [comment]
Add more

```
java.lang.NullPointerException
 at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:17)
 at androidx.room.MultiInstanceInvalidationClient$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:91)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:346)
 at android.os.Looper.loop(Looper.java:475)
 at android.app.ActivityThread.main(ActivityThread.java:7950)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

**Comment by nanedi** [comment]
I have tried Google pixel 4 and 6, Sony 1 III, 1 IV.
Android 13

They all have the same problem.

**Comment by Malgotra** [comment]
Redmi Note 10 MIUI 14 Android 12. Same crash.
java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment$initializeTransitionLayout$1.onTransitionChange(PlayerFragment.kt:14)
	at com.github.libretube.ui.views.SingleViewTouchableMotionLayout$2.onTransitionChange(SingleViewTouchableMotionLayout.kt:25)
	at androidx.constraintlayout.motion.widget.MotionLayout.fireTransitionChange(MotionLayout.java:73)
	at androidx.constraintlayout.motion.widget.MotionLayout.setState(MotionLayout.java:5)
	at androidx.constraintlayout.motion.widget.MotionLayout.evaluate(MotionLayout.java:276)
	at androidx.constraintlayout.motion.widget.MotionLayout.dispatchDraw(MotionLayout.java:6)
	at android.view.View.updateDisplayListIfDirty(View.java:21875)
	at android.view.View.draw(View.java:22742)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23020)
	at android.view.View.updateDisplayListIfDirty(View.java:21884)
	at android.view.View.draw(View.java:22742)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:29)
	at androidx.constraintlayout.motion.widget.MotionLayout.dispatchDraw(MotionLayout.java:63)
	at android.view.View.updateDisplayListIfDirty(View.java:21875)
	at android.view.View.draw(View.java:22742)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21875)
	at android.view.View.draw(View.java:22742)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21875)
	at android.view.View.draw(View.java:22742)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21875)
	at android.view.View.draw(View.java:22742)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21875)
	at android.view.View.draw(View.java:22742)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23020)
	at com.android.internal.policy.DecorView.draw(DecorView.java:887)
	at android.view.View.updateDisplayListIfDirty(View.java:21884)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4643)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4361)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3472)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2263)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8990)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1144)
	at android.view.Choreographer.doCallbacks(Choreographer.java:948)
	at android.view.Choreographer.doFrame(Choreographer.java:877)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1129)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8302)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)

**Comment by akano12** [comment]
This happens when dismissing the video while in full screen

**Comment by akano12** [comment]
This  only happens when dismissing a video while in fullscreen,
you haven't mentioned this in your issue and i guess that's why Bnyro couldn't reproduce

**Comment by beaglesnuf** [comment]
Can repro on P6 and P7 GOS (A13)...

``
java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment$initializeTransitionLayout$1.onTransitionChange(PlayerFragment.kt:14)
	at com.github.libretube.ui.views.SingleViewTouchableMotionLayout$2.onTransitionChange(SingleViewTouchableMotionLayout.kt:25)
	at androidx.constraintlayout.motion.widget.MotionLayout.fireTransitionChange(MotionLayout.java:73)
	at androidx.constraintlayout.motion.widget.MotionLayout.setState(MotionLayout.java:5)
	at androidx.constraintlayout.motion.widget.MotionLayout.evaluate(MotionLayout.java:276)
	at androidx.constraintlayout.motion.widget.MotionLayout.onLayout(MotionLayout.java:28)
	at android.view.View.layout(View.java:23716)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23716)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at androidx.constraintlayout.motion.widget.MotionController.interpolate(MotionController.java:630)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:363)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:160)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:760)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4017)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3355)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2346)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
``

**Comment by farline99** [comment]
Thank you for fixing this. It was annoying. You are awesome developer! ❤️
