### ISSUE TITLE
Source error while switching Video to audio

### ISSUE THREAD

**Issue by nayeemdv** [libre-tube/LibreTube#3394]
### Steps to reproduce

1. open a video 
2. Click in Audio
3. wait for 5 to 6 seconds

### Expected behavior

Audio Should play!!

### Actual behavior

Audio Doesn't play also a Toast appears (Source Error)

https://user-images.githubusercontent.com/91174350/227754478-cd756f62-7709-4c81-9549-adae0cee6f41.mp4

### LibreTube version

0.13.0

### Android version

Android 11

### Other details

I think it doesnt get response from url... First five Lines gets repeated until error shows up

I/System.out: [okhttp]:check permission begin!
I/System.out: [okhttp]:not MMS!
I/System.out: [okhttp]:not Email!
I/System.out: [OkHttp] sendRequest>>
I/System.out: [OkHttp] sendRequest<<
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:413)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by thangisme** [comment]
I'm facing the same bug

**Comment by itsmmt305** [comment]
me too

**Comment by Bnyro** [comment]
Looks like a proxy issue or an invalid source from YouTube, did you try changing the audio quality in the settings to "worst"?

**Comment by Flashwalker** [comment]
I have the same.
Also with some instances the video and audio playing lasts only a few first seconds and hanging.

**Comment by Flashwalker** [comment]
> Looks like a proxy issue or an invalid source from YouTube, did you try changing the audio quality in the settings to "worst"?

In my case i tried to toggle the piped proxy in settins to get direct youtube stream. It doesn't helps, still `source error`.

**Comment by Flashwalker** [comment]
Also for those instances when you able to play first few seconds of audio stream, if you tap Next/Prev arrow buttons - the track is switched but not the video thumb image or title. It stays from the starting track

**Comment by LordPax** [comment]
I have the same error

**Comment by Bnyro** [comment]
Fixed in #3878

**Comment by itsmmt305** [comment]
> Fixed in #3878

yayyy

**Comment by Flashwalker** [comment]
0.15 still affected

**Comment by LordPax** [comment]
> 0.15 still affected

it's normal, this fix as been merge after 0.15, we are waiting for 0.15.1
