### ISSUE TITLE
Errors when cloning a long playlist

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3395]
### Steps to reproduce

1.Clone a long playlist.
2.Click the background playback button repeatedly
3.Error
Attention!
You do these actions quickly.

### Expected behavior

There should be no error.

### Actual behavior

A)   java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.github.libretube.util.PlayingQueue.contains(PlayingQueue.kt:202)
	at com.github.libretube.util.PlayingQueue.updateCurrent(PlayingQueue.kt:69)
	at com.github.libretube.services.BackgroundMode$loadAudio$1.invokeSuspend(BackgroundMode.kt:188)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ca1f7b5, Dispatchers.IO]
    
B) java.lang.ArrayIndexOutOfBoundsException: src.length=2776 srcPos=2774 dst.length=2776 dstPos=2773 length=3
	at java.lang.System.arraycopy(Native Method)
	at java.util.ArrayList.fastRemove(ArrayList.java:555)
	at java.util.ArrayList.remove(ArrayList.java:540)
	at com.github.libretube.util.PlayingQueue.add(PlayingQueue.kt:35)
	at com.github.libretube.util.PlayingQueue$fetchMoreFromPlaylist$1.invokeSuspend(PlayingQueue.kt:106)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@529a4af, Dispatchers.IO]
    

### LibreTube version

0.13.0 Debug

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/124310688/227762715-3cd2711a-5d3c-4e4a-959a-a1e1cf3e051d.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Well, it's self-explaining that your device can't handle so many actions at a time.
