### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by razzat008** [libre-tube/LibreTube#3407]
### Steps to reproduce

1.Click on any video.
2.Close the video by pressing (cross) button on top left side.

### Expected behavior

The video should stop playing and we should be able to surf the recommendation.

### Actual behavior

App crashes when the close player button is pressed.

### LibreTube version

0.13.0

### Android version

Android 13

### Other details

This error window gets prompted after reopening the app after it crashes:

`java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment$initializeTransitionLayout$1.onTransitionChange(PlayerFragment.kt:14)
	at com.github.libretube.ui.views.SingleViewTouchableMotionLayout$2.onTransitionChange(SingleViewTouchableMotionLayout.kt:25)
	at androidx.constraintlayout.motion.widget.MotionLayout.fireTransitionChange(MotionLayout.java:73)
	at androidx.constraintlayout.motion.widget.MotionLayout.setState(MotionLayout.java:5)
	at androidx.constraintlayout.motion.widget.MotionLayout.evaluate(MotionLayout.java:276)
	at androidx.constraintlayout.motion.widget.MotionLayout.dispatchDraw(MotionLayout.java:6)
	at android.view.View.updateDisplayListIfDirty(View.java:22059)
	at android.view.View.draw(View.java:22932)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23204)
	at android.view.View.updateDisplayListIfDirty(View.java:22068)
	at android.view.View.draw(View.java:22932)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:29)
	at androidx.constraintlayout.motion.widget.MotionLayout.dispatchDraw(MotionLayout.java:63)
	at android.view.View.updateDisplayListIfDirty(View.java:22059)
	at android.view.View.draw(View.java:22932)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22059)
	at android.view.View.draw(View.java:22932)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22059)
	at android.view.View.draw(View.java:22932)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22059)
	at android.view.View.draw(View.java:22932)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22059)
	at android.view.View.draw(View.java:22932)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23204)
	at com.android.internal.policy.DecorView.draw(DecorView.java:821)
	at android.view.View.updateDisplayListIfDirty(View.java:22068)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4668)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4379)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3598)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2326)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9092)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:853)
    `

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Can't reproduce on 0.13.1.

**Comment by Bnyro** [comment]
Yes, please update to the latest version.
