### ISSUE TITLE
Crash if you try to make the video fullscreen before it "initialises"

### ISSUE THREAD

**Issue by xrtxn** [libre-tube/LibreTube#3409]
### Steps to reproduce

Open a video
Quickly swipe up to try to make the video fullscreen before it loads
Crash

### Expected behavior

I suppose the fullscreen should start and show a black screen.

### Actual behavior

It crashes

### LibreTube version

0.13.1 but it was the same in earlier versions

### Android version

android 13

### Other details

Crash log:
kotlin.UninitializedPropertyAccessException: lateinit property streams has not been initialized
	at com.github.libretube.ui.fragments.PlayerFragment.setFullscreen(PlayerFragment.kt:184)
	at com.github.libretube.ui.fragments.PlayerFragment$initializeTransitionLayout$2.invoke(PlayerFragment.kt:13)
	at com.github.libretube.ui.views.SingleViewTouchableMotionLayout$Listener.onScroll(SingleViewTouchableMotionLayout.kt:54)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:708)
	at com.github.libretube.ui.views.SingleViewTouchableMotionLayout.onTouchEvent(SingleViewTouchableMotionLayout.kt:8)
	at android.view.View.dispatchTouchEvent(View.java:15010)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3115)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1906)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4263)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:3)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
	at android.view.View.dispatchPointerEvent(View.java:15269)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6659)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6459)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5910)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6098)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6155)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9001)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8952)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8921)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9124)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:247)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9081)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9215)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:824)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by nayeemdv** [comment]
I think for this issue is to add a check whether the stream is initialized or not. works fine!!
