### ISSUE TITLE
Application login error when pip is running.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3428]
### Steps to reproduce

1.Press the pip button on the player.
2.Automatically logged out of the app.
3.Error when entering the application

### Expected behavior

Do not exit the application and do not have an error when entering.

### Actual behavior

android.content.ActivityNotFoundException: Unable to find explicit activity class {com.github.libretube.debug/com.github.libretube.ui.activities.MainActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2098)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
	at android.app.Activity.startActivityForResult(Activity.java:5473)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:728)
	at android.app.Activity.startActivityForResult(Activity.java:5431)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:709)
	at android.app.Activity.startActivity(Activity.java:5817)
	at android.app.Activity.startActivity(Activity.java:5770)
	at com.github.libretube.ui.activities.MainActivity.loadIntentData(MainActivity.kt:379)
	at com.github.libretube.ui.activities.MainActivity.onNewIntent(MainActivity.kt:501)
	at android.app.Activity.performNewIntent(Activity.java:8306)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1429)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1442)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4241)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4248)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    

### LibreTube version

0.13.1 The latest Debug

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/124310688/228138103-c6718da0-59c5-4659-90c1-6ba6e48c2fad.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce, looks like a device specific issue.

**Comment by Bnyro** [comment]
Seems to be a device issue.

**Comment by Qaz-7** [comment]
I could help.
