### ISSUE TITLE
Error cloning long playlist without account

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3429]
### Steps to reproduce

1.Clone a long playlist.
2.Enter the playlist
3.Click the "Play All" button.
4.Double click to close the mini player.
5.Error

### Expected behavior

There should be no error

### Actual behavior

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment.getBinding(PlayerFragment.kt:126)
	at com.github.libretube.ui.fragments.PlayerFragment.killPlayerFragment(PlayerFragment.kt:1547)
	at com.github.libretube.ui.fragments.PlayerFragment.initializeOnClickActions$lambda$1(PlayerFragment.kt:361)
	at com.github.libretube.ui.fragments.PlayerFragment.$r8$lambda$hp5aoFq1o-ltpmx829WbzpePC68(Unknown Source:0)
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda4.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7792)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    

### LibreTube version

0.13.1 The latest Debug

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/124310688/228161745-64bd6b01-35b9-4ca0-a53b-3c1d85e6c503.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Qaz-7** [comment]
I used it without an account.
