### ISSUE TITLE
Channel playback queue error.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3430]
### Steps to reproduce

1.Go to the Channels section.
2.Play any channel in the background.
3.Then click the "play latest videos" button.
4.An error has occurred and queue buttons are not being closed.

### Expected behavior

When the video  player opens, the audio player should be completely closed

### Actual behavior

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.github.libretube.util.PlayingQueue.currentIndex(PlayingQueue.kt:195)
	at com.github.libretube.util.PlayingQueue.hasPrev(PlayingQueue.kt:55)
	at com.github.libretube.ui.fragments.PlayerFragment.syncQueueButtons(PlayerFragment.kt:1137)
	at com.github.libretube.ui.fragments.PlayerFragment.$r8$lambda$d66kNQWGCX0ZZMRUB3wPXYjt3xY(Unknown Source:0)
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    

### LibreTube version

0.13.1 The latest Debug

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/124310688/228168141-ab8c06ba-dd29-426f-adf8-cdfe9de8b8a4.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Qaz-7** [comment]
It can be reproduce
