### ISSUE TITLE
CRASH WHEN CLICKING DOWNLOAD OPTION IN THE SETTINGS

### ISSUE THREAD

**Issue by socynx** [libre-tube/LibreTube#3451]
Steps to reproduce

1- Press the settings button
2 - Press the downloads option
3 - The app immediately closes

Expected behavior

Do not exit the application and do not have an error when clicking download option

Actual behavior:

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	... 1 more
Caused by: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.github.libretube/files/audio/Legião Urbana - Vento no litoral_126_kbps_M4A.mp4
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:115)
	at j$.nio.file.spi.a.x(Unknown Source:14)
	at j$.nio.file.Files.readAttributes(SourceFile:0)
	at j$.nio.file.Files.size(Unknown Source:5)
	at com.github.libretube.ui.adapters.DownloadsAdapter.onBindViewHolder(DownloadsAdapter.kt:101)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:1157)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:59)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:825)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:79)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:64)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26380)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:547)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:253)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:31)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:102)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:186)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:460)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:440)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:34)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1433)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:509)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:90)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:160)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:760)
	at android.view.View.measure(View.java:26380)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4021)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2637)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2943)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2350)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9194)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	... 3 more

**Comment by Bnyro** [comment]
#3379
