### ISSUE TITLE
Error sign in to account

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3465]
### Steps to reproduce

1.Sign in to account
2. Error

### Expected behavior

There should be no error

### Actual behavior

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:11177)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2482)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at android.view.View.requestLayout(View.java:27053)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:9)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.triggerUpdateProcessor(RecyclerView.java:26)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:43)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:19)
	at androidx.preference.Preference.notifyChanged(Preference.java:19)
	at androidx.preference.Preference.setEnabled(Preference.java:14)
	at com.github.libretube.ui.preferences.InstanceSettings$onCreatePreferences$6$1.invoke(InstanceSettings.kt:21)
	at com.github.libretube.ui.dialogs.LoginDialog$signIn$1.invokeSuspend(LoginDialog.kt:234)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:79)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@431bf39, Dispatchers.IO]
    

### LibreTube version

0.13.1

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/124310688/229171319-4a0ef2e7-4158-4884-a851-11c2cb460458.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We've been replacing the release apks with a hotfix version some days ago, so please make a backup and reinstall the app.

**Comment by Qaz-7** [comment]
I didn't know. Thank you
