### ISSUE TITLE
Seemingly random crashes when opening after a bit of inactivity.

### ISSUE THREAD

**Issue by TwinniDev** [libre-tube/LibreTube#3485]
### Steps to reproduce

1. Open the app after it hasn't been in use for a bit.

### Expected behavior

The app opens to the home screen without crashing.

### Actual behavior

The app opens to the homescreen, immediately crashing and spitting you out to your launcher.

### LibreTube version

0.13.1

### Android version

Android 13

### Other details

java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
	at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:131)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:2)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue$1(FragmentViewBindings.kt:3)
	at com.github.libretube.ui.fragments.SearchResultFragment.getBinding(SearchResultFragment.kt:8)
	at com.github.libretube.ui.fragments.SearchResultFragment$fetchSearch$1.invokeSuspend(SearchResultFragment.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:42)
	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:33)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c3c523d, Dispatchers.Main.immediate]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That has already been fixed in #3439.
