### ISSUE TITLE
Stack trace popped up when switching to the app after several hours

### ISSUE THREAD

**Issue by RobbyCBennett** [libre-tube/LibreTube#3489]
### Steps to reproduce

I'm not sure if this is repeatable, but this is what happened.

1. Opened a video (specifically https://www.youtube.com/watch?v=vIRjSdTCIEU)
2. Expanded the miniplayer to the portrait video player
3. Decided to watch it the next day because of the length, so I paused it and didn't close the app but switched away
4. Opened the app
5. Error popped up

### Expected behavior

No error popup

### Actual behavior

Popup showed with the following exception

```
java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
	at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:131)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:2)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue$1(FragmentViewBindings.kt:3)
	at com.github.libretube.ui.fragments.SearchResultFragment.getBinding(SearchResultFragment.kt:8)
	at com.github.libretube.ui.fragments.SearchResultFragment$fetchSearch$1.invokeSuspend(SearchResultFragment.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:42)
	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:33)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@27fb9f8, Dispatchers.Main.immediate]
```

### LibreTube version

0.13.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This has been fixed in #3439 ;)
