### ISSUE TITLE
crash leaving trends

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#3526]
### Steps to reproduce

- Watch some videos at the trend tab
- switch to subscriptions tab
- app crashes

### Expected behavior

No crash

### Actual behavior

App crashes

### LibreTube version

latest Debug

### Android version

Android 13

### Other details

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.TrendsFragment.getBinding(TrendsFragment.kt:27)
	at com.github.libretube.ui.fragments.TrendsFragment.access$getBinding(TrendsFragment.kt:25)
	at com.github.libretube.ui.fragments.TrendsFragment$fetchTrending$1.invokeSuspend(TrendsFragment.kt:71)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:74)
	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:111)
	at androidx.lifecycle.DispatchQueue.dispatchAndEnqueue$lambda$2$lambda$1(DispatchQueue.kt:99)
	at androidx.lifecycle.DispatchQueue.$r8$lambda$1ME-FmJywCV2uxhp8ajM5a9C_oI(Unknown Source:0)
	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8535cb6, Dispatchers.Main.immediate]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Ah fair, I don't have the trends fragment set as a tab, thus I didn't noticed that one.
