### ISSUE TITLE
Crash - Fragment's view can't be accessed

### ISSUE THREAD

**Issue by andrealicheri** [libre-tube/LibreTube#3534]
### Steps to reproduce

1. Open Libretube
2. Watch a video
3. Close it
4. Click the home button

### Expected behavior

The app should continue **working**

### Actual behavior

The app **crashed**

### LibreTube version

0.13.0

### Android version

Android 12

### Other details

Here's the error message
`java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
	at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:131)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:2)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue$1(FragmentViewBindings.kt:3)
	at com.github.libretube.ui.fragments.SearchResultFragment.getBinding(SearchResultFragment.kt:8)
	at com.github.libretube.ui.fragments.SearchResultFragment$fetchSearch$1.invokeSuspend(SearchResultFragment.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:42)
	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:33)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e32bd2b, Dispatchers.Main.immediate]
    `

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please update to 0.13.1!
