### ISSUE TITLE
Crash in favorite 

### ISSUE THREAD

**Issue by blap** [libre-tube/LibreTube#3583]
### Steps to reproduce

Play favorite.

### Expected behavior

Play videos.

### Actual behavior

Crash.

https://user-images.githubusercontent.com/913963/232625127-733734b3-af41-4503-a6a8-9a69a9501909.mp4

### LibreTube version

0.14.0

### Android version

Android 12

### Other details

`retrofit2.HttpException: HTTP 500 
	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:133)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:9)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8002057, Dispatchers.IO]
    `

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by blap** [comment]
`retrofit2.HttpException: HTTP 500 
	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:133)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:9)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8002057, Dispatchers.IO]
    `

**Comment by Bnyro** [comment]
Please provide the full crashlog, you can obtain it via adb or Scoop.

**Comment by blap** [comment]
> Please provide the full crashlog, you can obtain it via adb or Scoop.

From scoop

`FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: com.github.libretube, PID: 8975
retrofit2.HttpException: HTTP 500 
	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:133)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:9)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3ef47b0, Dispatchers.IO]`

**Comment by blap** [comment]
ADB log from android studio.

[adb_log.txt](https://github.com/libre-tube/LibreTube/files/11481448/adb_log.txt)

**Comment by FireMasterK** [comment]
It looks like Libretube can't handle an error response while loading streams 🤔

**Comment by Bnyro** [comment]
It should in theory. See https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt#L680-L691
