### ISSUE TITLE
Background playing paused.

### ISSUE THREAD

**Issue by Gigas212** [libre-tube/LibreTube#3589]
### Steps to reproduce

Background playing stopped while notification appeared.And not resuming by pressing play button.

### Expected behavior

While I press the play button on lock screen/libretube mainframe screen,it should be playing seemlessly.

### Actual behavior

I am playing a video/audio on background and my screen is locked.when A notification appeared.Libretube stopped playing.By pressing the playing button its not playing even I unlocked the phone & the libretube app also not playing.

### LibreTube version

0.14.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Toiletmason** [comment]
I am experiencing the same issue.  I'm on android 13 oneui 5.1

**Comment by Toiletmason** [comment]
java.lang.NullPointerException
	at com.github.libretube.ui.fragments.ChannelFragment$fetchChannel$1$1.invokeSuspend(ChannelFragment.kt:141)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d322f6a, Dispatchers.Main.immediate]

**Comment by Toiletmason** [comment]
For me, this is still occurring. It doesn't matter if I tell audio, or just turn the screen off on the video player by pressing the power button. The audio stops with the screen off somewhere between 2-3 minutes of screen off time. Using og youtube, and Newpipe doesn't have this problem. It's the only issue that I have and I'd like to ditch Newpipe permanently

**Comment by Bnyro** [comment]
If you want to play the video with screen off, it's recommended to switch to the audio mode (button below the video player) which will not be affected by Android battery saving measures. If you need more info, feel free to browse other closed issues on the same topic.

**Comment by Toiletmason** [comment]
@Bnyro I already do that my man. I'm still having the issue where it will just stop playing. I also have to close the app before anything else will play.
