### ISSUE TITLE
Crash When Navigating To Library

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#3592]
### Steps to reproduce

Has to do something with Library loading,while navigating when Library is tapped, It crashes.
Library should not be empty

### Expected behavior

only happens when library is not empty ,Something in the library fails to load and this error is occurred.
maybe this is happening when some videos or playlists r turned private. which fails fetching

### Actual behavior

It gives this Crashlog,

java.lang.NullPointerException
 at com.github.libretube.ui.fragments.LibraryFragment$fetchPlaylists$1$1.invokeSuspend(LibraryFragment.kt:64)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:210)
 at android.os.Looper.loop(Looper.java:299)
 at android.app.ActivityThread.main(ActivityThread.java:8309)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
 Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2f440c6, Dispatchers.Main.immediate]

### LibreTube version

0.14

### Android version

A13

### Other details

This error is not by me,Since devs dont use TG now, I will open issues of crashes here only with proper details.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please try to find a better way to reproduce it or share a video.

**Comment by Bnyro** [comment]
I just remembered we already addressed that some weeks ago, should be find in debug builds.
