### ISSUE TITLE
Crash when tabs are changed if Search is in progress

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#3593]
### Steps to reproduce

Search for something then switch tabs 2 times,but dont let the results appear,change tabs when it is still loading

### Expected behavior

Tabs should be changed and Search fragment should destroyed without crash.

### Actual behavior

But it crashes and gives this Crashlog.

java.lang.NullPointerException
 at com.github.libretube.ui.fragments.SearchResultFragment$fetchSearch$1$1.invokeSuspend(SearchResultFragment.kt:83)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
 at android.app.ActivityThread.main(ActivityThread.java:8757)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
 Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@979161b, Dispatchers.Main.immediate]

### LibreTube version

Latest Alpha

### Android version

A13

### Other details

https://user-images.githubusercontent.com/125901294/233090677-97b7e9cd-5871-4e82-87ee-9e9533d04751.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Jwjshhi** [comment]
Same problem

**Comment by akano12** [comment]
Nice copy/paste from telegram
