### ISSUE TITLE
Crashes on opening after closed for a while

### ISSUE THREAD

**Issue by pabloscloud** [libre-tube/LibreTube#3597]
### Steps to reproduce

Leave the app closed for a few hours then open it

### Expected behavior

No error

### Actual behavior

App crashes

### LibreTube version

0.14.0

### Android version

13

### Other details

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.ChannelFragment$fetchChannel$1$1.invokeSuspend(ChannelFragment.kt:141)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a023dd9, Dispatchers.Main.immediate]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by sunglocto** [comment]
can confirm, this happens to me constantly with the exact same crash message

**Comment by pabloscloud** [comment]
👍
