### ISSUE TITLE
Downloads crashes app after moving or deleting downloaded file

### ISSUE THREAD

**Issue by MrSrsen** [libre-tube/LibreTube#3612]
### Steps to reproduce

1. Download video
2. Go trough file manager to LibreTube files
3. Move or delete downloaded file
4. Open downloaded files in LibreTube app
5. App crashes

Crash log:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	... 1 more
Caused by: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.github.libretube/files/audio/Are You Smarter Than Me - WAN Show April 21, 2023_126_kbps_M4A.mp4
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:115)
	at j$.nio.file.spi.a.x(Unknown Source:14)
	at j$.nio.file.Files.readAttributes(SourceFile:0)
	at j$.nio.file.Files.size(Unknown Source:5)
	at com.github.libretube.ui.adapters.DownloadsAdapter.onBindViewHolder(DownloadsAdapter.kt:101)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:1157)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:59)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:825)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:79)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:64)
	at android.view.View.measure(View.java:27720)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27720)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27720)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:547)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:253)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:31)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:102)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:186)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:460)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:440)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:34)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1433)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:509)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:90)
	at android.view.View.measure(View.java:27720)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:160)
	at android.view.View.measure(View.java:27720)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27720)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27720)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27720)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1375)
	at android.view.View.measure(View.java:27720)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4841)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3426)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3732)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:852)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	... 3 more
 ```

### Expected behavior

App won't crash.

Downloaded video will be ignored and deleted from the list.

### Actual behavior

App crashed.

### LibreTube version

0.14.0

### Android version

Android 13

### Other details

My use-case was that I wanted to view downloaded file trough VLC player so I moved it to my files on filesystem. Reason was that LibreTube was not beheaved the way I expected in that it did not retain time of play after closing the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MrSrsen** [comment]
> external player function of LibreTube

Where can I find it? I can not find anything like that in the app. That sound like something that would indirectly solve my issue.

**Comment by MrSrsen** [comment]
> It's a hidden feature, just long press the share button.

https://user-images.githubusercontent.com/13176514/234211141-00b9695f-cc14-4eb8-b908-be606b3f2a68.mp4

It's not working for me.

**Comment by luckkmaxx** [comment]
> But this is not playing offline content. I need this to work for downloaded offline videos. Could this be added to context menu of downloaded videos?

 Maybe share the video with some external downloader, like TubeMate

**Comment by dhammel** [comment]
@Bnyro If removing internal database files, like where the settings of the app get saved in /data/data then yes, but removing files that the app downloads out side of app then no. Newpipe for example downloads to a folder in root of internal storage. If removing the files through file manager, next time opening the downloads section in newpipe, it will recognize those files no longer exist and clear the history in downloads.

My use case is to copy those videos to my pc and delete them from phone to free space. As of now, i have to copy instead then open libretube and delete them from downloads there. Its just a 2 step process.
