### ISSUE TITLE
Crash when accessing the app from the "recent apps" screen 

### ISSUE THREAD

**Issue by frank-372** [libre-tube/LibreTube#3645]
### Steps to reproduce

I exit the app for a while and when I try to get back in via the "recent apps" screen the app crashes.
It doesn't tend to happen when leaving for a shorter period of time, but I can't give an estimate.

### Expected behavior

The app should open as normal.

### Actual behavior

The app crashes to the home screen.

### LibreTube version

0.14.0

### Android version

Android 10

### Other details

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.SubscriptionsFragment.access$initChannelGroups(SubscriptionsFragment.kt:87)
	at com.github.libretube.ui.fragments.SubscriptionsFragment$initChannelGroups$1.invokeSuspend(SubscriptionsFragment.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@116c5fc, Dispatchers.Main.immediate]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by frank-372** [comment]
Apparently already dealt with in debug versions, so I'm closing it.

**Comment by Bnyro** [comment]
Seems like that's a different issue, will investigate shortly.
