### ISSUE TITLE
NPE when opening the app again after some time

### ISSUE THREAD

**Issue by atollk** [libre-tube/LibreTube#3653]
### Steps to reproduce

1. Open and play a video
2. Pause the video and "minimize" the app
3. Wait for a few hours
4. Open the app again via its icon

### Expected behavior

The app opens

### Actual behavior

The app crashes with:

```
java.lang.NullPointerException
	at com.github.libretube.ui.fragments.ChannelFragment$fetchChannel$1$1.invokeSuspend(ChannelFragment.kt:141)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6dfde67, Dispatchers.Main.immediate]
    ```

### LibreTube version

0.14.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#3597
