### ISSUE TITLE
Api crash when phone's locked or after a wile

### ISSUE THREAD

**Issue by rizyH** [libre-tube/LibreTube#3674]
### Steps to reproduce

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.SearchResultFragment$fetchSearch$1$1.invokeSuspend(SearchResultFragment.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@17f9e1b, Dispatchers.Main.immediate]
    

### Expected behavior

No crash ? 

### Actual behavior

Phone's crashed after a wile {about 5 minutes) or when I lock the phone

### LibreTube version

0.14.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please update to the latest version.

**Comment by rizyH** [comment]
It's already the lastet according to F-droid & the api website
