### ISSUE TITLE
Crash on import Freetube playlists

### ISSUE THREAD

**Issue by yoguut** [libre-tube/LibreTube#3675]
### Steps to reproduce

1. Settings
2. Backup & restore
3. Import playlists from Freetube (Freetube exported as `.db` file format, which is json)
4. Crash

### Expected behavior

No crash

### Actual behavior

Crash

### LibreTube version

0.14.0

### Android version

13 (custom)

### Other details

type: crash
osVersion: google/barbet/barbet:13/TQ2A.230405.003/2023041100:user/release-keys
package: com.github.libretube:33
process: com.github.libretube
processUptime: 395 + 285 ms

java.lang.NullPointerException
at com.github.libretube.ui.fragments.LibraryFragment$initBookmarks$1.invokeSuspend(LibraryFragment.kt:48)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(DispatchedTask.kt:107)
at android.os.Handler.handleCallback([Handler.java:942](http://handler.java:942/))
at android.os.Handler.dispatchMessage([Handler.java:99](http://handler.java:99/))
at android.os.Looper.loopOnce([Looper.java:201](http://looper.java:201/))
at android.os.Looper.loop([Looper.java:288](http://looper.java:288/))
at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:7891](http://activitythread.java:7891/))
at java.lang.reflect.Method.invoke(Native Method)
at [com.android](http://com.android/).internal.os.RuntimeInit$MethodAndArgsCaller.run([RuntimeInit.java:548](http://runtimeinit.java:548/))
at [com.android](http://com.android/).internal.os.ExecInit.main([ExecInit.java:49](http://execinit.java:49/))
at [com.android](http://com.android/).internal.os.RuntimeInit.nativeFinishInit(Native Method)
at [com.android](http://com.android/).internal.os.RuntimeInit.main([RuntimeInit.java:355](http://runtimeinit.java:355/))
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3fbade9, Dispatchers.Main.immediate]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Can you provide a freetube playlist file as an example?

**Comment by Bnyro** [comment]
FreeTube is not supported, you're expected to import a playlist in the NewPipe file format.

**Comment by yoguut** [comment]
> 

understood.

**Comment by yoguut** [comment]
> Can you provide a freetube playlist file as an example?


```json
[
  {
    "playlistName": "Favorites",
    "videos": [
      {
        "videoId": "0qmr4h7qWJ0",
        "title": "本山中町の家01【芦屋・西宮の建築家　シンプレックス一級建築士事務所】",
        "author": "SIMPLEX　芦屋・西宮の建築家　シンプレックス一級建築士事務所",
        "authorId": "UCCrYAB-rl_PXuMbeVBj5aqA",
        "published": "",
        "viewCount": 2082,
        "lengthSeconds": 196,
        "timeAdded": 1648508706237,
        "isLive": false,
        "paid": false,
        "type": "video"
      },
      {
        "videoId": "uBOkOllA1us",
        "title": "Expectation vs. Reality: Kevin McCloud Visits the Risky Brutalist House 2 Years On | Grand Designs",
        "author": "Channel 4 Lifestyle",
        "authorId": "UCI64UNunsXfaDZgVhsAI2tQ",
        "published": "",
        "viewCount": 325710,
        "lengthSeconds": 258,
        "timeAdded": 1648511575863,
        "isLive": false,
        "paid": false,
        "type": "video"
      },
      {
        "videoId": "39TudjkuHmY",
        "title": "BRUTALHOUSE - Part 1 - An Exploration of Brutalist Architecture",
        "author": "DEEP C",
        "authorId": "UCdb2voGo7oWnjpnt79qRMmw",
        "published": "",
        "viewCount": 2316,
        "lengthSeconds": 2236,
        "timeAdded": 1648512000559,
        "isLive": false,
        "paid": false,
        "type": "video"
      },
      {
        "videoId": "NBCHWg4GPw8",
        "title": "UE4 Archviz - Brutalist Architecture - Day One - 1080p/60fps",
        "author": "NorseFX",
        "authorId": "UCe8KrapKovhDix1mEC-0u3Q",
        "published": "",
        "viewCount": 25996,
        "lengthSeconds": 87,
        "timeAdded": 1648512080851,
        "isLive": false,
        "paid": false,
        "type": "video"
      },
      {
        "videoId": "9ABj-WSTIs8",
        "title": "The Concrete House",
        "author": "Tarry & Perry",
        "authorId": "UCOa16Mw3OmTE0FrA9GF4QUA",
        "published": "",
        "viewCount": 127208,
        "lengthSeconds": 199,
        "timeAdded": 1648512235755,
        "isLive": false,
        "paid": false,
        "type": "video"
      },
      {
        "videoId": "A0hgxx8VFso",
        "title": "An unexpected concrete design in Itu, São Paulo",
        "author": "Architecture Hunter",
        "authorId": "UCBqc02MY5MVZgqdHMlvQL7A",
        "published": "",
        "viewCount": 22963,
        "lengthSeconds": 144,
        "timeAdded": 1648581473195,
        "isLive": false,
        "paid": false,
        "type": "video"
      },
      {
        "videoId": "Wmaxuobkum0",
        "title": "【ルームツアー】眺望と光のうつろいを楽しむ高台のお家 | 憧れる素敵な暮らし | 2LDK | Room tour",
        "author": "your life is good",
        "authorId": "UCoDu3SDWoExTJtvSS8ajxwQ",
        "published": "",
        "viewCount": 721072,
        "lengthSeconds": 653,
        "timeAdded": 1650527441074,
        "isLive": false,
        "paid": false,
        "type": "video"
      },
      {
        "videoId": "ECBbAjoEHWI",
        "title": "Hydrothermal Vents | Oases in the Deep Sea",
        "author": "Natural World Facts",
        "authorId": "UCG5_BraUMNcluZPZ__oOeKg",
        "published": "",
        "viewCount": 131493,
        "lengthSeconds": 1179,
        "timeAdded": 1651315851570,
        "isLive": false,
        "paid": false,
        "type": "video"
      },
      {
        "videoId": "t9jvIyc4Hfg",
        "title": "Lifespan Expanded: The Scientific Quest For A Fountain Of Youth",
        "author": "World Science Festival",
        "authorId": "UCShHFwKyhcDo3g7hr4f1R8A",
        "published": "",
        "viewCount": 118668,
        "lengthSeconds": 5401,
        "timeAdded": 1663039489176,
        "isLive": false,
        "paid": false,
        "type": "video"
      },
      {
        "videoId": "6N1UJ4q7I14",
        "title": "Two Steps From Hell - Never Give Up On Your Dreams New Extended",
        "author": "Epic Music Mix",
        "authorId": "UCGszKyYglkDx7zE2tyNAlSw",
        "published": "",
        "viewCount": 27957,
        "lengthSeconds": 1288,
        "timeAdded": 1667884183297,
        "isLive": false,
        "paid": false,
        "type": "video"
      },
      {
        "videoId": "9cutYZpqjcU",
        "title": "ASMR Super Relaxing Layered Hair Treatment | Washing, Brushing, Massage (No Talking)",
        "author": "ASMR Bakery",
        "authorId": "UCDH70xAv1bBeaCt5Cc7a96A",
        "published": "",
        "viewCount": 11450,
        "lengthSeconds": 2820,
        "timeAdded": 1672046682633,
        "isLive": false,
        "paid": false,
        "type": "video"
      },
      {
        "videoId": "Vcj3uhy0NHw",
        "title": "STAR TRAILS on ANY Android Phone! Full Tutorial",
        "author": "Nebula Photos",
        "authorId": "UCO_gBdHekc74feh0bWqKJ1Q",
        "published": "",
        "viewCount": 588,
        "lengthSeconds": 771,
        "timeAdded": 1673544388206,
        "isLive": false,
        "paid": false,
        "type": "video"
      },
      {
        "videoId": "KYJJWx5opv8",
        "title": "Hans Zimmer Greatest Hits - The Best Songs Of Hans Zimmer Full Allbum 2018",
        "author": "Moon Chanel",
        "authorId": "UCXO0wq16j02aDRLYbVCPuGA",
        "published": "",
        "viewCount": 3346240,
        "lengthSeconds": 7765,
        "timeAdded": 1675733292078,
        "isLive": false,
        "paid": false,
        "type": "video"
      }
    ],
    "_id": "xcmrX4RAO1IOj2Mr"
  }
]
```

**Comment by Bnyro** [comment]
You can open a feature request for it if you want to, supporting it would be possible in theory with future updates.
