### ISSUE TITLE
HDR videos don't load at all on unsupported hardware 

### ISSUE THREAD

**Issue by guiopen** [libre-tube/LibreTube#3697]
### Steps to reproduce

![Screenshot_20230502-131256](https://user-images.githubusercontent.com/94094527/235725972-adbfb958-8f38-4c60-bd68-368ac88a038a.png)

1 - Open a hdr video (like this: https://www.youtube.com/watch?v=IDDmrzzB14M&t=0) on an old and cheap smartphone that don't support hdr

2 - Open and try to play the video on libretube 

### Expected behavior

As the smartphone don't support hdr, the video should play in normal sdr like the YouTube app or website 

### Actual behavior

The video don't play at all

### LibreTube version

0.14.1

### Android version

Android 11

### Other details

Using a moto g10, an entry level phone without hdr support 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by guiopen** [comment]
I think it's also related to this issue: /issues/3673

**Comment by FireMasterK** [comment]
> I think it's also related to this issue: [/issues/3673](https://github.com/libre-tube/LibreTube/issues/3673)

No, it's not, those videos are not HDR!

**Comment by Bnyro** [comment]
In theory the ExoPlayer should just handle HDR videos fine, shouldn't it? Maybe we can also get better results here by the media3 migration? Not sure.

**Comment by FireMasterK** [comment]
I can do some testing on Browserstack later, as that lets us use real devices to test applications. I'm just as confused as hardware-accelerated video decoding should normally be able to decode HDR content too (although it would display them as SDR).

**Comment by FireMasterK** [comment]
Seems like we get the following stacktrace:
```
05-02 18:44:38.081 E/MediaCodecVideoRenderer( 2617): Video codec error
05-02 18:44:38.081 E/MediaCodecVideoRenderer( 2617):   java.lang.IllegalStateException
05-02 18:44:38.081 E/MediaCodecVideoRenderer( 2617):       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
05-02 18:44:38.081 E/MediaCodecVideoRenderer( 2617):       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2630)
05-02 18:44:38.081 E/MediaCodecVideoRenderer( 2617):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:5)
05-02 18:44:38.081 E/MediaCodecVideoRenderer( 2617):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:45)
05-02 18:44:38.081 E/MediaCodecVideoRenderer( 2617):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:72)
05-02 18:44:38.081 E/MediaCodecVideoRenderer( 2617):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1009)
05-02 18:44:38.081 E/MediaCodecVideoRenderer( 2617):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:225)
05-02 18:44:38.081 E/MediaCodecVideoRenderer( 2617):       at android.os.Handler.dispatchMessage(Handler.java:101)
05-02 18:44:38.081 E/MediaCodecVideoRenderer( 2617):       at android.os.Looper.loop(Looper.java:164)
05-02 18:44:38.081 E/MediaCodecVideoRenderer( 2617):       at android.os.HandlerThread.run(HandlerThread.java:65)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617): Playback error
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(null, null, null, video/x-vnd.on2.vp9, vp9.2, 3567436, en, [1920, 1080, 30.0], [-1, -1]), format_supported=YES
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at android.os.Handler.dispatchMessage(Handler.java:101)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at android.os.Looper.loop(Looper.java:164)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at android.os.HandlerThread.run(HandlerThread.java:65)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.vp9
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:5)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:230)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1009)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:225)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       ... 3 more
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):   Caused by: java.lang.IllegalStateException
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2630)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:5)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:45)
05-02 18:44:38.082 E/ExoPlayerImplInternal( 2617):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:72)
```

(Tested on a Pixel 2)

**Comment by Bnyro** [comment]
Should we just skip the HDR streams when creating the DASH manifest if unsupported? We could figure that out with [`Display#getHdrCapabilities`](https://source.android.com/docs/core/display/hdr) in theory.

**Comment by Bnyro** [comment]
Seems weird that ExoPlayer doesn't pick the non HDR quality automatically.
