### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by jothamsia** [libre-tube/LibreTube#3738]
### Steps to reproduce

1. i was watching a video and left the app, while the video was minimized.
2. When i came back to the app it crased and gave me an error

### Expected behavior

when video is minimized and you leave and come back to the app it crashs

### Actual behavior

1. i was watching a video and left the app, while the video was minimized.
2. When i came back to the app it crased and gave me an error

### LibreTube version

0.14.0

### Android version

Android 8.0

### Other details

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.LibraryFragment$fetchPlaylists$1$1.invokeSuspend(LibraryFragment.kt:264)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bc3f141, Dispatchers.Main.immediate]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please use the latest version.
