### ISSUE TITLE
App crashes when starting to play a video

### ISSUE THREAD

**Issue by mohammadrafigh** [libre-tube/LibreTube#3758]
### Steps to reproduce

1. Open app
2. Use a custom instance with the latest version of Piped
3. Play a video
4. App crashes

### Expected behavior

App shouldn't crash.

### Actual behavior

Playing video is not working.

### LibreTube version

0.14.*

### Android version

Android 13

### Other details

I was using the same custom instance from version 0.12.* and everything was working fine till 0.14.*. I cleared the app data and started it fresh but still got the crashes. I cannot provide the custom instance info here in public. Here are some logs that I get when starting app again after a crash:

```
kotlinx.serialization.MissingFieldException: Field 'category' is required for type with serial name 'com.github.libretube.api.obj.Streams', but it was missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(StreamingJsonDecoder.kt:107)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:25)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:22)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:12)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:57)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:5)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@95f5a5e, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Field 'category' is required for type with serial name 'com.github.libretube.api.obj.Streams', but it was missing
	at androidx.core.R$styleable.throwMissingFieldException(Unknown Source:115)
	at com.github.libretube.api.obj.Streams.<init>(Streams.kt:3)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(Streams.kt:530)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(StreamingJsonDecoder.kt:67)
	... 10 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
I don't think your custom instance is up to date. Please update it and try again.

**Comment by mohammadrafigh** [comment]
OOPS! Thank you. For some reason Watchtower didn't update the images, weird. Updating Piped fixed the problem.
