### ISSUE TITLE
Crash fetching channel 

### ISSUE THREAD

**Issue by atollk** [libre-tube/LibreTube#3792]
### Steps to reproduce

Unfortunately, I wasn't able to reproduce the issue yet. But I hope the crash log provides information already.

What I was doing before the crash happened:
I was watching a video and navigated to its channel. The channel didn't load at first (I just saw the spinner) and I had to try multiple times.
When it finally worked, I bookmarked a playlist of that channel and then went back to the video. After a few seconds, the crash happened.

### Expected behavior

No crash

### Actual behavior

Crash

### LibreTube version

0.14.1

### Android version

GrapheneOS Android 13

### Other details

```
java.lang.NullPointerException
	at com.github.libretube.ui.fragments.ChannelFragment$fetchChannel$1$1.invokeSuspend(ChannelFragment.kt:340)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@46ee3b, Dispatchers.Main.immediate]
    
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by atollk** [comment]
The error happened multiple times to me by now. Unfortunately, I still haven't found the exact conditions which cause it. But it always has to do with a channel not loading for some reason and then navigating somewhere else.

The exact line is unfortunately obfuscated because of inlining but I don't see that many possible culprits in the file.

**Comment by Bnyro** [comment]
Does the issue still persist for you in the latest version?

**Comment by atollk** [comment]
I'll observe and come back with another comment if it does.

**Comment by Bnyro** [comment]
No further response, thus assuming the issue is not present anymore.
