### ISSUE TITLE
Getting crashes when clicking on comment reply

### ISSUE THREAD

**Issue by MithNo1** [libre-tube/LibreTube#3854]
### Steps to reproduce

Open comments and then click on any comment that has replies in it then click the reply it will crash then.

### Expected behavior

It should not crash when I click it.

### Actual behavior

It crashed when clicked on comment reply on any video. 

### LibreTube version

0.14.1

### Android version

12

### Other details

java.lang.NullPointerException
	at com.github.libretube.ui.adapters.CommentsAdapter.navigateToReplies(CommentsAdapter.kt:47)
	at com.github.libretube.ui.adapters.CommentsAdapter$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:15)
	at android.view.View.performClick(View.java:7512)
	at android.view.View.performClickInternal(View.java:7489)
	at android.view.View.access$3700(View.java:857)
	at android.view.View$PerformClick.run(View.java:29017)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8396)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Had this issue ever since 0.14.1 came out and didn't report it because it wasn't reproducible on debug builds.
So i guess it was fixed (so please test the nightly builds from here and report back https://github.com/libre-tube/NightlyBuilds/tree/main)

**Comment by akano12** [comment]
Also to reproduce it, double tap on any comment with replies 

https://github.com/libre-tube/LibreTube/assets/50032603/4df4bbe5-63c4-4809-a5a4-55a2bfa68f0b

**Comment by akano12** [comment]
> > Also to reproduce it, double tap on any comment with replies
> > 
> >  Screen_Recording_20230530_222414_LibreTube.mp4
> 
> So the issue is still present??

On the stable version (0.14.1) yes it is, but on debug builds it's fixed (the issue is fixed, just wait for the next update)

And you can try the debug version from the link above

**Comment by MithNo1** [comment]
Yes that's why I haven't reported many bugs before because its usually either fixed or reported by somebody else. And Libretube has become so stable now from last few versions. It's very mature now. But I was surprised to see this bug so I thought I will report it. @Bnyro thanks for all the work! Should I close this issue then? @akano12

**Comment by akano12** [comment]
> Should I close this issue then? @akano12 

I suggest you give the debug version a quick test before closing, i tried it over a week or two ago.
In case everything was ok, feel free to close it, else leave as is.
And indeed a LOT of issues were fixed since 0.14.1 came out, so i guess the next release is soon.

**Comment by MithNo1** [comment]
Fixed in 0.15.0
