### ISSUE TITLE
Crash when opening app in CommentsSheetMainFragment

### ISSUE THREAD

**Issue by gbieging** [libre-tube/LibreTube#3870]
### Steps to reproduce

1. Update to latest version
2. Open app and use normally
3. Do other stuff for some time
4. Open app again

### Expected behavior

App opens normally

### Actual behavior

App instantly closed, on reopening the following message appeared:

```
java.lang.NullPointerException
	at com.github.libretube.ui.fragments.CommentsMainFragment.onViewCreated(SourceFile:53)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:256)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:146)
	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:62)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:36)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:261)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:146)
	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:62)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:36)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:261)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:146)
	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:62)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:36)
	at androidx.fragment.app.FragmentActivity.onStart(SourceFile:35)
	at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
	at android.app.Activity.performStart(Activity.java:8616)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4204)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### LibreTube version

0.15.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by gbieging** [comment]
Still happens on version 0.16.0

```stacktrace
java.lang.NullPointerException
	at com.github.libretube.ui.fragments.CommentsMainFragment.onViewCreated(SourceFile:77)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:256)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:146)
	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:62)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:36)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:261)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:146)
	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:62)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:36)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:261)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:146)
	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:62)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:36)
	at androidx.fragment.app.FragmentActivity.onStart(SourceFile:35)
	at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
	at android.app.Activity.performStart(Activity.java:8616)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4204)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
    
```

**Comment by illerokcob** [comment]
Agree, the same happens to me on version 0.16.1, Android 11. Same crash log as well, line by line. Also, it's important that the crash only happens if the video player activity is open before leaving the app AND the activity has been destroyed due to memory saving features. The crash happens when I open the app a bit later and the activity is recreated from the saved state.
