### ISSUE TITLE
Crash when playing downloaded audio in background

### ISSUE THREAD

**Issue by NearestWater262** [libre-tube/LibreTube#3885]
### Steps to reproduce

Fully close and then Open app
Go to downloads
Press and hold on a song, Play in Background
Works fine
Now do the same for another song, app crashes

### Expected behavior

Should play normally

### Actual behavior

Crashes whole app

### LibreTube version

0.15.0

### Android version

Lineage 19

### Other details

This only started when I updated from 0.14.1 to 0.15.0 (github release). Before, playing multiple songs from my downloads in the background was working just fine.

Anyhows, when the app crashes, I start it up again and it gives me this stack trace

java.lang.IllegalStateException: Session ID must be unique. ID=
	at androidx.media3.session.MediaSession.<init>(SourceFile:55)
	at com.github.libretube.util.NowPlayingNotification.updatePlayerNotification(SourceFile:197)
	at com.github.libretube.services.OfflinePlayerService$onStartCommand$1$1.invokeSuspend(SourceFile:206)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f157f36, Dispatchers.IO]
    

I saw the below issue but it seems really different:

https://github.com/libre-tube/LibreTube/issues/3794

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Same issue as the one you have mentioned.
