### ISSUE TITLE
Crash opening description of Video with chapters

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#3908]
### Steps to reproduce

probably cannot be reproduced, i mostly watch podcasts and they have chapters,i was opening the description and chapter changed automatically on time and then closed description,when description opened again it crashed

### Expected behavior

i watch multiple Videos with chapters but faced this for first time, IK u r busy in fixing Piped so only take a look at Chapter's Adapter if something wrong otherwise close this because i am also unable to reproduce this now

### Actual behavior

CRASH

java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: ChaptersViewHolder{25aa465 position=0 id=-1, oldPos=-1, pLpos:-1 update tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{629640b VFED..... .......D 8,55-1072,354 #7f0a00b3 app:id/chapters_recView}, adapter:com.github.libretube.ui.adapters.ChaptersAdapter@79d22e8, layout:androidx.recyclerview.widget.LinearLayoutManager@5fabd01, context:com.github.libretube.ui.activities.MainActivity@434c590
 at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6620)
 at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1525)
 at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:13109)
 at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:13611)
 at androidx.recyclerview.widget.SimpleItemAnimator.dispatchChangeFinished(SimpleItemAnimator.java:317)
 at androidx.recyclerview.widget.DefaultItemAnimator$8.onAnimationEnd(DefaultItemAnimator.java:391)
 at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1115)
 at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
 at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1333)
 at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1575)
 at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
 at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
 at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
 at android.view.Choreographer.doCallbacks(Choreographer.java:899)
 at android.view.Choreographer.doFrame(Choreographer.java:827)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7874)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

### LibreTube version

Latest Alpha

### Android version

A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Good to know, but please don't ping me (see our code of conduct).
