### ISSUE TITLE
Issue Crash idk maby ignorable

### ISSUE THREAD

**Issue by HageFale** [libre-tube/LibreTube#3947]
### Steps to reproduce

java.lang.IllegalStateException: Session ID must be unique. ID=
	at androidx.media3.session.MediaSession.<init>(SourceFile:55)
	at com.github.libretube.util.NowPlayingNotification.updatePlayerNotification(SourceFile:197)
	at com.github.libretube.ui.fragments.PlayerFragment$playVideo$1$4.invokeSuspend(SourceFile:2956)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8118)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@89b7ebb, Dispatchers.IO]
    

### Expected behavior

It should not crash for no reason

### Actual behavior

its crashing for no reason

### LibreTube version

0.15.0

### Android version

Android 12 MIUI Mi11 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already fixed in debug builds.
