### ISSUE TITLE
The icon does not reset when the app clears data.

### ISSUE THREAD

**Issue by Fish25op** [libre-tube/LibreTube#3960]
### Steps to reproduce
1.Open the LibreTube Debug application.
2.Change the application Icon.
3.Clear LibreTube Debug data
4.Enter the app and select instance.
5.When the app deletes the data, the Icon is not reset.
6.Click OK and error.

### Expected behavior

Switch to the application without errors

### Actual behavior

https://github.com/libre-tube/LibreTube/assets/136016095/709bda0f-6609-43ee-9c36-69772bd03b4c

### LibreTube version

0.15.0 Debug

### Android version

Android 12

### Other details

android.content.ActivityNotFoundException: Unable to find explicit activity class {com.github.libretube.debug/com.github.libretube.ui.activities.MainActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2098)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
	at android.app.Activity.startActivityForResult(Activity.java:5473)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:728)
	at android.app.Activity.startActivityForResult(Activity.java:5431)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:709)
	at android.app.Activity.startActivity(Activity.java:5817)
	at android.app.Activity.startActivity(Activity.java:5770)
	at com.github.libretube.ui.activities.WelcomeActivity.onCreate$lambda$0(WelcomeActivity.kt:55)
	at com.github.libretube.ui.activities.WelcomeActivity.$r8$lambda$jHvE3c-XhO3NHDVazjvP88NvFKs(Unknown Source:0)
	at com.github.libretube.ui.activities.WelcomeActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7792)
	at android.widget.TextView.performClick(TextView.java:16112)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Fish25op** [comment]
This error does not occur in the latest debug version🤔😕

**Comment by Bnyro** [comment]
Maybe you had to reinstall the app first? Anyways, closing.

**Comment by Fish25op** [comment]
> Maybe you had to reinstall the app first? Anyways, closing.

I did this before, it happened again.

**Comment by Fish25op** [comment]
Damn it! The error occurs again. Open the issue😔

**Comment by Fish25op** [comment]
@Bnyro This error occurs if the application icon has changed.When you clear the app data, the icon does not reset and the error.

**Comment by Bnyro** [comment]
Hmm, makes sense. (please don't tag me, see our code of conduct)
