### ISSUE TITLE
Lates Debug Crashes When Opening Comments 

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#4033]
### Steps to reproduce

1. Play a video
2. Tap on comments button

### Expected behavior

Show comments 

### Actual behavior

LT crashes

### LibreTube version

Latest Debug 

### Android version

Android 13

### Other details

```
kotlin.UninitializedPropertyAccessException: lateinit property playerData has not been initialized
	at com.github.libretube.ui.fragments.PlayerFragment.initializeOnClickActions$lambda$4(PlayerFragment.kt:398)
	at com.github.libretube.ui.fragments.PlayerFragment.$r8$lambda$x2GIe87d5halYB00x6Jpj3yT0Ko(Unknown Source:0)
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda9.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7892)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30880)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
cc @Isira-Seneviratne

**Comment by Isira-Seneviratne** [comment]
I'll take a look at it, thanks.

**Comment by Isira-Seneviratne** [comment]
#4034

**Comment by Bnyro** [comment]
That was fast, thank you!

**Comment by Isira-Seneviratne** [comment]
It was a small change I overlooked, my bad.
