### ISSUE TITLE
video not downloding

### ISSUE THREAD

**Issue by Golukumar00** [libre-tube/LibreTube#4149]
### Steps to reproduce
After clicking on the download button, the download starts, but only a partial portion of the audio is downloaded. The download gets stuck when I try to stop it from the notification panel, causing the app to crash and display an error.

### Expected behavior

No response 

### Actual behavior

No response 

### LibreTube version

Nighty build 

### Android version

Android 12

### Other details

java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.libretube.helpers.DownloadHelper.getNotificationId, parameter <this>
	at com.github.libretube.helpers.DownloadHelper.getNotificationId(Unknown Source:2)
	at com.github.libretube.services.DownloadService$stop$1$1.invokeSuspend(DownloadService.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7880)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b9c90ab, Dispatchers.Main.immediate]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Mentioned the wrong issue in that PR
