### ISSUE TITLE
Bug Apps Debug

### ISSUE THREAD

**Issue by DPRRI** [libre-tube/LibreTube#4154]
### Steps to reproduce

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.libretube/com.github.libretube.ui.activities.MainActivity}: org.chromium.base.JniException: Unable to instantiate fragment com.github.libretube.ui.dialogs.DownloadDialog: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: org.chromium.base.JniException: Unable to instantiate fragment com.github.libretube.ui.dialogs.DownloadDialog: could not find Fragment constructor
	at androidx.fragment.app.FragmentManager$3.instantiate(SourceFile:59)
	at androidx.fragment.app.FragmentState.instantiate(SourceFile:3)
	at androidx.fragment.app.FragmentStateManager.<init>(SourceFile:12)
	at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(SourceFile:269)
	at androidx.fragment.app.Fragment.onCreate(SourceFile:17)
	at com.github.libretube.ui.fragments.PlayerFragment.onCreate(SourceFile:1)
	at androidx.fragment.app.FragmentStateManager.create(SourceFile:66)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:151)
	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:62)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:36)
	at androidx.fragment.app.FragmentActivity.onCreate(SourceFile:29)
	at com.github.libretube.ui.base.BaseActivity.onCreate(SourceFile:817)
	at com.github.libretube.ui.activities.MainActivity.onCreate(SourceFile:3)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	... 12 more
Caused by: java.lang.NoSuchMethodException: com.github.libretube.ui.dialogs.DownloadDialog.<init> []
	at java.lang.Class.getConstructor0(Class.java:2363)
	at java.lang.Class.getConstructor(Class.java:1759)
	at androidx.fragment.app.FragmentManager$3.instantiate(SourceFile:24)
	... 28 more
    

### Expected behavior

Bug

### Actual behavior

Bug home

### LibreTube version

0.15

### Android version

Android 12

### Other details

Fix

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please use the issue template properly.
