### ISSUE TITLE
App crashes when attempting to open while mini player is open

### ISSUE THREAD

**Issue by terminal-cs** [libre-tube/LibreTube#4162]
### Steps to reproduce

1) play any video
2) exit the app and allow the mini player to show
3) try to re-enter the app via the app icon on the home screen
Not that this does not happen when the full screen button on the mini player is pressed, and the app opens normally.

### Expected behavior

The app should re-open as expected to whatever video is currently playing

### Actual behavior

App crashes
Error log:
```
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.github.libretube/com.github.libretube.ui.activities.MainActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2197)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1839)
	at android.app.Activity.startActivityForResult(Activity.java:5507)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
	at android.app.Activity.startActivityForResult(Activity.java:5465)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:1)
	at android.app.Activity.startActivity(Activity.java:5963)
	at android.app.Activity.startActivity(Activity.java:5930)
	at com.github.libretube.ui.activities.MainActivity.loadIntentData(SourceFile:32)
	at com.github.libretube.ui.activities.MainActivity.onNewIntent(SourceFile:7)
	at android.app.Activity.performNewIntent(Activity.java:8358)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1517)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1530)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3821)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3828)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    
```

### LibreTube version

0.15.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I didn't know we're already at version 1.15.1

**Comment by terminal-cs** [comment]
> I didn't know we're already at version 1.15.1

Oops meant 0.15.1

**Comment by Bnyro** [comment]
This looks like an issue of the ROM or launcher: Can't reproduce this on any Android emulator or devices.

**Comment by terminal-cs** [comment]
> This looks like an issue of the ROM or launcher: Can't reproduce this on any Android emulator or devices.

Using stock google pixel 7 software, with niagra launcher. Have you tried that launcher?

**Comment by Bnyro** [comment]
Have you tried the stock launcher? I don't use non-foss apps on my main phone.

**Comment by terminal-cs** [comment]
> Have you tried the stock launcher? I don't use non-foss apps on my main phone.

Just tried, still happens with the stock launcher
