### ISSUE TITLE
Chapter selection crashes app likely in horizontal view

### ISSUE THREAD

**Issue by ticklemyIP** [libre-tube/LibreTube#4198]
### Steps to reproduce

1. Open video with chapters
2. Turn video sideways
3. Interact witch chapter selection at least by opening it
4. App crashes

### Expected behavior

App doesn't crash

### Actual behavior

App crashes.

### LibreTube version

0.16.0

### Android version

Android 13

### Other details

I tried to reproduce it multiple times but could't narrow it down enough what triggers it. It only happen in horizontal view. Doesn't happen anymore. Did catch an error report though:

`java.lang.IndexOutOfBoundsException: Index: 6, Size: 5
	at java.util.ArrayList.get(ArrayList.java:437)
	at androidx.media3.session.MediaSessionStub$$ExternalSyntheticLambda6.run(SourceFile:455)
	at com.github.libretube.helpers.PlayerHelper$$ExternalSyntheticLambda1.onShow(SourceFile:22)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1916)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#4214
