### ISSUE TITLE
Crash when starting video

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#4229]
### Steps to reproduce

1. Search for grapheneos
2. Try to play this video 

https://www.youtube.com/watch?v=4To-F6W1NT0

### Expected behavior

Video should play

### Actual behavior

App crashes

### LibreTube version

Latest debug and 0.16.0

### Android version

Android 13

### Other details

java.lang.IllegalArgumentException: unexpected host: 
	at okhttp3.HttpUrl$Builder.host(HttpUrl.kt:961)
	at com.github.libretube.helpers.ProxyHelper.unwrapUrl(ProxyHelper.kt:65)
	at com.github.libretube.helpers.ProxyHelper.unwrapUrl$default(ProxyHelper.kt:62)
	at com.github.libretube.helpers.ProxyHelper.shouldDisableProxy(ProxyHelper.kt:45)
	at com.github.libretube.ui.fragments.PlayerFragment.setStreamSource(PlayerFragment.kt:1294)
	at com.github.libretube.ui.fragments.PlayerFragment.access$setStreamSource(PlayerFragment.kt:127)
	at com.github.libretube.ui.fragments.PlayerFragment$setResolutionAndSubtitles$2.invokeSuspend(PlayerFragment.kt:1241)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cc95373, Dispatchers.IO]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Problem isn't with the video, it's caused by the "Fallback to Piped Proxy" option.
Disable it for now.

**Comment by akano12** [comment]
Also https://github.com/libre-tube/LibreTube/issues/4192
