### ISSUE TITLE
App crashes playing in background 

### ISSUE THREAD

**Issue by kemk** [libre-tube/LibreTube#4246]
### Steps to reproduce

When a video is playing in background whith screen off, the app crashes with the following error:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.libretube/com.github.libretube.ui.activities.MainActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.github.libretube/com.github.libretube.ui.activities.MainActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3689)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3826)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:227)
	at android.os.Looper.loop(Looper.java:327)
	at android.app.ActivityThread.main(ActivityThread.java:7967)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.github.libretube/com.github.libretube.ui.activities.MainActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2304)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1947)
	at android.app.Activity.startActivityForResult(Activity.java:5470)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
	at android.app.Activity.startActivityForResult(Activity.java:5428)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:1)
	at android.app.Activity.startActivity(Activity.java:5926)
	at android.app.Activity.startActivity(Activity.java:5893)
	at com.github.libretube.ui.activities.MainActivity.loadIntentData(SourceFile:32)
	at com.github.libretube.ui.activities.MainActivity.onCreate(SourceFile:870)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8269)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1398)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3670)
	... 12 more
    

### Expected behavior

The app should be able to keep playing without crash

### Actual behavior

App crashes

### LibreTube version

0.16.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Try with the latest version (current is 0.16.1)
