### ISSUE TITLE
Application crashes after closing the video in full screen mode

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#4256]
### Steps to reproduce

1. Open the application
2. Open the video
3. Go to full screen mode
4. Close the video by tapping the cross button in the top left corner.
5. App crashes

### Expected behavior

The app stays open and displays the last page opened before the video was opened.

### Actual behavior

Screen recording: [link](https://drive.filen.io/d/fbb14ef8-b524-4c68-b36b-3d6782f75d6d#ybmOQrGgXXSYBDCIs6bX7rUnc4oPTCTq) (GitHub says that the file is too big)

Crash log:
```
java.lang.NullPointerException
 at com.github.libretube.ui.fragments.PlayerFragment.setFullscreen(SourceFile:3)
 at com.github.libretube.ui.fragments.PlayerFragment.onConfigurationChanged(SourceFile:48)
 at androidx.fragment.app.FragmentManager.dispatchConfigurationChanged(SourceFile:46)
 at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda0.accept(SourceFile:52)
 at androidx.activity.ComponentActivity.onConfigurationChanged(SourceFile:22)
 at androidx.appcompat.app.AppCompatActivity.onConfigurationChanged(SourceFile:1)
 at com.github.libretube.ui.activities.MainActivity.onConfigurationChanged(SourceFile:6)
 at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:5973)
 at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5889)
 at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6149)
 at android.app.ActivityThread$ActivityClientRecord.lambda$init$0$ActivityThread$ActivityClientRecord(ActivityThread.java:668)
 at android.app.ActivityThread$ActivityClientRecord$$ExternalSyntheticLambda0.onConfigurationChanged(Unknown Source:2)
 at android.view.ViewRootImpl.performConfigurationChange(ViewRootImpl.java:5170)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2921)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8793)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
 at android.view.Choreographer.doCallbacks(Choreographer.java:845)
 at android.view.Choreographer.doFrame(Choreographer.java:780)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7870)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### LibreTube version

0.16.0 - 0.16.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you please try the latest debug build concerning this issue?

I haven't been able to reproduce it so far, but the chances are good the linked PR fixed it.

**Comment by DanielProg39** [comment]
> I haven't been able to reproduce it so far

Make sure you close the video without pausing it. Also, the bug does not seem to be reproducible if you open the app in landscape mode before opening the video (the video automatically opens in full screen mode and closes properly), so it only happens if you open the video when your phone is in vertical orientation, so you then switch it to full screen mode and the bug is reproducible.

> Could you please try the latest debug build concerning this issue?

Sure, I'll install it now and give you feedback as soon as possible.

**Comment by DanielProg39** [comment]
Seems that the broblem has been resolved (though I was a bit sceptical regarding changes in #4381, tbh).

I also decided to reinstall the stable version, will see if anything changes. By the way, which version would you recommend, F-droid or IzzyOnDroid and what's the difference between them? Just the signature? I've used one from IzzyOnDroid before and F-droid says that the IzzyOnDroid version is "recommended", so I'm about to decide. My thoughts are: it's not like NewPipe, where the new build has to be shipped as soon as possible, because it's often the only one that works. A 2-3 day delay between versions in the F-droid and IzzyOnDroid repos is not critical, nor is an app prone to crashing all the time, as its functionality is heavily dependent on the cloud. So that brings up the question I asked earlier.

PS. The default icon of LibreTube Debug is so beautiful, I'd like to have it as an option in the stable version :wink:

**Comment by Bnyro** [comment]
Yes, I accidentally includes formatting changes in that commit as well. The relevant change has been https://github.com/libre-tube/LibreTube/pull/4381/files#diff-850346ac5a1f8db4ca79415f3b517d1a09598dde4b28302d9937a093aacd7cc2R1615.

F-Droid builds the code from source so you can always be 100% sure that the code on GitHub is the one that's included in the apk.
However, since F-Droid can be very slow with updates sometimes, I would recommend using the IzzyOnDroid version, as they're being update-checked daily. That could be important id there'd be any breaking Piped API changes for example (unlikely to be happening as long as there are no fundamentally breaking YT changes). Nevertheless bug fix releases for LibreTube are important for the UX as well: two or three days days less with an annoying crash can be important for the convenience. Though LibreTube should be more stable now than it was earlier, that should become less and less important.

F-Droid builds sometimes failed already for LibreTube, or one time they had technical issues that prevented them from updating any app for two weeks, which is something I never experienced with Izzy's repo.

Hope that mostly answers the question.

PS: the icon looks that way to attract users to test the debug builds before releases to mitigate fixes before creating a new update :)

**Comment by DanielProg39** [comment]
@Bnyro I wrote you in Matrix
