### ISSUE TITLE
Unique ID required

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#4281]
### Steps to reproduce

Not sure if reproducable.
1. App crashes without error message
2. Reopen app
3. Click on video you watched before
4. App crashes with error message

### Expected behavior

Video should play

### Actual behavior

App crashes aftwr clicking on video.

### LibreTube version

0.16.1

### Android version

Android 13

### Other details

java.lang.IllegalStateException: Session ID must be unique. ID=
	at androidx.media3.session.MediaSession.<init>(MediaSession.java:556)
	at androidx.media3.session.MediaSession$Builder.build(MediaSession.java:363)
	at com.github.libretube.util.NowPlayingNotification.createMediaSession(NowPlayingNotification.kt:223)
	at com.github.libretube.util.NowPlayingNotification.updatePlayerNotification(NowPlayingNotification.kt:289)
	at com.github.libretube.ui.fragments.PlayerFragment.initializePlayerNotification(PlayerFragment.kt:1393)
	at com.github.libretube.ui.fragments.PlayerFragment.access$initializePlayerNotification(PlayerFragment.kt:129)
	at com.github.libretube.ui.fragments.PlayerFragment$playVideo$1$5.invokeSuspend(PlayerFragment.kt:764)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e1b36c6, Dispatchers.IO]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/4272
