### ISSUE TITLE
Feature request: Add setting to select download destination folder

### ISSUE THREAD

**Issue by mtris** [libre-tube/LibreTube#4292]
### Describe your suggested feature

Dear LibreTube Team: If possible, could a option be added in settings to select the destination folder of downloads? Currently, I am able to initiate a download, I see the dialog showing the download, but I am unable to locate the file once complete.
Android 13
Thank you for your consideration. If anyone knows where the completed downloads currently land, please let me know. Thank you again and great job on a well thought out app. Sincerely,

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Downloads are meant to be played in the app only (library -> downloads), therefore they are located at `Android/data/com.github.libretube`.

**Comment by mtris** [comment]
Hello: Thank you very much for the reply: Unfortunately after the latest Android update, I no longer have access to the Android/data folder.
In the app, I am able to go to the library tab but, when I click downloads, the app crashes with the report generated below. Thank you again for your consideration and your time.

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	... 1 more
Caused by: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.github.libretube/files/audio/Cisco Default Hold Music - [HQ Mono Audio] - Opus Number 1_126_kbps_M4A.mp4
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:115)
	at j$.nio.file.spi.a.x(Unknown Source:14)
	at j$.nio.file.Files.readAttributes(SourceFile:0)
	at j$.nio.file.Files.size(Unknown Source:5)
	at com.github.libretube.ui.adapters.DownloadsAdapter.onBindViewHolder(SourceFile:293)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:1136)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source:5)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:838)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:79)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(SourceFile:64)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7038)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7038)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26392)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(SourceFile:541)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(SourceFile:245)
	at retrofit2.Utils.verticalSolvingPass(SourceFile:31)
	at retrofit2.Utils.solveVerticalMatchConstraint(SourceFile:102)
	at retrofit2.Utils.verticalSolvingPass(SourceFile:186)
	at retrofit2.Utils.verticalSolvingPass(SourceFile:460)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(SourceFile:440)
	at androidx.lifecycle.ViewModelProvider.solveLinearSystem(SourceFile:36)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(SourceFile:1183)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:382)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(SourceFile:72)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7038)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7038)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7038)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7038)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7038)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:806)
	at android.view.View.measure(View.java:26392)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3993)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2660)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2940)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9283)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327)
	at android.view.Choreographer.doCallbacks(Choreographer.java:985)
	at android.view.Choreographer.doFrame(Choreographer.java:916)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8022)
	... 3 more

**Comment by Bnyro** [comment]
#3379
