### ISSUE TITLE
[Android 6] Crash when importing Libretube backup

### ISSUE THREAD

**Issue by Gamer750** [libre-tube/LibreTube#4358]
### Steps to reproduce

First open setting and click backup and restore

### Expected behavior

App should restore previous settings

### Actual behavior

java.io.FileNotFoundException: /storage/emulated/0/libretube-backup-2023-08-03-21_16_52.json: open failed: EACCES (Permission denied)
at libcore.io.IoBridge.open(IoBridge.java:452)
at java.io.FileInputStream.<init>(FileInputStream.java:76)
at java.io.FileInputStream.<init>(FileInputStream.java:103)
at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
at okio.Path$Companion.restoreAdvancedBackup(SourceFile:198)
at com.github.libretube.ui.activities.WelcomeActivity$restoreFilePicker$1$1.invokeSuspend(SourceFile:40)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
at androidx.work.Worker$2.run(SourceFile:53)
at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@88844b9, Dispatchers.IO]
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
at libcore.io.Posix.open(Native Method)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
at libcore.io.IoBridge.open(IoBridge.java:438)
... 10 more
   

### LibreTube version

0.16.1

### Android version

Android 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Android 6 is not the current focus of development and support for it will probably be dropped soon.
If anyone wants to open a PR with a fix, that'd be welcome though.
