### ISSUE TITLE
App crashes with the chapters

### ISSUE THREAD

**Issue by Unaiperezdiaz** [libre-tube/LibreTube#4374]
### Steps to reproduce

1. Go to any video that has chapters.
2. Click on any chapter of the video
3. Choose another video and the application crashes.

### Expected behavior

No crashes.

### Actual behavior

The application crashes.

### LibreTube version

Last debug LibreTube

### Android version

13

### Other details

Realme GT Master Edition

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
`java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment.getBinding(PlayerFragment.kt:135)
	at com.github.libretube.ui.fragments.PlayerFragment.getPlayerBinding(PlayerFragment.kt:137)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:1184)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName$default(PlayerFragment.kt:1183)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName$setCurrentChapterName(PlayerFragment.kt:1190)
	at com.github.libretube.ui.fragments.PlayerFragment.$r8$lambda$e8dQ99yjeNVp0o77dB1eH2xQQwE(Unknown Source:0)
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda15.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
    `

**Comment by akano12** [comment]
```
java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment.getBinding(PlayerFragment.kt:135)
	at com.github.libretube.ui.fragments.PlayerFragment.getPlayerBinding(PlayerFragment.kt:137)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:1184)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName$default(PlayerFragment.kt:1183)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName$setCurrentChapterName(PlayerFragment.kt:1190)
	at com.github.libretube.ui.fragments.PlayerFragment.$r8$lambda$e8dQ99yjeNVp0o77dB1eH2xQQwE(Unknown Source:0)
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda15.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
    
```

**Comment by Unaiperezdiaz** [comment]
On my cell phone:
java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment.getBinding(PlayerFragment.kt:135)
	at com.github.libretube.ui.fragments.PlayerFragment.getPlayerBinding(PlayerFragment.kt:137)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:1184)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName$default(PlayerFragment.kt:1183)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName$setCurrentChapterName(PlayerFragment.kt:1190)
	at com.github.libretube.ui.fragments.PlayerFragment.$r8$lambda$e8dQ99yjeNVp0o77dB1eH2xQQwE(Unknown Source:0)
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda15.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8381)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
