### ISSUE TITLE
Libretube close error report

### ISSUE THREAD

**Issue by Dodo12345678901** [libre-tube/LibreTube#4396]
### Steps to reproduce

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment.killPlayerFragment(SourceFile:23)
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda1.onClick(SourceFile:585)
	at android.view.View.performClick(View.java:7892)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30880)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
    

### Expected behavior

Application closed

### Actual behavior

Video stopped playing Video stopped playing 

### LibreTube version

0.16.1

### Android version

Android 13

### Other details

Application closed 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a screen recording and edit your issue with steps to reproduce.
