### ISSUE TITLE
Crashes when clicking on Library Button

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#4491]
### Steps to reproduce

1. Click Library Button

java.lang.ArrayIndexOutOfBoundsException: length=4; index=-1
 at com.github.libretube.ui.fragments.LibraryFragment.onViewCreated(SourceFile:377)
 at androidx.fragment.app.FragmentStateManager.createView(SourceFile:296)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:144)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:1429)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:92)
 at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:74)
 at androidx.fragment.app.DialogFragment$1.run(SourceFile:22)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
 at android.app.ActivityThread.main(ActivityThread.java:8751)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### Expected behavior

Show Downloads, Watch History, Playlist and Bookmarks

### Actual behavior

Crashes the application

### LibreTube version

0.17.1 & Latest Debug

### Android version

Android 12

### Other details

0.17.1

https://github.com/libre-tube/LibreTube/assets/90308888/d14bbbe0-c893-45ba-bd04-d34959abe24c

0.17.1 Latest Debug

https://github.com/libre-tube/LibreTube/assets/90308888/0b154335-65e1-41a7-bf74-7d4606475216

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Eliya-Manoj** [comment]
I can explain through video. I can reproduce this problem over and over again. 

https://github.com/libre-tube/LibreTube/assets/90308888/4834dc15-e869-4c0d-8ce1-f29d785a49c6

**Comment by Eliya-Manoj** [comment]
[libretube-backup-2023-08-13-20_51_36.txt](https://github.com/libre-tube/LibreTube/files/12345879/libretube-backup-2023-08-13-20_51_36.txt)
I changed the .json to .txt

**Comment by Bnyro** [comment]
[libretube-backup-2023-08-13-20_51_36.txt](https://github.com/libre-tube/LibreTube/files/12346072/libretube-backup-2023-08-13-20_51_36.txt)


Please restore that file in the settings, or if you don't trust me, search for `playlists_order` in the file and replace the value from `recent` to `creation_date`.

**Comment by Bnyro** [comment]
I'm not sure why that's set to `recent`, I'll pin it if others have the same issue.

**Comment by Bnyro** [comment]
Does that fix it?

**Comment by Eliya-Manoj** [comment]
Yes

**Comment by Bnyro** [comment]
Figured it out: the changes were introduced with https://github.com/libre-tube/LibreTube/commit/a392cb07dace06fec83175c80faea0279756d1d3 3 months ago. If you changed the playlists order in the settings before 3 months ago, and never changed the setting ever since, it will crash.

**Comment by Bnyro** [comment]
Please clear the app data before importing the backup.

**Comment by niktss** [comment]
> A fix for that will also be part of the next update in a month or so - but I think it's better to just quickly fix it yourself using the description above.

Would you please reconsider and issue a hotfix instead? Backups are borked for a lot of people due to #3427 , so implementing this workaround means losing all watch history

**Comment by Bnyro** [comment]
As described above you should only backup your preferences - which works without a problem. The watch history won't get lost by that, you don't clear your app data in that process.

**Comment by niktss** [comment]
> As described above you should only backup your preferences - which works without a problem. The watch history won't get lost by that, you don't clear your app data in that process.

Oh okay. It's just that you advised iamgitcat to wipe data, so I assumed it was mandatory to fix the issue

**Comment by RedCableGuy** [comment]
Library is my home section when I open the app, therefore it already crashes when I start it. Is there somehow a way to fix the issue "from the outside"?

**Comment by Bnyro** [comment]
Yes, you can open the settings while the internet is turned off (turn internet off and restart app).

**Comment by RedCableGuy** [comment]
That worked, thanks!

**Comment by niko4479** [comment]
Hi, where I can find the file 'backupfile' after generated ?

**Comment by spaceturtle11** [comment]
Tried to fix it as instructed, still crashes.

`java.lang.ArrayIndexOutOfBoundsException: length=4; index=-1
	at com.github.libretube.ui.fragments.LibraryFragment.onViewCreated(SourceFile:377)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:296)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:144)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:1429)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:92)
	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:74)
	at androidx.fragment.app.DialogFragment$1.run(SourceFile:22)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
    `

**Comment by pcm8081** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=4; index=-1
	at com.github.libretube.ui.fragments.LibraryFragment.onViewCreated(SourceFile:377)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:296)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:144)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:1429)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:92)
	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:74)
	at androidx.fragment.app.DialogFragment$1.run(SourceFile:22)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:241)
	at android.os.Looper.loop(Looper.java:342)
	at android.app.ActivityThread.main(ActivityThread.java:8138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by pcm8081** [comment]
> java.lang.ArrayIndexOutOfBoundsException: length=4; index=-1
> 	at com.github.libretube.ui.fragments.LibraryFragment.onViewCreated(SourceFile:377)
> 	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:296)
> 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:144)
> 	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:1429)
> 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:92)
> 	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:74)
> 	at androidx.fragment.app.DialogFragment$1.run(SourceFile:22)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:241)
> 	at android.os.Looper.loop(Looper.java:342)
> 	at android.app.ActivityThread.main(ActivityThread.java:8138)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
>     

Still crash

**Comment by pcm8081** [comment]
still crashes

**Comment by Leichesters** [comment]
@Bnyro when will the new update be published? Facing the same issue for quite some time and I don't know how to properly use the quick fix without deleting my watch history

**Comment by FireMasterK** [comment]
> @Bnyro when will the new update be published? Facing the same issue for quite some time and I don't know how to properly use the quick fix without deleting my watch history

Please do not tag maintainers. This is also explicitly stated in the code of conduct. If you continue this behavior, we may have to take action, based on the enforcement guidelines.

**Comment by Leichesters** [comment]
> > @Bnyro when will the new update be published? Facing the same issue for quite some time and I don't know how to properly use the quick fix without deleting my watch history
> 
> Please do not tag maintainers. This is also explicitly stated in the code of conduct. If you continue this behavior, we may have to take action, based on the enforcement guidelines.

sorry.

**Comment by Bnyro** [comment]
There's no ETA on the next update, however we don't aim to merge any new features before the next release, so it won't last too long from now on.
