### ISSUE TITLE
Crash while scrubbing seek bar on specific video

### ISSUE THREAD

**Issue by reyarthurr** [libre-tube/LibreTube#4494]
### Steps to reproduce

Example:
1. Open the playback history.
2. Play any video.
3. Move it forward or backward at different points of time.
4. Crash.

### Expected behavior

Move video forward or backward at different points of time without crashing the app

### Actual behavior

When I move at different points of time the video crashes the application.

### LibreTube version

0.17.1

### Android version

Android 12 Stock

### Other details

java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
	at android.graphics.Bitmap.createBitmap(Bitmap.java:858)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:818)
	at com.github.libretube.util.OnlineTimeFrameReceiver.getFrameAtTime(SourceFile:274)
	at com.github.libretube.util.OnlineTimeFrameReceiver$getFrameAtTime$1.invokeSuspend(Unknown Source:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(SourceFile:7)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:32)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a4ed276, Dispatchers.IO]

https://github.com/libre-tube/LibreTube/assets/119883321/513e949d-51e8-4f23-9eab-b7f24fef462d

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Unaiperezdiaz** [comment]
I'm using the Alpha version and temporarily I don't have any problems. (For now)

**Comment by reyarthurr** [comment]
> unable to replicate bro,with same video from both home screen and library but video says otherwise,maybe devs can identify the problem.update to aplha and see if you are using lbry or hls setting

Where can I get the application in alpha version to test the problem?

**Comment by reyarthurr** [comment]
I tried with the alpha version and activate the HLS and LBRY options and the same problem always occurs

https://github.com/libre-tube/LibreTube/assets/119883321/5db71a78-5237-4529-bc55-6fa7bc93a4fe

**Comment by Unaiperezdiaz** [comment]
Try changing the instance, sometimes some videos can't be played for some reason

**Comment by reyarthurr** [comment]
The problem is always the same in another instance and the most curious thing is that I tried the same video in Newpipe and almost the same error occurs.

**Comment by reyarthurr** [comment]
Could it be that maybe my specific device is the problem? Or would I have to do a clean reinstallation of libretube to newpipe?

Just in case anyone is interested or curious to know what newpipe throws, here is the error report:

java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
	at android.graphics.Bitmap.createBitmap(Bitmap.java:858)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:818)
	at org.schabi.newpipe.player.seekbarpreview.SeekbarPreviewThumbnailHolder.lambda$generateDataFrom$3(SeekbarPreviewThumbnailHolder.java:143)
	at org.schabi.newpipe.player.seekbarpreview.SeekbarPreviewThumbnailHolder.$r8$lambda$0elxBGHHcmMbO9kgf0vknFIh1sg(SeekbarPreviewThumbnailHolder.java:0)
	at org.schabi.newpipe.player.seekbarpreview.SeekbarPreviewThumbnailHolder$$ExternalSyntheticLambda4.get(R8$$SyntheticClass:0)
	at org.schabi.newpipe.player.seekbarpreview.SeekbarPreviewThumbnailHolder.getBitmapAt(SeekbarPreviewThumbnailHolder.java:214)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.onProgressChanged(VideoPlayerUi.java:581)
	at org.schabi.newpipe.views.FocusAwareSeekBar$NestedListener.onProgressChanged(FocusAwareSeekBar.java:130)
	at android.widget.SeekBar.onProgressRefresh(SeekBar.java:99)
	at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1577)
	at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1686)
	at android.widget.ProgressBar.setProgressInternal(ProgressBar.java:1752)
	at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:1016)
	at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:942)
	at android.view.View.dispatchTouchEvent(View.java:14541)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4195)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
	at android.view.View.dispatchPointerEvent(View.java:14800)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6362)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6163)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5641)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5698)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5664)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5829)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5672)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5886)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5645)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5698)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5664)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5672)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5645)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8584)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8535)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8503)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8707)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:260)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7880)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)


https://github.com/libre-tube/LibreTube/assets/119883321/2cce5c99-8e7d-4428-9099-fa68c905c179

**Comment by Unaiperezdiaz** [comment]
This is on a android 13, Realme GT Master Edition with alpha version

**Comment by Bnyro** [comment]
That's only reproducible with this video: https://piped.video/watch?v=qcycAKDzOPQ.

**Comment by Unaiperezdiaz** [comment]
I have tried in my browser with brave (OS arch Linux)
![report.png](https://github.com/libre-tube/LibreTube/assets/49728036/a3936102-b94e-4d03-9a49-873586137ee6)

**Comment by Unaiperezdiaz** [comment]
I don't know if this is the behavior that we're expecting
