### ISSUE TITLE
App crashing when tapping video

### ISSUE THREAD

**Issue by amadoumx** [libre-tube/LibreTube#4496]
### **Steps to reproduce**

Example:

Start the app. 

Tap on video.

Crash.

### **Expected behavior**

video starts without crashing the app

### **Actual behavior**

App crashing 

LibreTube version

0.17.1

Android version

Android 12 OxygenOS

### **Other details**

kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:124)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:25)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at retrofit2.DefaultCallAdapterFactory$1.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e1dc4c6, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing
	at okio.Okio.throwMissingFieldException(SourceFile:115)
	at com.github.libretube.api.obj.Streams.<init>(SourceFile:3)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:722)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	... 9 more

**Comment by amadoumx** [comment]
Thanks for the reply. Changing the instance worked.

**Comment by Bnyro** [comment]
If it's a public instance of Piped, please also contact the instance's maintainer and kindly ask them to update to the latest version of Piped.
