### ISSUE TITLE
App crash when opening Sponsor Block settings

### ISSUE THREAD

**Issue by fakep7497** [libre-tube/LibreTube#4527]
### Steps to reproduce

Open sponsorblock settings

### Expected behavior

Should open the sponsorblock setting without any problem

### Actual behavior

App crash with error as follows

```
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:321)
	at androidx.preference.Preference.getPersistedInt(SourceFile:16)
	at com.github.libretube.ui.views.ColorPreference.onSetInitialValue(SourceFile:17)
	at androidx.preference.Preference.onAttachedToHierarchy(SourceFile:39)
	at androidx.preference.PreferenceInflater.rInflate(SourceFile:313)
	at androidx.preference.PreferenceInflater.rInflate(SourceFile:345)
	at androidx.preference.PreferenceInflater.inflate(SourceFile:42)
	at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(SourceFile:25)
	at com.github.libretube.ui.preferences.SponsorBlockSettings.onCreatePreferences(SourceFile:4)
	at androidx.preference.PreferenceFragmentCompat.onCreate(SourceFile:68)
	at androidx.fragment.app.FragmentStateManager.create(SourceFile:71)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:149)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:1429)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:82)
	at androidx.fragment.app.FragmentManager.execSingleAction(SourceFile:32)
	at com.github.libretube.ui.preferences.MainSettings.navigateToSettingsFragment(SourceFile:26)
	at com.github.libretube.ui.preferences.MainSettings$$ExternalSyntheticLambda0.onPreferenceClick(SourceFile:112)
	at androidx.preference.Preference.performClick(SourceFile:20)
	at androidx.preference.Preference$1.onClick(SourceFile:358)
	at android.view.View.performClick(View.java:8160)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
 ```

### LibreTube version

0.17.1

### Android version

Android 11

### Other details

This issue is there since version 0.16.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You recently restored a backup that causes this - as workaround for now, remove every value whose key starts with `sb_color`, and re-import the backup (or send the file here and I can send you the edited file back).

**Comment by fakep7497** [comment]
Thanks
Issue resolved ✅ with removed key `sponsorblock_color`

**Comment by fakep7497** [comment]
Actually when i undo the file and restore again i do not face the issue. Don't know why😅

attached pref file may help
[libretube-backup-2023-08-17-16_39_09.json.txt](https://github.com/libre-tube/LibreTube/files/12369006/libretube-backup-2023-08-17-16_39_09.json.txt)

**Comment by Bnyro** [comment]
Thanks, but that's not needed :)
I already know what it's caused by and how to fix it, I'll push a fix the next time I'm at my PC :)

**Comment by Bnyro** [comment]
Actually, we already have that code here: https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/helpers/BackupHelper.kt#L95.
The issue only exists if you restored the backup in anything else than the latest version.
