### ISSUE TITLE
Crash opening instance settings but not always

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#4528]
### Steps to reproduce

open instance settings

### Expected behavior

no crash

### Actual behavior

recyclerview error

### LibreTube version

Latest Alpha

### Android version

A13

### Other details

java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{c7a55b0 VFED.V... ......ID 0,0-1080,1966 #7f0a0289 app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@8dde926, layout:androidx.recyclerview.widget.LinearLayoutManager@c524c29, context:com.github.libretube.ui.activities.SettingsActivity@52eacd1
 at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:3441)
 at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:6025)
 at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:13128)
 at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:8050)
 at androidx.preference.PreferenceGroupAdapter.onPreferenceChange(PreferenceGroupAdapter.java:354)
 at androidx.preference.Preference.notifyChanged(Preference.java:1294)
 at androidx.preference.Preference.setSummaryProvider(Preference.java:1107)
 at com.github.libretube.ui.preferences.InstanceSettings.initInstancesPref(InstanceSettings.kt:135)
 at com.github.libretube.ui.preferences.InstanceSettings.access$initInstancesPref(InstanceSettings.kt:27)
 at com.github.libretube.ui.preferences.InstanceSettings$initInstancesPref$1.invokeSuspend(Unknown Source:15)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
 at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
 at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b9217a0, Dispatchers.IO]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#4216
