### ISSUE TITLE
Crash when trying to play video

### ISSUE THREAD

**Issue by zooool** [libre-tube/LibreTube#4543]
### Steps to reproduce

1. Search for video
2. Tap it to start playing
3. App crashes

### Expected behavior

The video starts playing.

### Actual behavior

`kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:124)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:25)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at retrofit2.DefaultCallAdapterFactory$1.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1a43ffc, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing
	at okio.Okio.throwMissingFieldException(SourceFile:115)
	at com.github.libretube.api.obj.Streams.<init>(SourceFile:3)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:722)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	... 9 more`

### LibreTube version

0.17.1 armv8

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's because the Piped instance you use is not up to date - use another one or tell the owner to update their instance.

**Comment by omentic** [comment]
This seems like it'd be a common occurrence. Any chance Libretube could catch this error instead of crashing?

**Comment by zooool** [comment]
@Bnyro errors should always be caught and never cause app crashes, even if it's due to a 3rd party.
!reopen
