### ISSUE TITLE
App not working Java.lang Issue Lineage OS

### ISSUE THREAD

**Issue by wuniversales** [libre-tube/LibreTube#4618]
### Steps to reproduce

I don't know if it's an isolated case but it doesn't work for me with the latest version of Lineage OS.
This is the error, I can't navigate the menus or anything, the app just closes and then when I open it, it gives this error.

```
java.lang.ArrayIndexOutOfBoundsException: length=4; index=-1
	at com.github.libretube.ui.fragments.LibraryFragment.onViewCreated(SourceFile:377)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:296)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:144)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:1429)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:92)
	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:74)
	at androidx.fragment.app.DialogFragment$1.run(SourceFile:22)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    
```

### Expected behavior

should work

### Actual behavior

Not work

### LibreTube version

Latest f-droid build

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by wuniversales** [comment]
Sorry, duplicated issue
