### ISSUE TITLE
Error when trying to access Library

### ISSUE THREAD

**Issue by heartlog** [libre-tube/LibreTube#4639]
### Steps to reproduce

1. Open the Libretube
2. Click on library
3. Libretube will crash automatically

### Expected behavior

Library should open..
Even after clearing catch, problem is still there.

### Actual behavior

After crashing, Libretube throws error. I have pasted it in other details.

### LibreTube version

0.17.1

### Android version

Android 13

## Error Log:
```
java.lang.ArrayIndexOutOfBoundsException: length=4; index=-1
	at com.github.libretube.ui.fragments.LibraryFragment.onViewCreated(SourceFile:377)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:296)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:144)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:1429)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:92)
	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:74)
	at androidx.fragment.app.DialogFragment$1.run(SourceFile:22)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by heartlog** [comment]
I think I found some solution.
