### ISSUE TITLE
Crash when auto fullscreen is enabled

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#4864]
### Steps to reproduce

1. Open the app
2. Make sure you have "automatic full-screen mode" enabled in settings, if not - enable it
3. Open any video
4. App crashes

### Expected behavior

Video should start playing

### Actual behavior

App crashes

### LibreTube version

LibreTube Debug installed today (don't remember which exact commit)

### Android version

Android 13

### Other details

Crash log:
```
kotlin.UninitializedPropertyAccessException: lateinit property trackSelector has not been initialized
	at com.github.libretube.ui.fragments.PlayerFragment.setPlayerResolution(PlayerFragment.kt:1327)
	at com.github.libretube.ui.fragments.PlayerFragment.updateResolutionOnFullscreenChange(PlayerFragment.kt:1337)
	at com.github.libretube.ui.fragments.PlayerFragment.unsetFullscreen(PlayerFragment.kt:578)
	at com.github.libretube.ui.fragments.PlayerFragment.onConfigurationChanged(PlayerFragment.kt:1715)
	at com.github.libretube.ui.fragments.PlayerFragment.changeOrientationMode(PlayerFragment.kt:1467)
	at com.github.libretube.ui.fragments.PlayerFragment.onViewCreated(PlayerFragment.kt:289)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1751)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
	at com.github.libretube.helpers.NavigationHelper.navigateVideo(NavigationHelper.kt:165)
	at com.github.libretube.helpers.NavigationHelper.navigateVideo$default(NavigationHelper.kt:52)
	at com.github.libretube.ui.adapters.WatchHistoryAdapter.onBindViewHolder$lambda$5$lambda$2(WatchHistoryAdapter.kt:70)
	at com.github.libretube.ui.adapters.WatchHistoryAdapter.$r8$lambda$qoptevtwdDBF7r6KQaQUUtEJar8(Unknown Source:0)
	at com.github.libretube.ui.adapters.WatchHistoryAdapter$$ExternalSyntheticLambda1.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29476)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Can't reproduce +
There's a new debug version released 2 minutes ago, give it a try

**Comment by DanielProg39** [comment]
/

**Comment by DanielProg39** [comment]
It was a mouseslip

**Comment by DanielProg39** [comment]
Well, it is reproducible in the latest version

**Comment by DanielProg39** [comment]
Here's the recording:

https://github.com/libre-tube/LibreTube/assets/63293432/22681276-b7cc-44ad-bcfb-ef34f6343ee8

**Comment by DanielProg39** [comment]
Clearing cache doesn't help

**Comment by DanielProg39** [comment]
Update: no matter what video I open (from history, feed or channel page), it makes the app crash

**Comment by DanielProg39** [comment]
> > Update: no matter what video I open (from history, feed or channel page), it makes the app crash
> 
> try backing up data, clean install and play video , after that restore backup

So I made a backup, deleted app data, deleted the app itself, installed it again, opened the video from trends - successfull. Then I restored data from a backup (history, watch positions and settings), logged in to Piped, opened the video - app crashes

**Comment by DanielProg39** [comment]
Maybe it's something with settings? I mean maybe new version contains some change in settings that makes current settings configuration break the app?

**Comment by DanielProg39** [comment]
I'll try to make a backup without settings, will see if it helps

**Comment by DanielProg39** [comment]
> Maybe it's something with settings? I mean maybe new version contains some change in settings that makes current settings configuration break the app?

I might be right. New version probably changes or breaks some player settings. I made a backup without settings, reinstalled the app, restored data from backup and logged in. All videos play as usual

**Comment by DanielProg39** [comment]
I found what causes the bug. It's the "automatic full-screen mode" which makes video to enter full screen mode when the device is rotated. When this feature is enabled, the player crashes every time I open a video. Try to reproduce

**Comment by akano12** [comment]
Rename the issue title to crash when auto fillscreen is enabled

**Comment by DanielProg39** [comment]
I think that "can't reproduce" label is no longer valid

**Comment by DanielProg39** [comment]
Something also tells me that the root of the problem might be this new option to set no-fullscreen resolution of video.

![Screenshot_20230927-140054_Trebuchet](https://github.com/libre-tube/LibreTube/assets/63293432/e4bb1043-e8b2-4964-8450-ba813ef6746e)

**Comment by Bnyro** [comment]
Oh, with that hint, I know what's going on now :+1:
