### ISSUE TITLE
crash when playing a video

### ISSUE THREAD

**Issue by VereinsamtFreigeist** [libre-tube/LibreTube#4890]
### Steps to reproduce

1. searching a video
2. playing one of the search results
3. crash and Libretube closed

### Expected behavior

video should play

### Actual behavior

Crash and App is closed

### LibreTube version

0.18.1

### Android version

12

### Other details

Error code:
kotlinx.datetime.DateTimeFormatException: j$.time.format.DateTimeParseException: Text '2023-04-01T23:30:10-07:00' could not be parsed, unparsed text found at index 10
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:20)
	at kotlinx.datetime.serializers.LocalDateIso8601Serializer.deserialize(SourceFile:15)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at okio._UtilKt.decodeSerializableElement(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:50)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:555)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7ce6fea, Dispatchers.IO]
Caused by: j$.time.format.DateTimeParseException: Text '2023-04-01T23:30:10-07:00' could not be parsed, unparsed text found at index 10
	at j$.time.format.DateTimeFormatter.parseResolved0(Unknown Source:160)
	at j$.time.format.DateTimeFormatter.parse(Unknown Source:11)
	at j$.time.LocalDate.parse(Unknown Source:10)
	at j$.time.LocalDate.parse(Unknown Source:2)
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:6)
	... 15 more
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/4884
