### ISSUE TITLE
Error when loading specific video

### ISSUE THREAD

**Issue by ticklemyIP** [libre-tube/LibreTube#4891]
### Steps to reproduce

1. Try opening https://www.youtube.com/watch?v=jGwy7yLDM4w
2. App crashes with error below

### Expected behavior

Video plays regularly

### Actual behavior

App crashes when playing video

### LibreTube version

0.18.1

### Android version

Android 13

### Other details

<details><summary>Error code</summary>
<p>
kotlinx.datetime.DateTimeFormatException: j$.time.format.DateTimeParseException: Text '2022-02-18T05:05:19-08:00' could not be parsed, unparsed text found at index 10
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:20)
	at kotlinx.datetime.serializers.LocalDateIso8601Serializer.deserialize(SourceFile:15)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at okio._UtilKt.decodeSerializableElement(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:50)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:555)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@144a7da, Dispatchers.IO]
Caused by: j$.time.format.DateTimeParseException: Text '2022-02-18T05:05:19-08:00' could not be parsed, unparsed text found at index 10
	at j$.time.format.DateTimeFormatter.parseResolved0(Unknown Source:160)
	at j$.time.format.DateTimeFormatter.parse(Unknown Source:11)
	at j$.time.LocalDate.parse(Unknown Source:10)
	at j$.time.LocalDate.parse(Unknown Source:2)
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:6)
	... 15 more
</p>
</details> 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by nekorubu** [comment]
Can reproduce on my end, but with [this video](https://www.youtube.com/watch?v=S8Smq6q50_4) and [this video](https://www.youtube.com/watch?v=l2oYqQx_bZs). What's interesting is that the video you've given works for me, and even more oddly, I just watched the first video that I listed earlier this morning.

**Comment by ticklemyIP** [comment]
Is the error code same for you? Might be worth including yours too.

**Comment by Rstment25** [comment]
I'm attaching picture below for easier viewing ( the link that breaks it for me is this one: https://www.youtube.com/watch?v=Xp5ruI1uvdE )

![Screenshot_20231004-161420_LibreTube](https://github.com/libre-tube/LibreTube/assets/32986283/41f342f7-0536-48ad-bba3-435603f3d3ed)

**Comment by Rstment25** [comment]
> All the links you have sent work perfectly fine for me, have you tried changing instance? I'm currently using simpleprivacy.fr with the latest version of LibreTube and they all works.

You're right. The official instance is crashing , I've switched to libre one and no more crashing

**Comment by nekorubu** [comment]
> All the links you have sent work perfectly fine for me, have you tried changing instance? I'm currently using simpleprivacy.fr with the latest version of LibreTube and they all work.

I've been using https://invidious.plasmatrap.com, as well as using the app with the proxy disabled, and both have caused crashes. However, switching to the libre instance does resolve the crashes

**Comment by Rstment25** [comment]
> > All the links you have sent work perfectly fine for me, have you tried changing instance? I'm currently using simpleprivacy.fr with the latest version of LibreTube and they all work.
> 
> I've been using https://invidious.plasmatrap.com, as well as using the app with the proxy disabled, and both have caused crashes. However, switching to the libre instance does resolve the crashes

Yeah even the libre instance is crashing... just with a different video than before.

Videos that crash one instance are very likely to work on all other instances - I'm assuming every instance is crashing, it's just a matter of finding which link will crash which instance 🙃

**Comment by Eliya-Manoj** [comment]
Same problem happened. now, no problem.
