### ISSUE TITLE
Crash when startig video

### ISSUE THREAD

**Issue by Silther** [libre-tube/LibreTube#4903]
### Steps to reproduce

1. Start a specific video like: `https://www.youtube.com/watch?v=ag_SQh4Ikds`
2. player opens
3. app crashes

### Expected behavior

Video should play

### Actual behavior

App Crashes

### LibreTube version

0.16.1 and latest debug

### Android version

Android 13

### Other details

kotlinx.datetime.DateTimeFormatException: j$.time.format.DateTimeParseException: Text '2019-11-24T04:23:59-08:00' could not be parsed, unparsed text found at index 10
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:20)
	at kotlinx.datetime.serializers.LocalDateIso8601Serializer.deserialize(SourceFile:15)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at okio._UtilKt.decodeSerializableElement(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:50)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:555)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c1141f6, Dispatchers.IO]
Caused by: j$.time.format.DateTimeParseException: Text '2019-11-24T04:23:59-08:00' could not be parsed, unparsed text found at index 10
	at j$.time.format.DateTimeFormatter.parseResolved0(Unknown Source:160)
	at j$.time.format.DateTimeFormatter.parse(Unknown Source:11)
	at j$.time.LocalDate.parse(Unknown Source:10)
	at j$.time.LocalDate.parse(Unknown Source:2)
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:6)
	... 15 more

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Eliya-Manoj** [comment]
https://github.com/libre-tube/LibreTube/issues/4884

**Comment by akano12** [comment]
Already fixed in debug
