### ISSUE TITLE
libretube crashes as I start a video 

### ISSUE THREAD

**Issue by Ehiffi** [libre-tube/LibreTube#4910]
### Steps to reproduce

1. Open libretube
2. find a video lcd Soundsystem daftpunk that is playing at my house
3. Play the video
4. Crash 

### Expected behavior

It should play the video I guess

### Actual behavior

It crashes )

### LibreTube version

0.18.1

### Android version

android 12l

### Other details

Crash log : kotlinx.datetime.DateTimeFormatException: j$.time.format.DateTimeParseException: Text '2009-03-06T15:40:55-08:00' could not be parsed, unparsed text found at index 10
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:20)
	at kotlinx.datetime.serializers.LocalDateIso8601Serializer.deserialize(SourceFile:15)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at okio._UtilKt.decodeSerializableElement(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:50)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:555)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6980d45, Dispatchers.IO]
Caused by: j$.time.format.DateTimeParseException: Text '2009-03-06T15:40:55-08:00' could not be parsed, unparsed text found at index 10
	at j$.time.format.DateTimeFormatter.parseResolved0(Unknown Source:160)
	at j$.time.format.DateTimeFormatter.parse(Unknown Source:11)
	at j$.time.LocalDate.parse(Unknown Source:10)
	at j$.time.LocalDate.parse(Unknown Source:2)
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:6)
	... 15 more
    

I have no idea why it has this behavior but it's not just this video, it may happen again on another, it's sorta random but somethimes it crashes, you start the same video and it crashes again, again and again. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ehiffi** [comment]
I see this behavior on all videos so far, and it started out of blue as another issue was made 5 mins earlier than mine

**Comment by Ehiffi** [comment]
Sorry GitHub fro browser sucks. See this issue got out of blue and started just now
