### ISSUE TITLE
App crashes when choosing a video to play 

### ISSUE THREAD

**Issue by yendrrek** [libre-tube/LibreTube#4922]
### Steps to reproduce

Happens randomly and occasionally. The only solution seems to be reinstalling the app.
You tap a video thumbnail and the app crashes. This is the exception thrown:

kotlinx.datetime.DateTimeFormatException: j$.time.format.DateTimeParseException: Text '2017-10-02T06:00:02-07:00' could not be parsed, unparsed text found at index 10
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:20)
	at kotlinx.datetime.serializers.LocalDateIso8601Serializer.deserialize(SourceFile:15)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at okio._UtilKt.decodeSerializableElement(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:50)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:555)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a69b996, Dispatchers.IO]
Caused by: j$.time.format.DateTimeParseException: Text '2017-10-02T06:00:02-07:00' could not be parsed, unparsed text found at index 10
	at j$.time.format.DateTimeFormatter.parseResolved0(Unknown Source:160)
	at j$.time.format.DateTimeFormatter.parse(Unknown Source:11)
	at j$.time.LocalDate.parse(Unknown Source:10)
	at j$.time.LocalDate.parse(Unknown Source:2)
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:6)
	... 15 more
    

### Expected behavior

App plays videos. 

### Actual behavior

App crashes. 

### LibreTube version

0.18.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by yendrrek** [comment]
Duplicate and resolved as per new release note.
