### ISSUE TITLE
App crashing when I open a video.

### ISSUE THREAD

**Issue by amogusussy** [libre-tube/LibreTube#4923]
### Steps to reproduce

1. Set a different auth instance. (piped.yt)
2. Try to play a video
3. Aop crashes. 

### Expected behavior

The videos should play normally. 

### Actual behavior

Aop crashes  

### LibreTube version

0.17.1

### Android version

Android 13

### Other details

Log that gets outputted when I reopen the app:

```
kotlinx.datetime.DateTimeFormatException: j$.time.format.DateTimeParseException: Text '2023-10-06T15:57:17-07:00' could not be parsed, unparsed text found at index 10
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:20)
	at kotlinx.datetime.serializers.LocalDateIso8601Serializer.deserialize(SourceFile:15)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at okio._UtilKt.decodeSerializableElement(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:49)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:515)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:25)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at retrofit2.DefaultCallAdapterFactory$1.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@40c6945, Dispatchers.IO]
Caused by: j$.time.format.DateTimeParseException: Text '2023-10-06T15:57:17-07:00' could not be parsed, unparsed text found at index 10
	at j$.time.format.DateTimeFormatter.parseResolved0(Unknown Source:160)
	at j$.time.format.DateTimeFormatter.parse(Unknown Source:11)
	at j$.time.LocalDate.parse(Unknown Source:10)
	at j$.time.LocalDate.parse(Unknown Source:2)
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:6)
	... 15 more
    ```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Update to latest version & https://github.com/libre-tube/LibreTube/issues/4884

**Comment by akano12** [comment]
Update to latest version & https://github.com/libre-tube/LibreTube/issues/4884
