### ISSUE TITLE
Deserialization Bug (Thanks, Gooble)

### ISSUE THREAD

**Issue by DostoevskyOnLinux** [libre-tube/LibreTube#4925]
### Steps to reproduce

Ex.
    1. Open a video such as [this one](https://m.youtube.com/watch?v=No_A22Mdxb0&pp=ygUUdGhlIGxpbnV4IGV4cGVyaW1lbnQ%3D) .
    2. App crashes with the following error:

> kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:124)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@df82bd7, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing
	at _COROUTINE._BOUNDARY.throwMissingFieldException(SourceFile:115)
	at com.github.libretube.api.obj.Streams.<init>(SourceFile:3)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:709)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	... 9 more
    

### Expected behavior

It should handle this? Or expect different input? IDK. Probably shouldn't crash, though...

### Actual behavior

Crashes when opening a video like that.

### LibreTube version

0.19.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by DostoevskyOnLinux** [comment]
I'd like to try helping with this one if it's determined to be an actual issue, and not just the server acting up... If you have the time, could you point me to the place I need to get started? I have a couple months' worth of experience with Kotlin & Jetpack Compose stuff, and I'd like to try giving back to this project.

**Comment by DostoevskyOnLinux** [comment]
Huh. Nevermind. I changed server instances, and it works. Sorry, I got ahead of myself with this bug report...
