### ISSUE TITLE
v0.18.1 Crashes When Opening a Video from Subscriptions

### ISSUE THREAD

**Issue by NeilPandya** [libre-tube/LibreTube#4930]
### Steps to reproduce

Running version 0.18.1 (APK downloaded from Releases in this repo) on:

Pixel 7
Android 13
Android security update: September 1, 2023
Google Play store update: August 1, 2023
Baseband: g5300g-230323-230525-B-10200345,g5300g-230323-230525-B-10200345
Kernel: 5.10.157-android13-4-00003-g776d0a76f6aa-ab10208116
#1 Thu May 25 12:11:12 UTC 2023
Build Number: TQ3A.230901.001

### Expected behavior

Selected video should play normally.

### Actual behavior

App crashes to home screen, forcing a relaunch 

### LibreTube version

0.18.1

### Android version

Android 13

### Other details

Log dump:

```
kotlinx.datetime.DateTimeFormatException: j$.time.format.DateTimeParseException: Text '2023-10-07T15:00:24-07:00' could not be parsed, unparsed text found at index 10
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:20)
	at kotlinx.datetime.serializers.LocalDateIso8601Serializer.deserialize(SourceFile:15)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at okio._UtilKt.decodeSerializableElement(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:50)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:555)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@97cb3fe, Dispatchers.IO]
Caused by: j$.time.format.DateTimeParseException: Text '2023-10-07T15:00:24-07:00' could not be parsed, unparsed text found at index 10
	at j$.time.format.DateTimeFormatter.parseResolved0(Unknown Source:160)
	at j$.time.format.DateTimeFormatter.parse(Unknown Source:11)
	at j$.time.LocalDate.parse(Unknown Source:10)
	at j$.time.LocalDate.parse(Unknown Source:2)
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:6)
	... 15 more
  
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/4884 & update to latest version

**Comment by NeilPandya** [comment]
> #4884 & update to latest version

Oof, sorry, I'm on mobile so I must've scrolled past #4884; forgive me for the duplicate!
