### ISSUE TITLE
crashes after tapping on the video

### ISSUE THREAD

**Issue by AmineAlikhani** [libre-tube/LibreTube#5075]
### Steps to reproduce

every time I want to play a video by tapping on it the whole app goes in the background and when I switch to it again I see this Error message:
kotlinx.datetime.DateTimeFormatException: j$.time.format.DateTimeParseException: Text '2020-12-30T04:46:30-08:00' could not be parsed, unparsed text found at index 10
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:20)
	at kotlinx.datetime.serializers.LocalDateIso8601Serializer.deserialize(SourceFile:15)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at okio._UtilKt.decodeSerializableElement(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:49)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:515)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:25)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at retrofit2.DefaultCallAdapterFactory$1.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@94fb751, Dispatchers.IO]
Caused by: j$.time.format.DateTimeParseException: Text '2020-12-30T04:46:30-08:00' could not be parsed, unparsed text found at index 10
	at j$.time.format.DateTimeFormatter.parseResolved0(SourceFile)
	at j$.time.format.DateTimeFormatter.parse(SourceFile)
	at j$.time.LocalDate.parse(SourceFile)
	at j$.time.LocalDate.parse(SourceFile)
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:6)
	... 15 more
    

### Expected behavior

play the video

### Actual behavior

app goes in the background

### LibreTube version

0.17.1

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
You're using extremely old version of the app, update to latest version
