### ISSUE TITLE
Crashes when opening video settings in audio mode

### ISSUE THREAD

**Issue by balt-dev** [libre-tube/LibreTube#5137]
### Steps to reproduce

Open a video
Enter audio mode
Long-press to open settings

### Expected behavior

Settings open

### Actual behavior

App crashes

### LibreTube version

0.19.0

### Android version

Android 12

### Other details
```
java.lang.NullPointerException
	at com.github.libretube.ui.sheets.VideoOptionsBottomSheet.onCreate(SourceFile:22)
	at androidx.fragment.app.Fragment.performCreate(SourceFile:22)
	at androidx.fragment.app.FragmentStateManager.create(SourceFile:51)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:177)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:1574)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:92)
	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:74)
	at androidx.fragment.app.DialogFragment$1.run(SourceFile:22)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7880)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed in debug builds.
