### ISSUE TITLE
App crash when viewing certain videos

### ISSUE THREAD

**Issue by CryogenicPotato** [libre-tube/LibreTube#5198]
### Steps to reproduce

Watch the following video https://piped.video/watch?v=DH0AKVCXlec&t=0 

### Expected behavior

App should not crash

### Actual behavior

App crashes with the following exception :

kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:158)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@dd667d0, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing
	at coil.util.DrawableUtils.throwMissingFieldException(SourceFile:115)
	at com.github.libretube.api.obj.Streams.<init>(SourceFile:1)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:1)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:2)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:102)
	... 9 more
    

### LibreTube version

0.20.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5148#issuecomment-1810604961
