### ISSUE TITLE
App crashes when opening videos

### ISSUE THREAD

**Issue by Digitalhell666** [libre-tube/LibreTube#5213]
### Steps to reproduce

1. Open the app, app loads normally
2. Click on video to play
3. App crashes and displays the following

kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:158)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f9d0bad, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing
	at okio.-SegmentedByteString.throwMissingFieldException(SourceFile:115)
	at com.github.libretube.api.obj.Streams.<init>(SourceFile:1)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:1)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:2)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:102)
	... 9 more
    

### Expected behavior

Open the app to play video, click on a video and the video plays

### Actual behavior

Open the app, click on the video, app crashes

### LibreTube version

0.20.1

### Android version

Android 12

### Other details

![Screenshot_20231122-120239_LibreTube](https://github.com/libre-tube/LibreTube/assets/135291660/6b61068a-f8e6-4a09-8c3c-25e2f8d670d2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5148#issuecomment-1810604961
