### ISSUE TITLE
Can't play downloaded media

### ISSUE THREAD

**Issue by Pinguin10000** [libre-tube/LibreTube#5237]
### Describe your suggested feature

Since Android 13 patch November, it is no longer possible to write data to the root folder of Android, let alone read it, so downloaded videos from Libretube will not be played 

### Other details

Error Code:
java.lang.RuntimeException: setDataSource failed: status = 0x80000000
	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:313)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:254)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:359)
	at com.github.libretube.util.OfflineTimeFrameReceiver.<init>(SourceFile:18)
	at com.github.libretube.ui.activities.OfflinePlayerActivity$playVideo$1.invokeSuspend(SourceFile:553)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4845c6e, Dispatchers.Main.immediate]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We don't save any downloaded files in the root folder.

**Comment by Pinguin10000** [comment]
0/Android/data/com.github.libretube/files/

**Comment by Ladas552** [comment]
Have the same problem. Buy Don't think it's the folder problem, because I have a video from a couple of weeks back that is still playable. But if I download new ones they return error or black screen. To be specific: Avc1 crashes the app, and VP9 gives

![Screenshot_2023-11-29-08-11-57-23_54f92cd6866f5233ab0db4392b806878](https://github.com/libre-tube/LibreTube/assets/94762349/e1c84ac3-ca20-4fce-b573-ec13f0676781)
 black screen.

```
java.lang.RuntimeException: setDataSource failed: status = 0x80000000
	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:328)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:260)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:373)
	at com.github.libretube.util.OfflineTimeFrameReceiver.<init>(SourceFile:18)
	at com.github.libretube.ui.activities.OfflinePlayerActivity$playVideo$1.invokeSuspend(SourceFile:595)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@34cd61, Dispatchers.Main.immediate]
```
![Screenshot_2023-11-29-08-16-40-79_54f92cd6866f5233ab0db4392b806878](https://github.com/libre-tube/LibreTube/assets/94762349/4398bc63-972d-4ba5-8b2f-f203733c4d72)

**Comment by MinekPo1** [comment]
I'm having the same issue on Android 12, last I have installed is from early September, so the issue is not with the patch or Android 13.

Manufacturer, Device: Motorola e22 
OS, API version, arch: Android 12, 31, arm64-v8a

I can confirm that, as Ladas552 said, Avc1 crashes, VP9 gives black screen.

Testing the files with VLC, it cant open it either.

I'm attaching downloads of [this video](https://youtu.be/RAhJEPyXFe4) in 480p with both Avc1 and VP9, to hopefully help in any debugging efforts.

Avc1

https://github.com/libre-tube/LibreTube/assets/68391527/4691f7aa-67b8-486f-8bcc-ed17a08030f1

VP9

https://github.com/libre-tube/LibreTube/assets/68391527/82a9c5d8-1199-4ff8-9012-d065378dc992

**Comment by uouo2020** [comment]
hi i recently update libretune and show me this : and i cant open and see videos like before, I am from iran 
kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:158)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e4e1994, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing
	at okio.-SegmentedByteString.throwMissingFieldException(SourceFile:115)
	at com.github.libretube.api.obj.Streams.<init>(SourceFile:1)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:1)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:2)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:102)
	... 10 more

**Comment by zagatta** [comment]
I am having the same problem.

**Comment by alexandru0-dev** [comment]
Same error, black screen on videos and crash on when clicking on downloaded content.

Running android 14 and latest version of Libretube

**Comment by Wildeyed2** [comment]
Someone closed my question saying I had the same problem than shown here.
I cant see why nor how

PROBLEM
I cant play (sometimes) any video on libretube (although I can download them) but I do can read already downloaded stuff with VLC.

The error message says something about 'illegal argument' and writes as follow :
java.lang.IllegalArgumentException
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:80)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:164)
	at com.github.libretube.util.OfflineTimeFrameReceiver.<init>(SourceFile:18)
	at com.github.libretube.ui.activities.OfflinePlayerActivity$playVideo$1.invokeSuspend(SourceFile:553)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c7d1d72, Dispatchers.Main.immediate]

Could someone kindly.reopen my.ticket or does it mean ill have no help whatsoever ?

**Comment by alexandru0-dev** [comment]
> Could someone kindly.reopen my.ticket or does it mean ill have no help whatsoever ?

@Wildeyed2 Your issue is the same as all of the people that commented in this "ticket".
So any updates etc are also going to be tracked into this "ticket".
The reason that your "ticket" was closed is because it is a duplicate. There is no reason to track the same issue twice. Any updates are going to be found here.
U are going to get help once the issue is solved.

(Btw they are called "issues" not "tickets")

**Comment by Wildeyed2** [comment]
Im sorry im not very tech savy but how can it be the same issue when the problem is different and the error message too? 
I have no problem at all with downloading and listening to my downloads with vlc, nor with.libre-tube, unlike the other people in this thread.
And none of them wrote ( as I did) that the problem seemed to be solved by itself as soon as I left home

**Comment by imadnyc** [comment]
This affects me as well - pixel5a on graphene.

**Comment by Terkyz** [comment]
Same issue on Android 12...

**Comment by Pinguin10000** [comment]
I found the downloaded media file and this file can i play it

**Comment by Jolg42** [comment]
I also have this crash
```
Error Code:
java.lang.RuntimeException: setDataSource failed: status = 0x80000000
....
```

When trying to play a downloaded video. I can't play any of the videos I downloaded.

With
- a Pixel 8 with GrapheneOS
- Android 14 - SDK 34
- LibreTube v0.20.1 (latest)

I'm not sure what I can do to help here, if you have ideas, let me know.

I checked the `Android/data/com.github.libretube/files/` and the video files were playable but without sound, since the audio is in a different file.

**Comment by vehosah** [comment]
Have the same problem, with the black screen

**Comment by endingisnight** [comment]
Was able to replicate. Problem seems to be with the "Disable piped proxy", disabling it seems to fix it.

**Comment by Pinguin10000** [comment]
Works again

**Comment by SFAZ38** [comment]
> Works again

Works for whom. For me it doesn't works at all. Download fails when its near to end.
