### ISSUE TITLE
App crashes when trying to play video

### ISSUE THREAD

**Issue by SmsmGH** [libre-tube/LibreTube#5246]
### Steps to reproduce

1. Open app
2. List of videos loads normally
3. Tap on video
4. App crashes before loading any video

### Expected behavior

Video should start loading and play

### Actual behavior

App crashes

### LibreTube version

0.20.1

### Android version

13

### Other details

OneUI 5.1 on a Samsung M52 5g

kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:158)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ee6e918, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing
	at okio.-SegmentedByteString.throwMissingFieldException(SourceFile:115)
	at com.github.libretube.api.obj.Streams.<init>(SourceFile:1)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:1)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:2)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:102)
	... 9 more
    

https://github.com/libre-tube/LibreTube/assets/103067021/ceae363e-6c35-490a-9e1c-ada62ab894fb

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by IndusAryan** [comment]
your instance isnt updated, change instance
