### ISSUE TITLE
App crashes when exiting full-screen of a video, which was played from a link from the Google app

### ISSUE THREAD

**Issue by Amr-Ibra** [libre-tube/LibreTube#5265]
### Steps to reproduce

1. Open the Google app
2. Browse the news for a YouTube video
3. Choose to open the YouTube video in LibreTube
4. In LibreTube, go full-screen
5. Exit full-screen

### Expected behavior

App crashes with this error on the next app start:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.libretube/com.github.libretube.ui.activities.MainActivity}: org.chromium.base.JniException: lateinit property exoPlayer has not been initialized
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5280)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5188)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:57)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5239)
	at android.app.ActivityThread.access$3400(ActivityThread.java:220)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2027)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: org.chromium.base.JniException: lateinit property exoPlayer has not been initialized
	at com.github.libretube.ui.fragments.PlayerFragment.onDestroy(SourceFile:148)
	at androidx.fragment.app.Fragment.performDestroy(SourceFile:20)
	at androidx.fragment.app.FragmentStateManager.destroy(SourceFile:125)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:370)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:1574)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:82)
	at androidx.fragment.app.FragmentManager.execSingleAction(SourceFile:32)
	at com.github.libretube.helpers.NavigationHelper.navigateVideo$default(SourceFile:171)
	at com.github.libretube.ui.activities.MainActivity.loadIntentData(SourceFile:204)
	at com.github.libretube.ui.activities.MainActivity.onCreate(SourceFile:866)
	at android.app.Activity.performCreate(Activity.java:7802)
	at android.app.Activity.performCreate(Activity.java:7791)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1300)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
	... 16 more
    `

### Actual behavior

No crash

### LibreTube version

0.20.1

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Amr-Ibra** [comment]
Maybe a relevant app setting:
- General → Screen orientation → _Auto-rotation_
