### ISSUE TITLE
Unable to play any videos anymore, even after changing instance and updating app

### ISSUE THREAD

**Issue by Raj2032** [libre-tube/LibreTube#5282]
### Steps to reproduce

Attempting to play video shows a loading symbol and then stops loading.

### Expected behavior

should play video

### Actual behavior

Not being able to play the video

### LibreTube version

0.20.1

### Android version

Android 9 - Samsung Galaxy S8

### Other details

Somewhere last week I tried to play a video but could not get it to load, tried different videos same thing, I tried to change to different instances, same behaviour, in some instances the app would even crash, I did update the app but same issues persist, I tried to uninstall and reinstall, I tried to clear my cache and data. Its just no longer able to load any videos.

When it crashes when using one of the instances here is one example of the error log:

```
kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:158)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cbf228a, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing
	at okio.-SegmentedByteString.throwMissingFieldException(SourceFile:115)
	at com.github.libretube.api.obj.Streams.<init>(SourceFile:1)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:1)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:2)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:102)
	... 9 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
For the crashing problem, change your instance as the one you selected is outdated.
For the video playing problem, check pinned issues

**Comment by Raj2032** [comment]
@akano12 sorry if this comes off as being a troll question but where do I find pinned issues? I just went to the issues page I can't find any pinned issues?
