### ISSUE TITLE
Videos are not playing 

### ISSUE THREAD

**Issue by nascentphilosopher** [libre-tube/LibreTube#5292]
### Steps to reproduce

Videos are not responding 

### Expected behavior

Videos should play

### Actual behavior

Videos are not responding 

### LibreTube version

Latest 

### Android version

Android 12 

### Other details

java.lang.RuntimeException: setDataSource failed: status = 0x80000000
	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:310)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:253)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:355)
	at com.github.libretube.util.OfflineTimeFrameReceiver.<init>(SourceFile:18)
	at com.github.libretube.ui.activities.OfflinePlayerActivity$playVideo$1.invokeSuspend(SourceFile:595)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at android.os.Handler.handleCallback(Handler.java:980)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8098)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@86e25d9, Dispatchers.Main.immediate]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5237

& check pinned issues
