### ISSUE TITLE
Downloads don't play in app.   Also can't be used as files.

### ISSUE THREAD

**Issue by Ere-the-Weekend-comes** [libre-tube/LibreTube#5390]
### Steps to reproduce

Pick a video, download it,  Try to play the downloaded file in the app.

### Expected behavior

Should create a playable file, or should be playable in the app. 

### Actual behavior

 doesn't seem to create a usable file for video or audio.  In Android 13 attempting to play the downloaded file (right MB but not playable in WIndows either) throws a debug popup with the following contents:

java.lang.RuntimeException: setDataSource failed: status = 0x80000000
	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:313)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:254)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:359)
	at com.github.libretube.util.OfflineTimeFrameReceiver.<init>(SourceFile:18)
	at com.github.libretube.ui.activities.OfflinePlayerActivity$playVideo$1.invokeSuspend(SourceFile:595)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@66736a3, Dispatchers.Main.immediate]
    
On Android 12 phone, attempting to play a downloaded vid file (which shows a thumbnail in Libretube downloads list, but is not playable anywhere), where the audio didn't download correctly (this seems to be the meat of the issue though there is no bug report for downloads that just won't finish properly) gives the following debug output:

java.lang.NullPointerException
	at com.github.libretube.services.OfflinePlayerService$onStartCommand$1.invokeSuspend(SourceFile:42)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5694aee, Dispatchers.IO]

### LibreTube version

0.20.1

### Android version

Android 12 and Android 13 Samsung One UI 5.1

### Other details

I have also had problems lately updating f droid repos.  I also see other issues with phone.  Could be hacked or malware.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ere-the-Weekend-comes** [comment]
ADDITIONALLY, IT doesn't play a seemingly downloaded video (which also can't be played on Windows or converted though it does have a thumbnail in the app and is 50 or so mb as it should) on the Android 12 phone with the following debug report:

java.lang.NullPointerException
	at com.github.libretube.services.OfflinePlayerService$onStartCommand$1.invokeSuspend(SourceFile:42)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5694aee, Dispatchers.IO]

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5237
