### ISSUE TITLE
Crash on download menu

### ISSUE THREAD

**Issue by FlingCarnationProposal** [libre-tube/LibreTube#5408]
### Steps to reproduce

**Video selection:**
1. Long press on any video.
2. Press download.

**Video player screen:**
1. Press download.

### Expected behavior

The menu pops up, where I can select formats for the video and proceed with downloading it.

### Actual behavior

The menu pops up for a split second, then the app suddenly closes. Upon next launch, the app presents the following error:
```
java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
	at java.util.ArrayList.get(ArrayList.java:437)
	at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:397)
	at com.github.libretube.ui.views.DropdownMenu.setSelectedItemPosition(SourceFile:11)
	at com.github.libretube.ui.dialogs.DownloadDialog$fetchAvailableSources$1.invokeSuspend(SourceFile:740)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:115)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d56a8b4, Dispatchers.Main.immediate]
    
```

### LibreTube version

0.21.0

### Android version

Android 10

### Other details

Tried it with 3 different instances:
1. adminforge.de
2. privacydev.net
3. projectsegfau.lt us

Using piped proxy. Not logged in to piped. Codecs: all. Resolution is auto.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Same problem here
