### ISSUE TITLE
Creating backup fatal crash app

### ISSUE THREAD

**Issue by BurningProcessor** [libre-tube/LibreTube#5409]
### Steps to reproduce

When I create backup app crush

### Expected behavior

Backup created

### Actual behavior

Fatal crash app

### LibreTube version

0.21

### Android version

Lineage OS 20 (Android 13)

### Other details

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT typ=application/json (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2200)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1839)
	at android.app.Activity.startActivityForResult(Activity.java:5507)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(SourceFile:1)
	at androidx.activity.ComponentActivity$1.onLaunch(SourceFile:309)
	at androidx.fragment.app.Fragment$10.launch(SourceFile:108)
	at androidx.fragment.app.Fragment$10.launch(SourceFile:156)
	at com.github.libretube.ui.preferences.BackupRestoreSettings.onCreatePreferences$lambda$18(SourceFile:75)
	at com.github.libretube.ui.preferences.BackupRestoreSettings.$r8$lambda$MWOsRb4Pw8gdLGBsHFlsUCNbxRQ(SourceFile:1)
	at com.github.libretube.ui.preferences.BackupRestoreSettings$$ExternalSyntheticLambda0.onFragmentResult(SourceFile:1)
	at androidx.fragment.app.FragmentManager$LifecycleAwareResultListener.onFragmentResult(SourceFile:3)
	at coil.util.-Lifecycles.setFragmentResult(SourceFile:34)
	at com.github.libretube.ui.dialogs.BackupDialog$onCreateDialog$2$1$1.invokeSuspend(SourceFile:148)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:115)
	at androidx.work.Worker$2.run(SourceFile:136)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@746bf20, Dispatchers.IO]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That looks like you disabled/uninstalled the system file picker and hence is out of scope.

**Comment by BurningProcessor** [comment]
Yes, indeed, I had the Storage Access Framework cut out of the firmware. In this case, Toast appears in the "NewPipe" or "Material Files" applications with the message "No application found for this"
