### ISSUE TITLE
App crashes when download options appear

### ISSUE THREAD

**Issue by Brokoli5191** [libre-tube/LibreTube#5432]
### Steps to reproduce

1. Try to download a video
2. See LibreTube crashing ~1 sec after the download options appear

### Expected behavior

LibreTube should Not Crash when the download options appear

### Actual behavior

LibreTube crashes after the download options appear. Then after reopening the app an error is displayed.

### LibreTube version

0.21.0

### Android version

12

### Other details

Device: Samsung galaxy a12
the error message: java.lang.IndexOutOfBoundsException: Index: 12, Size: 8
	at java.util.ArrayList.get(ArrayList.java:437)
	at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:394)
	at com.github.libretube.ui.views.DropdownMenu.setSelectedItemPosition(SourceFile:11)
	at com.github.libretube.ui.dialogs.DownloadDialog$fetchAvailableSources$1.invokeSuspend(SourceFile:740)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:115)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@992a6d8, Dispatchers.Main.immediate]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5408
