### ISSUE TITLE
App crashes if track completes while phone is locked

### ISSUE THREAD

**Issue by matkoniecz** [libre-tube/LibreTube#5612]
### Steps to reproduce

start playlist

play video

skip to nearly end

lock phone (note `Can not perform this action after onSaveInstanceState` in crash log, this seems actually related)

wait for track ending

unlock phone, go to app

### Expected behavior

app does not crash, next track is played

### Actual behavior

app crashes with 

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.enqueueAction(SourceFile:38)
	at androidx.fragment.app.BackStackRecord.commitInternal(SourceFile:70)
	at androidx.fragment.app.DialogFragment.dismissInternal(SourceFile:116)
	at androidx.fragment.app.DialogFragment.dismiss(SourceFile:2)
	at com.google.android.material.bottomsheet.BottomSheetDialogFragment.dismiss(SourceFile:15)
	at androidx.activity.OnBackPressedDispatcher$addCallback$1.invoke(SourceFile:1)
	at androidx.activity.OnBackPressedDispatcher$addCallback$1.invoke(SourceFile:11)
	at com.github.libretube.ui.fragments.PlayerFragment.playNextVideo(SourceFile:81)
	at com.github.libretube.ui.views.CustomExoPlayerView$initialize$3.onPlaybackStateChanged(SourceFile:245)
	at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda5.invoke(SourceFile:12)
	at androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda1.run(SourceFile:178)
	at androidx.media3.common.util.ListenerSet.flushEvents(SourceFile:104)
	at androidx.media3.exoplayer.ExoPlayerImpl.updatePlaybackInfo(SourceFile:108)
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(SourceFile:963)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

### LibreTube version

0.21.1 from F-droid

### Android version

10

### Other details

may be similar to #5584

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The crash log indicates that a bottom sheet has been open while the crash happened. It would be good for me to know which one to be able to reproduce the issue.

**Comment by matkoniecz** [comment]
> bottom sheet has been open

which part of interface it is? Would it be enough to publish screenshot before locking phone?
