### ISSUE TITLE
DeadSystemRuntimeException after using the app a while

### ISSUE THREAD

**Issue by SarthakDhiman96** [libre-tube/LibreTube#5632]
### Steps to reproduce

This error msg pops in general:

android.os.DeadSystemRuntimeException: android.os.DeadSystemException
	at android.app.ActivityClient.activityStopped(ActivityClient.java:99)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:135)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.os.DeadSystemException
	... 10 more
    

### Expected behavior

Smooth Operational UI

### Actual behavior

1. Gittery UI
2. Sudden Crash (Though Rare)
[else not much]

### LibreTube version

Version 0.21.1

### Android version

Android 14

### Other details

**### Error Message Log: ###**

android.os.DeadSystemRuntimeException: android.os.DeadSystemException
	at android.app.ActivityClient.activityStopped(ActivityClient.java:99)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:135)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.os.DeadSystemException
	... 10 more
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's apparently an Android and not an app issue, see https://ao.chatoyer.de/questions/42784731/android-deadsystemexception#44395215.
