### ISSUE TITLE
Crash when exporting subscriptions

### ISSUE THREAD

**Issue by git10700** [libre-tube/LibreTube#5732]
### Steps to reproduce

1. Open LibreTube.
2. Click on the three points on top of each other.
3. Click on Settings.
4. Click on Backup & restore.
5. Click on Export subscriptions.
6. Choose NewPipe, then click OK.
7. Choose Downloads folder
8. Click SAVE.

### Expected behavior

It should export to the Downloads folder.

### Actual behavior

The app crashed.

### LibreTube version

0.21.1

### Android version

Android 13

### Other details
Crash Log
```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 13602: Expected string literal but 'null' literal was found at path: $[51].avatar
Use 'coerceInputValues = true' in 'Json {}' builder to coerce nulls to default values.
JSON input: ....."name":"folder docs","avatar":null,"verified":true},{"url":".....
 at okio.Utf8.JsonDecodingException(SourceFile:1)
 at okio.Utf8.JsonDecodingException(SourceFile:2)
 at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(SourceFile:52)
 at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(SourceFile:36)
 at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(SourceFile:6)
 at kotlinx.serialization.json.internal.StringJsonLexer.consumeKeyString(SourceFile:3)
 at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeString(SourceFile:20)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(SourceFile:14)
 at okio.OkioOkioKt.decodeStringElement(SourceFile:6)
 at com.github.libretube.api.obj.Subscription$$serializer.deserialize(SourceFile:1)
 at com.github.libretube.api.obj.Subscription$$serializer.deserialize(SourceFile:2)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:104)
 at okio.OkioOkioKt.decodeSerializableElement(SourceFile:11)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:50)
 at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(SourceFile:8)
 at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(SourceFile:38)
 at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(SourceFile:6)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:104)
 at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
 at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
 at retrofit2.OkHttpCall.parseResponse(SourceFile:56)
 at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
 at androidx.appcompat.app.TwilightManager.onSuccess(SourceFile:33)
 at androidx.work.Worker$2.run(SourceFile:220)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@61101fe, Dispatchers.IO]
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's strange, I didn't know it's possible that YouTube channels don't have an avatar :shrug:
