### ISSUE TITLE
Crash dump

### ISSUE THREAD

**Issue by olsonperrensen** [libre-tube/LibreTube#5770]
### Steps to reproduce

Unknown steps to reproduce
 

Crash log: 

android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{bf6fe87 u11 com.github.libretube.debug/com.github.libretube.services.OnlinePlayerService c:com.github.libretube.debug}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2211)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2182)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2477)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:894)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1985)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1939)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:831)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:831)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1189)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:752)
	at com.github.libretube.helpers.BackgroundHelper.playOnBackground(BackgroundHelper.kt:47)
	at com.github.libretube.helpers.BackgroundHelper.playOnBackground$default(BackgroundHelper.kt:24)
	at com.github.libretube.helpers.NavigationHelper.navigateVideo(NavigationHelper.kt:62)
	at com.github.libretube.helpers.NavigationHelper.navigateVideo$default(NavigationHelper.kt:49)
	at com.github.libretube.ui.adapters.SearchResultsAdapter.bindVideo$lambda$7$lambda$3(SearchResultsAdapter.kt:100)
	at com.github.libretube.ui.adapters.SearchResultsAdapter.$r8$lambda$bPthpmxEcfMFlfAV_848idC54ZE(Unknown Source:0)
	at com.github.libretube.ui.adapters.SearchResultsAdapter$$ExternalSyntheticLambda5.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7729)
	at android.view.View.performClickInternal(View.java:7706)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30484)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	... 6 more
    

### Expected behavior

Working app

### Actual behavior

Crash

### LibreTube version

0.21.1

### Android version

14

### Other details

android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{bf6fe87 u11 com.github.libretube.debug/com.github.libretube.services.OnlinePlayerService c:com.github.libretube.debug}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2211)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2182)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2477)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:894)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1985)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1939)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:831)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:831)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1189)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:752)
	at com.github.libretube.helpers.BackgroundHelper.playOnBackground(BackgroundHelper.kt:47)
	at com.github.libretube.helpers.BackgroundHelper.playOnBackground$default(BackgroundHelper.kt:24)
	at com.github.libretube.helpers.NavigationHelper.navigateVideo(NavigationHelper.kt:62)
	at com.github.libretube.helpers.NavigationHelper.navigateVideo$default(NavigationHelper.kt:49)
	at com.github.libretube.ui.adapters.SearchResultsAdapter.bindVideo$lambda$7$lambda$3(SearchResultsAdapter.kt:100)
	at com.github.libretube.ui.adapters.SearchResultsAdapter.$r8$lambda$bPthpmxEcfMFlfAV_848idC54ZE(Unknown Source:0)
	at com.github.libretube.ui.adapters.SearchResultsAdapter$$ExternalSyntheticLambda5.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7729)
	at android.view.View.performClickInternal(View.java:7706)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30484)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	... 6 more
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please create a new issue if you have a consistent way to reproduce this, the crash logs are not helpful in that case.
