### ISSUE TITLE
the app force stop while using it

### ISSUE THREAD

**Issue by Ammar-A7med** [libre-tube/LibreTube#5786]
### Steps to reproduce

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment.killPlayerFragment(SourceFile:33)
	at androidx.activity.OnBackPressedDispatcher$addCallback$1.invoke(SourceFile:3)
	at androidx.activity.OnBackPressedDispatcher$addCallback$1.invoke(SourceFile:12)
	at androidx.work.CoroutineWorker$$ExternalSyntheticLambda0.run(SourceFile:164)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1116)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:562)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1242)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1484)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1063)
	at android.view.Choreographer.doCallbacks(Choreographer.java:889)
	at android.view.Choreographer.doFrame(Choreographer.java:812)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1050)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7830)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
    

### Expected behavior

work smooth 

### Actual behavior

work as shit

### LibreTube version

0.21.1

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Outdated version.
