### ISSUE TITLE
Video not playing in DASH format

### ISSUE THREAD

**Issue by VitoItalianGamer** [libre-tube/LibreTube#5855]
### Steps to reproduce

1.Watch a video by searching or whatever
2.the video remains black and no sound

### Expected behavior

The video plays like normal

### Actual behavior

The video remains black and plays only in HLS

### LibreTube version

0.22.2

### Android version

Android 12

### Other details

Was it of next DNS or libretube itself

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ngn13** [comment]
To fix 1002 errors Piped project disabled ump with this commit: https://github.com/TeamPiped/Piped-Backend/commit/d5572d70a77ca6db1d0381bd506ae85cf8047468

Which breaks DASH for some reason

**Comment by VitoItalianGamer** [comment]
Can you guys fix this issue?

**Comment by Not-A-Coder2023** [comment]
This happened to me just recently

**Comment by consoleaf** [comment]
> This happened to me just recently

Try disabling DASH in settings. Worked for me, probably will for you as well

**Comment by anoo2niem** [comment]
For those using libretube with a selfhosted piped server with docker, where switching to HLS doesn't seem to work and where the backend got updated recently by watchtower;

1337kavin/piped@sha256:afa51dbe3089686e42e894a405dabf7cc6f649b739c4f801c766153bf7a96a3c is the image with digestID just before the update that disabled UMP and breaks DASH as mentioned by @ngn13.

Currently using this image, back up and running,  till the issue git fixed.

**Comment by Vartroc** [comment]
Comments don't work for me as well. When I click on "Comments" I just get a Blanc screen

**Comment by 0x24D** [comment]
Debug log shows the issue comes from ExoPlayer:
```
playerFailed [eventTime=2.76, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_IO_READ_POSITION_OUT_OF_RANGE
                   androidx.media3.exoplayer.ExoPlaybackException: Source error
                       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:713)
                       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:685)
                       at android.os.Handler.dispatchMessage(Handler.java:102)
                       at android.os.Looper.loopOnce(Looper.java:201)
                       at android.os.Looper.loop(Looper.java:288)
                       at android.os.HandlerThread.run(HandlerThread.java:67)
                   Caused by: androidx.media3.datasource.cronet.CronetDataSource$OpenException
                       at androidx.media3.datasource.cronet.CronetDataSource.skipFully(CronetDataSource.java:928)
                       at androidx.media3.datasource.cronet.CronetDataSource.open(CronetDataSource.java:676)
                       at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
                       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
                       at androidx.media3.exoplayer.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:129)
                       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                       at java.lang.Thread.run(Thread.java:1012)
                 ]
```

The DASH manifest created using `PlayerHelper::createDashSource` works fine using other video player, including Piped (shaka-player).

**Comment by VitoItalianGamer** [comment]
I'm using hls and the auto generated captions don't appear.

**Comment by CarlosRuiz-globalqss** [comment]
> I'm using hls and the auto generated captions don't appear.

same here - DASH is not working, and HLS is slow and without automatic subtitles

**Comment by Bnyro** [comment]
I am getting
```
Caused by: androidx.media3.common.ParserException: Invalid integer size: 8101{contentIsMalformed=true, dataType=1}
                                                                                                          at androidx.media3.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:121)
                                                                                                          at androidx.media3.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:514)
                                                                                                          at androidx.media3.exoplayer.source.chunk.BundledChunkExtractor.read(BundledChunkExtractor.java:149)
                                                                                                          at androidx.media3.exoplayer.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:129)
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                          at java.lang.Thread.run(Thread.java:1012)
```

I've logged and compared requests from Piped and LibreTube at the proxy's side, and they're pretty much identical. So I suspect that when disabling ump, YouTube's video format is different and thus no longer compatible with the ExoPlayer, while Shaka does handle things differently at the Piped frontend on the web.

**Comment by ARR552** [comment]
> > This happened to me just recently
> 
> Try disabling DASH in settings. Worked for me, probably will for you as well

This worked for me as well but only for the video. However It is still failing in audio mode...

**Comment by Ehab-d** [comment]
> This worked for me as well but only for the video. It is still failing in audio mode...

The audio player did not respect the Use HLS setting and always used DASH. This issue was resolved in #5862. The audio player did not respect the Use HLS setting and always used DASH. This issue was resolved in #5862. You can expect it to be resolved in the next release or try the [nightly builds](https://github.com/libre-tube/NightlyBuilds).

**Comment by VitoItalianGamer** [comment]
How do I enable UMP in libretube?

**Comment by aviallon** [comment]
Would implementing an MPV player fix the issue?
MPV can play almost every thing, after all.
I know Findroid (native Android client for Jellyfin) had a very good MPV player integration that just works when enabled.

**Comment by VitoItalianGamer** [comment]
I got Findroid how do I add a server to it?

**Comment by sonisaltiner** [comment]
Greetings. Is there a problem with entity? Occasionally entitys starting with the prefix Kavin disappear. If I select any other occurrence, there are problems, some things stay loading.

**Comment by Moonstone3010** [comment]
Hi,
I've been having the same problem for (I think) a few weeks now. No video is playing, it shows the message: source error. This is independent of the instance. Piped in the browser works on the same device.
A workaround for this problem is to disable the piped proxy. When videos are sucked directly from YT everything works.
The second solution is to enable HLS instead of DASH, but - as someone wrote above - in version 0.22.2 this does not work in audio-only mode.

**Comment by sonisaltiner** [comment]
@Moonstone3010 Thank you for your reply. Solution 2 seems to work. Solution 1 causes a different problem. The videos open but do not play. I hope you are working on these issues.

**Comment by Bnyro** [comment]
Please ONLY comment here if you have useful information on how to solve the issue at LibreTube's or Piped proxy's side.

It's not helpful to say that the issue exists for you too - everybody has the same issue...

**Comment by aviallon** [comment]
@Bnyro could something like an automatic fallback be implemented?

Also, I think trying to use MPV as the player might help there, although it would probably be a major pita to add.

**Comment by 0xrxL** [comment]
> @Bnyro could something like an automatic fallback be implemented?
> 
> Also, I think trying to use MPV as the player might help there, although it would probably be a major pita to add.

Yeah...at this point I think that too. Maybe the current player implementation lack of some codec, useful to correctly decode the video stream.

**Comment by 0xrxL** [comment]
UPDATE: DASH working again on [this](https://github.com/libre-tube/LibreTube/actions/runs/9085428494) debug build, I can even watch the age restricted videos (with a specific piped instance, obviously), but there's no specifically merged code related to it.

What happened? 🤔🤷‍♂️

**Comment by Bnyro** [comment]
> UPDATE: seems DASH working again on [this](https://github.com/libre-tube/LibreTube/actions/runs/9085428494) debug build, I can even watch the age restricted videos (with a custom piped instance, obviously), but there's no specifically merged code related to it.
> 
> What happened? 🤔🤷‍♂️
>
You certainly disabled the proxy ...

**Comment by 0xrxL** [comment]
> > UPDATE: seems DASH working again on [this](https://github.com/libre-tube/LibreTube/actions/runs/9085428494) debug build, I can even watch the age restricted videos (with a custom piped instance, obviously), but there's no specifically merged code related to it.
> > What happened? 🤔🤷‍♂️
> 
> You certainly disabled the proxy ...

I checked it, and it's disabled. But I wasn't able to make restricted video working on current stable version (also with proxy disabled).

So I wondered if there was a fix (or fixes) merged recently.

**Comment by Bnyro** [comment]
No ...

**Comment by Pamilg8** [comment]
The YouTube app uses the Android Testsuite or the iOS YouTube API instead of the default Android YouTube API for video player requests. But how can the problem be solved? Maybe in NewPipe Extractor

**Comment by mckellenjaundice122** [comment]
Ever since December I haven't been able to use the app at all, nothing has changed, it's just as broken even with all the default settings. Only way I can get anything to play is to disable the piped proxy, the hls setting does absolutely nothing whether off or on for me

**Comment by Pamilg8** [comment]
> Ever since December I haven't been able to use the app at all, nothing has changed, it's just as broken even with all the default settings. Only way I can get anything to play is to disable the piped proxy, the hls setting does absolutely nothing whether off or on for me

YouTube blocks LibreTube and servers are sometimes down (initial player not response). It seems that the ipv6 rotator is not implemented. YouTube proxy is not reliable. NewPipe is more stable

**Comment by VitoItalianGamer** [comment]
I'll install New Pipe until LibreTube fixes the DASH problem

**Comment by BatDevil** [comment]
i have the same issue here

**Comment by BatDevil** [comment]
i have the same issue here but for specific channels like Ohara, Joseph Blaze and TheAvatarist.

**Comment by VitoItalianGamer** [comment]
Ok

**Comment by VitoItalianGamer** [comment]
But there is no auto generated captions.

**Comment by Not-A-Coder2023** [comment]
unrelated but apparently adding a channel to a group crashes libretube debug

**Comment by alejandro-alzate** [comment]
> Which breaks DASH **_for some reason_**

Pinnacle of subtle software quirks.

**Comment by GlytchMeister** [comment]
Up until a few minutes ago, I have been able to play DASH on at least one instance.  But now, every instance is either unable to play DASH or is returning "sign in to confirm you're not a not" errors.

HLS, as mentioned in the setting to use it over DASH, is QUITE slow... and there is a limit to how far the video will buffer. Once it hits that limit, it won't buffer any more, even if I begin playing the video.  I have to change the resolution to clear the played buffer once I reach the end of the buffer so the video can buffer the next 30 seconds or so of the video.

This is an awful lot of hoops to jump through to watch a video, even at just 480p.

**Comment by ngn13** [comment]
> I know a previous comment said not to comment just to say one is experiencing this problem as well, but I feel like something has happened recently; Up until a few minutes ago, I have been able to play DASH on at least one instance.

The instance you were using was probably running an older version of Piped, with [this commit](https://github.com/TeamPiped/Piped-Backend/commit/d5572d70a77ca6db1d0381bd506ae85cf8047468) Piped disabled ump, which breaks DASH

> But now, every instance is either unable to play DASH or is returning "sign in to confirm you're not a not" errors.

The "sign in" error you are getting is not related to HLS or DASH, [please see this issue](https://github.com/TeamPiped/Piped/issues/3658).

**Comment by Bnyro** [comment]
Piped should work again after https://github.com/TeamPiped/piped-proxy/pull/370 if you use a private instance.

However, the recommended way to use LibreTube is to use "full local mode" anyways and not use Piped since Piped is no longer actively maintained.
