### ISSUE TITLE
Switch to audio then back to video crash

### ISSUE THREAD

**Issue by gsdgethjfjj** [libre-tube/LibreTube#5958]
### Steps to reproduce

Open a video, turn on audio mode, turn on video mode again

### Expected behavior

App isn't crashing

### Actual behavior

App is crashing

### LibreTube version

0.23.0

### Android version

Android 14

### Other details

java.lang.RuntimeException: Unable to stop service com.github.libretube.services.OnlinePlayerService@b6752b0: java.lang.IllegalArgumentException: Receiver not registered: androidx.media3.common.util.NetworkTypeObserver$Receiver@a500529
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5111)
	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2405)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: androidx.media3.common.util.NetworkTypeObserver$Receiver@a500529
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1670)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1905)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:821)
	at com.github.libretube.services.OnlinePlayerService.onDestroy(SourceFile:34)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5091)
	... 11 more
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TechnoSparks** [comment]
On 0.22.2 this bug is not present

**Comment by M00NJ** [comment]
I can reproduce this. v0.23.0, Android 14 (GOS)

**Comment by xlash123** [comment]
I am able to reproduce this consistently by selecting play in background and then pressing the X on the mini player. I don't even have to switch to video.

**Comment by github-user93** [comment]
can confirm. using android 13, can reproduce the issue on 0.23.0

**Comment by DanielProg39** [comment]
I also encountered this error:

```
java.lang.RuntimeException: Unable to stop service com.github.libretube.services.OnlinePlayerService@218a77b: java.lang.IllegalArgumentException: Receiver not registered: com.github.libretube.services.OnlinePlayerService$playerActionReceiver$1@ba8f998
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4706)
	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.github.libretube.services.OnlinePlayerService$playerActionReceiver$1@ba8f998
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1662)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1836)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:812)
	at com.github.libretube.services.OnlinePlayerService.onDestroy(OnlinePlayerService.kt:435)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4686)
	... 9 more
    
```

**Comment by kazekawa2** [comment]
I also encounter this error
java.lang.RuntimeException: Unable to stop service com.github.libretube.services.OnlinePlayerService@589563c: java.lang.IllegalArgumentException: Receiver not registered: androidx.media3.common.util.NetworkTypeObserver$Receiver@2282fc5
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5345)
	at android.app.ActivityThread.access$2400(ActivityThread.java:324)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8855)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: androidx.media3.common.util.NetworkTypeObserver$Receiver@2282fc5
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1656)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1867)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:788)
	at com.github.libretube.services.OnlinePlayerService.onDestroy(SourceFile:34)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5325)
	... 9 more
