### ISSUE TITLE
LibreTube crashed when opening

### ISSUE THREAD

**Issue by ninosandzak** [libre-tube/LibreTube#5972]
### Steps to reproduce

1. Open LibreTube
2. Crash

### Expected behavior

LibreTube should start normally

### Actual behavior

When I click on LibreTube, the error message appears immediately and LibreTube is closed

### LibreTube version

0.23.0

### Android version

Android 11

### Other details

FATAL EXCEPTION: OkHttp Dispatcher
Process: com.github.libretube, PID: 8418
java.lang.IllegalArgumentException: Unexpected char 0xfffd at 30 in x-title value: Wir vertikutieren den Rasen, s�en und d�ngen
	at okhttp3.Headers$Companion.checkValue(SourceFile:87)
	at okhttp3.Headers$Builder.add(SourceFile:14)
	at com.google.net.cronet.okhttptransport.ResponseConverter.toResponse(SourceFile:379)
	at com.google.net.cronet.okhttptransport.CronetInterceptor.intercept(SourceFile:52)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:126)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:97)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

https://github.com/libre-tube/LibreTube/assets/68593004/1a82bbe1-0c8e-4626-abe5-709c8e20062d

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/5943
