### ISSUE TITLE
LibreTube v0.23.1 crashing A14

### ISSUE THREAD

**Issue by aryaoffixial** [libre-tube/LibreTube#6003]
### Steps to reproduce

Open LibreTube v0.23.1 loading normally.
Play video from home screen or search any if you want.
Open the video to play, it buffers 0-2 seconds but then crashes immediately

### Expected behavior

It shouldn't crash, i tried changin piped proxy on/off but same issue both time. Tried disable VPN DNS as well.

### Actual behavior

Crashing after clicking for playing videos

### LibreTube version

0.23.1

### Android version

Android 14, HyperOS 1.0.3.0

### LOGS

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.postDelayed(java.lang.Runnable, long)' on a null object reference
	at com.github.libretube.ui.views.OnlinePlayerView.syncQueueButtons(SourceFile:95)
	at com.github.libretube.ui.fragments.PlayerFragment$playVideo$1.invokeSuspend(SourceFile:604)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:115)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@87a2f2c, Dispatchers.Main]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Unaiperezdiaz** [comment]
Crash on Realme master edition Android 13
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.postDelayed(java.lang.Runnable, long)' on a null object reference
	at com.github.libretube.ui.views.OnlinePlayerView.syncQueueButtons(SourceFile:95)
	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(SourceFile:86)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8423)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
    https://github.com/libre-tube/LibreTube/assets/49728036/5546ffd4-a1f9-43f3-983b-c8382387688b

**Comment by alejandro-alzate** [comment]
lemme reference on yours #6004
