### ISSUE TITLE
Crash report 

### ISSUE THREAD

**Issue by nascentphilosopher** [libre-tube/LibreTube#6014]
### Steps to reproduce

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.postDelayed(java.lang.Runnable, long)' on a null object reference
	at com.github.libretube.ui.views.OnlinePlayerView.syncQueueButtons(SourceFile:95)
	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(SourceFile:86)
	at android.os.Handler.handleCallback(Handler.java:980)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8098)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
    

### Expected behavior

Frequently crashing 

### Actual behavior

Should not crash

### LibreTube version

0.23.1

### Android version

Android 12 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Update to latest version
