### ISSUE TITLE
Crashes when playing a video in a playlist

### ISSUE THREAD

**Issue by gloriouspuffy** [libre-tube/LibreTube#6023]
### Steps to reproduce

1. Open a playlist
2. Click on a video before the thumbnail loads

### Expected behavior

Video loads without any problems

### Actual behavior

Libretube crashes returning this in next launch

> java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.github.libretube.util.PlayingQueue.currentIndex(SourceFile:16)
	at com.github.libretube.util.PlayingQueue.getPrev(SourceFile:8)
	at com.github.libretube.ui.views.OnlinePlayerView.syncQueueButtons(SourceFile:30)
	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(SourceFile:86)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    

### LibreTube version

0.23.2

### Android version

Android 13, Superior OS, Redmi 9(cattail)

### Other details

I've noticed that this issue doesn't occur if I search for the video since thumbnail loads almost instantly but the thumbnail won't load in playlist(could be because it has 1k+ videos) and crashes if i play it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by User8388493929** [comment]
Can reproduce on a nightly build, although I'm unsure if it's actually related to thumbnails.

https://github.com/libre-tube/LibreTube/assets/166151037/e7faa9c6-3d66-43b8-8aeb-d5ea9928830c

**Comment by User8388493929** [comment]
Can reproduce on a nightly build, although I'm unsure if it's actually related to thumbnails.


Uploading screenrecord-libretube.mp4…

**Comment by User8388493929** [comment]
Can reproduce on a nightly build, although I'm unsure if it's actually related to thumbnails.

https://github.com/libre-tube/LibreTube/assets/166151037/ccd06d05-1ad6-4531-a120-1af78bab14d3

**Comment by gloriouspuffy** [comment]
> Can reproduce on a nightly build, although I'm unsure if it's actually related to thumbnails.
> screenrecord-libretube.mp4

I meant user made playlist in library
