### ISSUE TITLE
Pausing a video in picture-in-picture mode crashes LibreTube

### ISSUE THREAD

**Issue by omentic** [libre-tube/LibreTube#6078]
### Steps to reproduce

1. Begin playing a video in LibreTube
2. Press the home button to enter picture-in-picture mode.
3. Press the pause button on the picture-in-picture popup.

### Expected behavior

LibreTube should not crash.

### Actual behavior

LibreTube crashes. This is reproducible.

### LibreTube version

0.23.2

### Android version

13

### Other details

```java
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.github.libretube.media_control flg=0x10 pkg=com.github.libretube (has extras) } in androidx.media3.common.util.NetworkTypeObserver$Receiver@a4e9200
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.BadParcelableException: Parcelable encountered IOException reading a Serializable object (name = com.github.libretube.enums.PlayerEvent)
	at android.os.Parcel.readSerializableInternal(Parcel.java:5131)
	at android.os.Parcel.readValue(Parcel.java:4659)
	at android.os.Parcel.readValue(Parcel.java:4367)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4465)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4424)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:396)
	at android.os.BaseBundle.getValue(BaseBundle.java:376)
	at android.os.BaseBundle.getValue(BaseBundle.java:359)
	at android.os.BaseBundle.getValue(BaseBundle.java:352)
	at android.os.BaseBundle.getSerializable(BaseBundle.java:1453)
	at android.os.Bundle.getSerializable(Bundle.java:1171)
	at androidx.transition.Scene.getSerializable(SourceFile:16)
	at androidx.media3.common.util.NetworkTypeObserver$Receiver.onReceive(SourceFile:34)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
	... 11 more
Caused by: java.io.InvalidObjectException: enum constant Pause does not exist in class com.github.libretube.enums.PlayerEvent
	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1872)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1437)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:428)
	at android.os.Parcel.readSerializableInternal(Parcel.java:5118)
	... 25 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.github.libretube.enums.PlayerEvent.Pause
	at java.lang.Enum.valueOf(Enum.java:259)
	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1869)
	... 28 more
    ```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please try to reboot and/or freshly reinstall the app. It seems like your app is trying to use old broadcasts from the old version even though they no longer exist, apparently there's some issue with some Android versions when updating apps that do changes to their broadcasts.

I've had similar issues some time ago, and a reinstall fixed it for me. Same applies for your other issue.

**Comment by omentic** [comment]
Rebooting fixed it! Thanks :+1:

**Comment by Bnyro** [comment]
Awesome, you're welcome :+1:
