### ISSUE TITLE
App Crashes When Refreshing Channel Page or Toggling Search Bar

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#6106]
### Steps to reproduce

1. Open channel page
2. Refresh the page or open and close the search bar

### Expected behavior

The list of videos should refresh and the search bar should close, returning to the channel page.

### Actual behavior

The app crashes.

### LibreTube version

LibreTube Debug, commit 854723e

### Android version

Android 13

### Other details

I have also been able to reproduce #6103, which I suspect is part of the same problem. However, in all cases (whether those I have described above or from #6103) I get the same error, which is different from those in #6103.

Error:

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
 at java.util.ArrayList.set(ArrayList.java:453)
 at com.github.libretube.ui.fragments.ChannelFragment$fetchChannel$1.invokeSuspend(ChannelFragment.kt:243)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7924)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cfc93d7, Dispatchers.Main.immediate]
```

Recordings:

https://github.com/libre-tube/LibreTube/assets/63293432/c6403d54-5e77-4437-a2bd-79871db31a25

https://github.com/libre-tube/LibreTube/assets/63293432/9cd71b5e-2b3e-4fa5-8ae1-0499cab19263

https://github.com/libre-tube/LibreTube/assets/63293432/7bd64718-c462-4341-ae43-ca32359f1ba7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by DanielProg39** [comment]
I also just got this error in a new way. When watching the video, I opened a channel of origin of one of the recommended videos, then when closing the channel page, the app crashed. Couldn't reproduce it though.
