### ISSUE TITLE
Release 0.24.0 (PLEASE TEST!)

### ISSUE THREAD

**Issue by Bnyro** [libre-tube/LibreTube#6134]
## Beta-Testers searched for upcoming 0.24.0 release

The app is on a feature freeze now until the next release, so it's important to test it to avoid any major bugs and the necessity of hotfix releases.

Please test the app builds from https://github.com/libre-tube/NightlyBuilds and report any regressions here or in a new issue.

Thank you!

### New features
* feat: download popup that can be displayed over other apps by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6034
* feat: changed chips in channels to swipable tabs by @amandeepsinghjamwal in https://github.com/libre-tube/LibreTube/pull/6026 and https://github.com/libre-tube/LibreTube/pull/6053
* feat: support for external download apps by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6084
* feat: minor channel page header redesign by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6123
* feat: remember selected channel group across app restarts by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6132

### Bug fixes
* fix: button to play previous video doesnt work when repeat enabled by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6035
* fix: chapters dont work in audio mode by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6055
* fix: clear notification when app is killed from recent tasks.  by @nur-shuvo in https://github.com/libre-tube/LibreTube/pull/6063
* fix: crash when different threads access playing queue by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6083
* fix: crash when refreshing channel page by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6120
* fix: default value in behavior when minimized preference by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6118
* fix: download activity not dismissed when dialog closed by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6054
* fix: explicitely set status bar color after app start by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6080
* fix: navigation bar color when pure theme disabled by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6029
* fix: navigation bar missing nav items after closing player by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6122
* fix: repeat current doesn't work if autoplay disabled by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6032
* fix: search results scroll state not preserved when rotating by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6033
* fix: use correct fragment manager for result callbacks by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6067
* fix: use string resource for channel video tab by @FineFindus in https://github.com/libre-tube/LibreTube/pull/6065
* fix: notification bell shown even though notifications disabled by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6133 
* chore: dont share with time code by default by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6036

**Comment by Pamilg8** [comment]
I can help😇

**Comment by Unaiperezdiaz** [comment]
https://github.com/libre-tube/LibreTube/assets/49728036/10826a6a-13cd-49c5-9b32-e046f4135b8f

I have experienced this error with the notification control, it only happens when I clicked on it to enlarge the window, as shown in the video.
Once it is extended it is not possible to stop it in any way.

**Comment by mizuhashikuniumi** [comment]
Picture on picture bug
java.lang.NullPointerException: null cannot be cast to non-null type com.github.libretube.ui.activities.MainActivity
	at com.github.libretube.ui.fragments.PlayerFragment.getMainActivity(PlayerFragment.kt:173)
	at com.github.libretube.ui.fragments.PlayerFragment.unsetFullscreen(PlayerFragment.kt:695)
	at com.github.libretube.ui.fragments.PlayerFragment$fullscreenDialog$2$1.onBackPressed(PlayerFragment.kt:182)
	at android.app.Dialog.onKeyUp(Dialog.java:673)
	at com.github.libretube.ui.fragments.PlayerFragment$fullscreenDialog$2$1.onKeyUp(PlayerFragment.kt:190)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2866)
	at android.app.Dialog.dispatchKeyEvent(Dialog.java:826)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:390)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5953)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5821)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5316)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5491)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5548)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5524)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5682)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3180)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2722)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2713)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3157)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7662)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by mizuhashikuniumi** [comment]
Here

**Comment by mizuhashikuniumi** [comment]
Uploading screen-20240615-140534.mp4…

**Comment by mizuhashikuniumi** [comment]
https://github.com/libre-tube/LibreTube/assets/24605072/6a6acf3d-52fa-421a-a838-8e80dcb3c6ce

**Comment by gloriouspuffy** [comment]
Add the option to create a new channel group when a adding a channel to a group from channel's page

**Comment by Unaiperezdiaz** [comment]
On some channels I get -1 subscribers on the channel pages, I don't know if it's a bug or an instance problem, if someone can check or reproduce it. Because I'm not sure if it's just my phone or not.

**Comment by Bnyro** [comment]
> On some channels I get -1 subscribers on the channel pages, I don't know if it's a bug or an instance problem, if someone can check or reproduce it. Because I'm not sure if it's just my phone or not.
>
It's a NewPipeExtractor issue, there's an open issue at the NewPipeExtractor repo for it.

**Comment by Unaiperezdiaz** [comment]
![Screenshot_2024-06-21-05-11-35-93_7af1185115278aeb9699bfd161691b7e.jpg](https://github.com/libre-tube/LibreTube/assets/49728036/2f077ad7-b637-4683-b89b-78e048fa1187)
I don't understand why now appears this, it's the first time that I have seen it.😬😵‍💫

**Comment by Unaiperezdiaz** [comment]
![Screenshot_2024-06-21-05-11-35-93_7af1185115278aeb9699bfd161691b7e.jpg](https://github.com/libre-tube/LibreTube/assets/49728036/2f077ad7-b637-4683-b89b-78e048fa1187)
I don't understand why now appears this, it's the first time that I have seen it.😬😵‍💫

(I have already read this: https://github.com/TeamNewPipe/NewPipe/issues/11139), it happens to Libretube and more services)
🫤

**Comment by Pamilg8** [comment]
Notification action buttons don't work in Android 12 either

https://github.com/libre-tube/LibreTube/assets/149590337/459486fc-581a-4f13-b3e3-9e8fcfc4827d

**Comment by pokegamer5547** [comment]
![Screenshot_20240702-082238_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/65234485/e91d55aa-85e7-4e88-9d41-b4e87181ec53)
Sponsorblock submission screen by default enters current time as `00:00` format, but `:`symbol doesnt appear in number view of keyboard, thus we can't enter that symbol manually.

**Comment by julogit** [comment]
Issue #6197 for 0.24.0 also

**Comment by Bnyro** [comment]
As said above,
> report any regressions here
>
not issues that already existed in previous releases.

**Comment by brnwlshubh** [comment]
No videos plays for me on the latest build after selecting several server.

**Comment by Bnyro** [comment]
Thanks for the help everyone, I think we should do in the same way for the next releases :+1:

**Comment by owosoup** [comment]
The download support works flawlessly for Seal :) it opens a dialogue to choose whether I want to use a fast download (opens up dialogue on top of Libre tube and closes it after) or just open the app and download from there.

**Comment by Bnyro** [comment]
Fyi, there's no testing phase for the upcoming release due to the fact that it includes the fix for video playback everybody has been waiting for to make LibreTube usable again with public instances, the release after will get a normal testing phase again if everything goes as expected.
