### ISSUE TITLE
App Crashes When a Video is Marked as Watched

### ISSUE THREAD

**Issue by Repressed8077** [libre-tube/LibreTube#6188]
### Steps to reproduce

1. Open the app after it has been killed by the OS (usually happens after long hours of inactivity)
2. Go to a video you wish to mark as watched
3. After tapping mark as watched the app crashes resulting in the error log attached below

### Expected behavior

The video should be marked as watched without the app crashing

### Actual behavior

The app crashes instantly after tapping mark as watched. However after relaunching and tapping on mark as watched on other videos the app doesn't crash. Also, the video previously marked as watched prior to crashing is marked as watched after relaunching the app.

### LibreTube version

0.23.2

### Android version

Android 13

### Other details

java.lang.NullPointerException
	at androidx.navigation.NavController$restoreStateInternal$1.invoke(SourceFile:48)
	at kotlin.collections.CollectionsKt__MutableCollectionsKt.removeAll(SourceFile:57)
	at com.github.libretube.ui.sheets.VideoOptionsBottomSheet$onCreate$2.invokeSuspend(SourceFile:530)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:115)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8e89427, Dispatchers.Main.immediate]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FineFindus** [comment]
Does the app only crash when marking a video as watched above the new video indicator?
In that case it should be fixed with https://github.com/libre-tube/LibreTube/pull/6142

**Comment by Repressed8077** [comment]
> Does the app only crash when marking a video as watched above the new video indicator? In that case it should be fixed with #6142

Yes

**Comment by Repressed8077** [comment]
https://github.com/libre-tube/LibreTube/assets/173347816/60db6299-b709-4398-9e72-8e492d9a79f2

@FineFindus I tried to mark videos below the new indicator and it seems the app crashes regardless of the video publication date

**Comment by akano12** [comment]
@Repressed8077 did you retest nightly or not yet?

**Comment by Repressed8077** [comment]
> @Repressed8077 did you retest nightly or not yet?

I've tested it and everything works fine
