### ISSUE TITLE
App crash on opening video

### ISSUE THREAD

**Issue by spal54** [libre-tube/LibreTube#6241]
### Steps to reproduce

1. Open a video, sometimes shows "Network error" toast
2. Open another video, app crashes

### Expected behavior

Videos should play normally. 

### Actual behavior

App crashes
Crash log:
`java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
	at java.util.ArrayList$Itr.next(ArrayList.java:982)
	at com.github.libretube.util.PlayingQueue.currentIndex(SourceFile:16)
	at com.github.libretube.util.PlayingQueue.getPrev(SourceFile:8)
	at com.github.libretube.ui.views.OnlinePlayerView.syncQueueButtons(SourceFile:30)
	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(SourceFile:86)
	at android.os.Handler.handleCallback(Handler.java:1000)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:242)
	at android.os.Looper.loop(Looper.java:362)
	at android.app.ActivityThread.main(ActivityThread.java:8448)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)`

### LibreTube version

0.23.1 (f-droid)

### Android version

14

### Other details

I don't know if it's related, but "Use HLS" and "LBRY HLS" settings are on. And also "Disable Piped proxy" is also on, because piped instances are slow and often don't work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's been fixed with 0.24.0
