### ISSUE TITLE
ForegroundServiceDidNotStartInTimeException

### ISSUE THREAD

**Issue by LoHub** [libre-tube/LibreTube#6260]
### Steps to reproduce

Randomly happen when app is bring back in foreground.

### Expected behavior

No exception raise.

### Actual behavior

An exception is raise.

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{cba7328 u0 com.github.libretube/.services.OnlinePlayerService c:com.github.libretube}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2250)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2221)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2527)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1985)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1939)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:832)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:832)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(SourceFile:1)
	at androidx.room.Room.startForegroundService(SourceFile:7)
	at com.github.libretube.helpers.BackupHelper.playOnBackground(SourceFile:124)
	at com.github.libretube.helpers.BackupHelper.playOnBackground$default(SourceFile:34)
	at com.github.libretube.helpers.NavigationHelper.navigateVideo$default(SourceFile:73)
	at com.github.libretube.ui.adapters.VideosAdapter$$ExternalSyntheticLambda0.onClick(SourceFile:47)
	at android.view.View.performClick(View.java:7931)
	at android.view.View.performClickInternal(View.java:7908)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30990)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	... 8 more
```

### LibreTube version

0.24.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
see comment https://github.com/libre-tube/LibreTube/issues/5929#issuecomment-2088501669
