### ISSUE TITLE
Crash While in Background 

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#6326]
### Steps to reproduce

1. Play something
2. Switch to another app for couple of minutes 

### Expected behavior

LT continue playing normally 

### Actual behavior

LT Crash 

### LibreTube version

0.24

### Android version

Android 13

### Other details

`
coil.network.HttpException: lateinit property searchView has not been initialized
	at com.github.libretube.ui.activities.MainActivity.getSearchView(SourceFile:8)
	at com.github.libretube.ui.fragments.SearchSuggestionsFragment$showHistory$1.invokeSuspend(SourceFile:72)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:113)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8cc7012, Dispatchers.Main.immediate]
`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Just a side note, after the app crashed 8n background, i tried opening it again but faced 2-3 additional crashes on startup before libretube actually opened, this was the log i got after opening the app
