### ISSUE TITLE
Bug in video/audio playback

### ISSUE THREAD

**Issue by PLMichelSainz** [libre-tube/LibreTube#6592]
### Steps to reproduce

step 1. Download a video/audio
step 2. Play the video in the background
step 3. Play for 5-10 minutes, then cut off and play another saved video/audio

### Expected behavior

Play for 5-10 minutes, then cut off and play another saved video/audio

### Actual behavior

Play for 5-10 minutes, then cut off and play another saved video/audio

### LibreTube version

0.25.2 (57)

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PLMichelSainz** [comment]
error code.



java.lang.RuntimeException: Unable to create service com.github.libretube.services.OfflinePlayerService: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.github.libretube/.services.OfflinePlayerService
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4925)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2407)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8594)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.github.libretube/.services.OfflinePlayerService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5020)
	at android.os.Parcel.readParcelable(Parcel.java:5002)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3182)
	at android.os.Parcel.createException(Parcel.java:3171)
	at android.os.Parcel.readException(Parcel.java:3154)
	at android.os.Parcel.readException(Parcel.java:3096)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6995)
	at android.app.Service.startForeground(Service.java:776)
	at com.github.libretube.services.OfflinePlayerService.onCreate(SourceFile:56)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4912)
	... 9 more

**Comment by Bnyro** [comment]
Likely a dupicate of https://github.com/libre-tube/LibreTube/issues/5661
