### ISSUE TITLE
Crash when trying to view watch history

### ISSUE THREAD

**Issue by jigglypuff3r** [libre-tube/LibreTube#6657]
### Steps to reproduce

Click on watch history

### Expected behavior

View watch history

### Actual behavior

App crashing - error report:

kotlinx.datetime.DateTimeFormatException: j$.time.format.DateTimeParseException: Text '2024-01-09T16:00:10-08:00' could not be parsed, unparsed text found at index 10
	at kotlinx.datetime.LocalDate$Companion.parse$default(SourceFile:45)
	at kotlin.text.UStringsKt.toLocalDate(SourceFile:8)
	at androidx.transition.Scene.stringToLocalDate(SourceFile:3)
	at com.github.libretube.db.dao.WatchHistoryDao_Impl$11.call(SourceFile:166)
	at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(SourceFile:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4f78dac, Dispatchers.Main.immediate]
Caused by: j$.time.format.DateTimeParseException: Text '2024-01-09T16:00:10-08:00' could not be parsed, unparsed text found at index 10
	at j$.time.format.DateTimeFormatter.e(SourceFile:0)
	at j$.time.format.DateTimeFormatter.parse(Unknown Source:10)
	at j$.time.LocalDate.parse(SourceFile:0)
	at j$.time.LocalDate.parse(Unknown Source:2)
	at kotlinx.datetime.LocalDate$Companion.parse$default(SourceFile:32)
	... 9 more
    

### LibreTube version

0.25.2 (57) (latest)

### Android version

8.1.0

### Other details

Much thanks to everyone working on this app, making the world a better place for all. If I wasn't a poor farmer barely able to support my family, I'd donate to you wonderful people. Jah Bless.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It seems like you're having videos with an invalid date in your watch history, which in theory should not be possible at all unless you imported a manually modified LibreTube backup.

Therefore, I've no idea what the cause of this issue is, mitigating it won't be a problem however.
