### ISSUE TITLE
Crash in livestream IllegalStateException: Slider value(-2.691) must be greater or equal to valueFrom(0.0)

### ISSUE THREAD

**Issue by LoHub** [libre-tube/LibreTube#6677]
### Steps to reproduce

1. Watch a live-stream
2. Move the time slider to left at the beginning

### Expected behavior

No crash

### Actual behavior

The following error is raised:

```
java.lang.IllegalStateException: Slider value(-2.691) must be greater or equal to valueFrom(0.0), and lower or equal to valueTo(3600.0)
	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(SourceFile:225)
	at com.google.android.material.slider.BaseSlider.onDraw(SourceFile:9)
	at android.view.View.draw(View.java:24842)
	at android.view.View.updateDisplayListIfDirty(View.java:23692)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5659)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5312)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4303)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2917)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10324)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

### LibreTube version

0.25.2

### Android version

Android 15

### Other details

Could be related to #4994

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That slider is provided by the ExoPlayer library, possibly it's a bug in their timebar implementation (we just use theirs without any modification).
