### ISSUE TITLE
error after screen lock when video is paused

### ISSUE THREAD

**Issue by krolaper** [libre-tube/LibreTube#6915]
### Steps to reproduce

```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 627400 bytes
Bundle stats:
  android:viewHierarchyState [size=3748]
    android:views [size=3428]
  androidx.lifecycle.BundlableSavedStateRegistry.key [size=622900]
    android:support:activity-result [size=15912]
      KEY_COMPONENT_ACTIVITY_REGISTERED_KEYS [size=14788]
    android:support:fragments [size=606612]
      fragment_becbd9f3-6e23-4942-9e1a-852f14713a41 [size=594600]
        childFragmentManager [size=585228]
          fragment_d4d1eb06-17ee-47a0-bfbf-e150d5c4b36b [size=126960]
            viewState [size=3300]
            childFragmentManager [size=122712]
              fragment_19579dbf-a703-4a8f-9635-c74b39b4327b [size=40748]
                arguments [size=39568]
                  videoList [size=33776]
                  nextPage [size=5008]
              fragment_ef5134ea-aad8-4458-8bad-589e5355a623 [size=40784]
                arguments [size=39604]
                  videoList [size=33776]
                  nextPage [size=5008]
              fragment_86190ed9-d009-4ace-8128-8d4bd5cbf616 [size=40248]
                arguments [size=39068]
                  videoList [size=33776]
                  nextPage [size=5008]
          fragment_946a707d-c69f-4a0e-859c-bc5d5dd322df [size=125076]
            viewState [size=3300]
            childFragmentManager [size=120828]
              fragment_05712643-d2ce-4667-89bb-e07836078512 [size=40120]
                arguments [size=38940]
                  videoList [size=33160]
                  nextPage [size=4996]
              fragment_cdb56f15-0f15-41a1-98d1-9d03fee8675b [size=40156]
                arguments [size=38976]
                  videoList [size=33160]
                  nextPage [size=4996]
              fragment_bd055103-8c38-4fea-a8bc-c5e6ab2aba12 [size=39620]
                arguments [size=38440]
                  videoList [size=33160]
                  nextPage [size=4996]
          fragment_7dc2a905-8e2e-432f-bbfc-707782074e5c [size=4032]
            viewState [size=2860]
          fragment_4579a92c-91b5-45e8-89ff-57f28ad87e9c [size=3532]
            viewState [size=2792]
          fragment_ba746da9-8cb4-4b4b-9466-9545bcbfe0cb [size=1260]
          fragment_a18ce76e-6952-47c2-9e25-ffcfe00f39ed [size=4032]
            viewState [size=2860]
          fragment_a3a238d8-39f1-417b-ae6f-5bed1507e03f [size=1384]
          fragment_6d3feb2c-8ca0-4f5e-ae1e-989d86c3dbdf [size=4024]
            viewState [size=2860]
          fragment_7af0f4ad-6fb9-422b-8db4-c964ab8a25da [size=1184]
          state [size=10988]
          fragment_5dfde74e-56e7-4c55-9ab8-8ddf40a31519 [size=1252]
          fragment_d1a756f1-ec9e-4a3c-941c-84d1512d079f [size=1184]
          fragment_704c1bf6-a277-478f-8b20-e65a1f53b26e [size=122184]
            viewState [size=3300]
            childFragmentManager [size=117936]
              fragment_db186061-6936-4434-b66e-1ce20b3ece7a [size=39192]
                arguments [size=38012]
                  videoList [size=32188]
                  nextPage [size=5004]
              fragment_be8f3b6a-761b-41b0-b7d1-e5e644b4018e [size=39156]
                arguments [size=37976]
                  videoList [size=32188]
                  nextPage [size=5004]
              fragment_1b9bc625-675d-4b15-922a-e02903f3ddaf [size=38656]
                arguments [size=37476]
                  videoList [size=32188]
                  nextPage [size=5004]
          fragment_ddf09dbf-79d4-4da2-9797-72853cb72d54 [size=4024]
            viewState [size=2860]
          fragment_1cfca15d-f8a5-47f2-b981-7ede88a9e401 [size=1252]
          fragment_c4678c9e-fe56-4786-a65f-bcbacc76d918 [size=167236]
            viewState [size=43576]
              0x7f0a0275 [size=40760]
            childFragmentManager [size=122712]
              fragment_34952501-9a32-456c-b47f-643730cc0bc6 [size=40784]
                arguments [size=39604]
                  videoList [size=33776]
                  nextPage [size=5008]
              fragment_b6d86acb-3ee5-4da4-998b-659dfc4f9a60 [size=40748]
                arguments [size=39568]
                  videoList [size=33776]
                  nextPage [size=5008]
              fragment_32b50483-8d68-49ba-8078-58a268c09203 [size=40248]
                arguments [size=39068]
                  videoList [size=33776]
                  nextPage [size=5008]
          fragment_38bfcff0-ac64-4433-b273-ab074ab0de34 [size=4056]
            viewState [size=2860]
        registryState [size=8832]
          androidx.lifecycle.BundlableSavedStateRegistry.key [size=8708]
            android-support-nav:fragment:navControllerState [size=8384]
              android-support-nav:controller:backStack [size=8280]
      fragment_68c8e6ee-5caf-4d5a-9471-a1664df9d589 [size=11336]
        viewState [size=10404]
PersistableBundle stats:
  [null]
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:146)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8787)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
Caused by: android.os.TransactionTooLargeException: data parcel size 627400 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:586)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1498)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:100)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:135)
	... 8 more
    ```

### Expected behavior

No crash

### Actual behavior

Crash app

### LibreTube version

0.26.0

### Android version

15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
@krolaper edit your complaint and follow proper template

**Comment by krolaper** [comment]
> Samsung?

Pixel 6a, A15

**Comment by Figim** [comment]
> > Samsung?
> 
> Pixel 6a

Please check again in the latest version. Follow the issue template

**Comment by ghost** [comment]
Same on the 32.0 on android 17 with a Pixel 8. It happend in the background even with unrestricted battery given and notifcations enabled. So that is not the issue.

<details>

```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 529516 bytes
Bundle stats:
  android:viewHierarchyState [size=3944]
    android:views [size=3676]
  androidx.lifecycle.BundlableSavedStateRegistry.key [size=524812]
    androidx.lifecycle.internal.SavedStateHandlesProvider [size=2080]
      androidx.lifecycle.ViewModelProvider.DefaultKey:com.github.libretube.ui.models.AddToPlaylistViewModel [size=1852]
        videoInfo [size=1580]
    android:support:activity-result [size=34608]
      KEY_COMPONENT_ACTIVITY_REGISTERED_KEYS [size=32584]
      KEY_COMPONENT_ACTIVITY_REGISTERED_RCS [size=1660]
    android:support:fragments [size=487752]
      fragment_6bdabbf6-8371-4a85-b3aa-4a3cc5b69e3f [size=17456]
        viewState [size=10792]
        childFragmentManager [size=5656]
          fragment_17aa9dbb-6a70-415b-a1a1-cf361194342a [size=5232]
            childFragmentManager [size=1912]
              fragment_6b3d3c26-1c69-4d87-8155-99d13f8501c9 [size=1488]
            savedInstanceState [size=1292]
              android:savedDialogState [size=1216]
                android:dialogHierarchy [size=1088]
                  android:views [size=1036]
      fragment_682a101f-3edb-4b17-8a48-db20a9897771 [size=469540]
        childFragmentManager [size=422920]
          fragment_87783061-796d-4ebf-b298-4e0eb9a6c0cb [size=4180]
            viewState [size=3696]
          fragment_2ff4bb2f-3c06-4ab8-8531-3b71d1d36d6d [size=4820]
            viewState [size=3696]
          fragment_25e5df31-5dc5-40b4-b10f-6fc715d47a2f [size=4244]
            viewState [size=3056]
          fragment_50b9f72a-81ef-4e99-9556-a8af7203ead9 [size=1268]
          fragment_275172a7-3ee6-400d-b5d9-9e9c400398d3 [size=4860]
            viewState [size=3696]
          fragment_ea0467fe-969d-439e-826b-5f5a7457f6c7 [size=4844]
            viewState [size=3696]
          fragment_0f547590-4537-41bc-9755-74bd53464762 [size=1276]
          fragment_d8af098b-b859-4f4c-a2a8-0947ba84acc3 [size=4820]
            viewState [size=3696]
          fragment_b50a5f80-199b-4c72-b251-a8c865b9a581 [size=3952]
            viewState [size=3200]
          fragment_d18503be-f2b0-4b2e-af3e-cd4ae7667224 [size=1268]
          fragment_d76ac04b-931f-425f-9471-aa7db1832e4b [size=1196]
          fragment_1a62e423-2c6d-4b46-8a71-0adfa5037814 [size=1268]
          fragment_a47edd9c-0be4-4ddb-9e0e-ce504bd665a8 [size=4244]
            viewState [size=3056]
          fragment_0d4e4bc3-1705-454b-b527-3e5feab25677 [size=1268]
          fragment_3f763a24-4092-4ba7-bef4-9c0880a37220 [size=1268]
          fragment_3273ebde-7240-4f4b-9d74-0eeb51a4d07e [size=5680]
            viewState [size=2900]
            childFragmentManager [size=1816]
              fragment_e2aeaeb0-70d4-4bfc-ba67-a8e88ac47f96 [size=1392]
          fragment_f5e6084a-4ce1-4fe3-b918-415884a6f4ac [size=1268]
          fragment_c43aa0fb-a2a9-4d31-913a-b75d84d7c46a [size=1280]
          fragment_d25e6994-6483-4bbc-abfe-279be4fcd237 [size=4844]
            viewState [size=3696]
          fragment_0e29474c-8910-4025-b8c6-23895e43cf39 [size=1196]
          fragment_92992270-2493-443c-98eb-70496dd2fe35 [size=1268]
          fragment_a6aa4404-716b-40a6-8bfe-9ab1c5f7b358 [size=4204]
            viewState [size=3696]
          fragment_a0350713-59c8-49d7-a63e-16877aaa6fd3 [size=5680]
            viewState [size=3092]
            childFragmentManager [size=1816]
              fragment_4d70754c-1241-4ca5-9c08-65111dca6d37 [size=1392]
          fragment_25a1a90a-c273-49c5-b6e3-7703e4180e67 [size=1268]
          fragment_0f8c8d11-7784-4fac-a3b8-5adc06f5c5f0 [size=5680]
            viewState [size=2900]
            childFragmentManager [size=1816]
              fragment_5318d1d3-2285-4c95-8938-76e8e805f470 [size=1392]
          fragment_592bdf7b-a2ab-42f1-ae98-3f0ba03ee73c [size=4196]
            viewState [size=3696]
          fragment_fc8e731b-101f-4607-9937-c81c5c530ebe [size=4196]
            viewState [size=3696]
          fragment_dcd64769-a242-4249-9335-38fdf65d55a1 [size=4244]
            viewState [size=3056]
          fragment_15e4822d-05fc-4cc1-9840-2bd8e73100dd [size=1268]
          fragment_bf9f7c5b-b72a-46a2-a7b5-70b0b1d8a100 [size=1268]
          fragment_c20fc40a-e33a-4ac4-9e62-f82ac4d085d7 [size=4196]
            viewState [size=3696]
          fragment_63b57bd7-9cd2-4efb-9633-875c237556ca [size=1196]
          fragment_6209950a-32f0-4cd0-ab3c-baff77bb3bef [size=4196]
            viewState [size=3696]
          fragment_266c7afa-be31-47e9-a616-729832b4aa1e [size=1268]
          fragment_d74af3a7-d7ff-4756-8515-1b6d7c75cc14 [size=1268]
          fragment_88240603-de6e-40a3-82fb-5f926d8ba78e [size=4172]
            viewState [size=3056]
          fragment_46a26468-2cea-4974-b3ec-4561875dd8ea [size=4196]
            viewState [size=3056]
          fragment_8afceb9d-0d2c-4348-bd9b-a4401c4bbaf5 [size=1268]
          fragment_bc81370d-355e-4a4d-9284-07d2eff4b66b [size=4220]
            viewState [size=3696]
          fragment_5053aeb2-e035-42be-9c0f-a66f5d4d1a6b [size=1268]
          fragment_a673c863-a90b-417c-b091-531cd625cfae [size=1304]
          fragment_0102ee48-5a17-46eb-b4bc-782c43dd81f5 [size=4844]
            viewState [size=3696]
          fragment_d185715a-ca28-480d-855e-597ddc3a7ccc [size=4276]
            viewState [size=3056]
          fragment_9c8853a4-3d21-42e1-a19f-fc8a6b73589a [size=4228]
            viewState [size=3056]
          fragment_0bb5e1d5-fe23-4015-8f8b-6c116b325c51 [size=1268]
          fragment_bae7ce94-c45a-4cc8-8de5-656180a014ff [size=1268]
          fragment_29c33be3-4b96-4f66-8971-b6b01f3c43d2 [size=4244]
            viewState [size=3696]
          fragment_366cd499-93f5-457d-8531-92aba264267b [size=1288]
          fragment_8c50174f-096d-4c6e-b4b1-30db7083ab53 [size=4868]
            viewState [size=3696]
          fragment_c05ed749-d0c9-4959-8e96-7bfb5bc9b3d6 [size=1268]
          fragment_4b0acca1-3f32-4c26-aa63-159a666bf798 [size=4812]
            viewState [size=3696]
          fragment_a9fb91a5-b304-4a8c-bcdc-90e79ccc2880 [size=4268]
            viewState [size=3696]
          fragment_f1d777d6-0f71-40ec-9002-dcc4ded4398c [size=1196]
          fragment_3a1b2e27-9013-43ba-a50d-1a17f7836d31 [size=5680]
            viewState [size=3092]
            childFragmentManager [size=1816]
              fragment_50351597-a899-4065-aff9-72ea823a14ad [size=1392]
          fragment_5fba605a-8e2b-42c2-8a37-b9d4938d9a7e [size=1268]
          fragment_c9a20520-b595-4cd4-9723-275a141db16c [size=4196]
            viewState [size=3056]
          state [size=68300]
          fragment_0946e4ee-9f0a-4aa6-a393-85b8002b4361 [size=4820]
            viewState [size=3696]
          fragment_851d8eba-656d-4d85-b656-aa71d5cae259 [size=4172]
            viewState [size=3056]
          fragment_e3623f97-d129-4d26-8bb5-667ae01659d5 [size=4204]
            viewState [size=3056]
          fragment_178ea25b-a5b3-4e1c-affe-fc485534c995 [size=1268]
          fragment_0f43cb83-dda7-4b2a-b0f5-3ddc8d9c9c69 [size=1268]
          fragment_fbbb9e8a-9f91-4da4-a4c7-9e842a485b1e [size=4812]
            viewState [size=3696]
          fragment_bc7a5b41-f486-4259-b9de-bb97e54db80f [size=4172]
            viewState [size=3696]
          fragment_25bad90e-67a0-406d-b5bc-a94fff0cce64 [size=5680]
            viewState [size=2900]
            childFragmentManager [size=1816]
              fragment_e551b5ae-9f1c-454e-b12a-1e6bc263fdf2 [size=1392]
          fragment_0c9ce0e0-b188-4581-b979-760487897140 [size=4868]
            viewState [size=3696]
          fragment_4f3be34c-6a49-4b6f-8f2e-bb8bb3db9ef2 [size=1268]
          fragment_6efc3239-ba8a-4ae1-981d-9890f1eabf29 [size=1268]
          fragment_45b2b223-424e-4fc4-90d3-39f39636f0c3 [size=4204]
            viewState [size=3056]
          fragment_888d1cf0-6ee1-47af-ab59-9b99b7440d35 [size=1268]
          fragment_945540c6-9b0e-472d-ab41-6aaa10d12625 [size=4276]
            viewState [size=3056]
          fragment_e0b11dfa-dc22-4c8c-9b76-7556986904f1 [size=1268]
          fragment_aec11d0f-48d4-4733-a3b5-0d4802d9d7cc [size=1268]
          fragment_5f3cc5fc-0514-411a-b156-85fe381e776e [size=4204]
            viewState [size=3056]
          fragment_d3768b28-b17e-4f80-9411-5c2eba4e14af [size=4228]
            viewState [size=3056]
          fragment_e3fe80ca-eefd-4ab3-9f36-ebaf180554f4 [size=5680]
            viewState [size=2900]
            childFragmentManager [size=1816]
              fragment_52c6212c-ea10-4c0d-b708-5859cd285ebf [size=1392]
          fragment_7c1757e3-6e02-4fc5-8bf2-2ed741926ee0 [size=5680]
            viewState [size=2900]
            childFragmentManager [size=1816]
              fragment_8c2b794f-1903-4145-8b7b-beddd260644e [size=1392]
          fragment_813d5bdf-50cf-4f42-bda4-2e63e977de66 [size=4820]
            viewState [size=3696]
          fragment_e2b3730d-293e-4bde-a325-0301eadca695 [size=1268]
          fragment_a9e9bd84-2701-44af-9524-3e4844b5d85e [size=4196]
            viewState [size=3056]
          fragment_be6f0138-a469-4baa-b231-3a776d7cd8f1 [size=4860]
            viewState [size=3696]
          fragment_cf623dd5-f3b8-49d1-9638-f1e9e6ff7da3 [size=1268]
          fragment_b978128c-8c5a-496f-8ef7-39f7a185cd65 [size=4252]
            viewState [size=3056]
          fragment_fa6ff434-62ab-49b4-b3a4-f656f710e4dd [size=4180]
            viewState [size=3056]
          fragment_3fd9f5d3-bc2d-49d5-9fd0-0ad53bd7eea6 [size=4196]
            viewState [size=3056]
          fragment_2ed12e71-170f-4ec4-8686-281f9e549986 [size=4252]
            viewState [size=3056]
          fragment_725b03e4-9013-45ba-9ecc-61f8ff2bc1a4 [size=5680]
            viewState [size=2900]
            childFragmentManager [size=1816]
              fragment_e318731e-4e01-4556-a03d-54e75fda7acf [size=1392]
          fragment_5d86a591-9480-4544-a4c9-2566bb6d8be5 [size=1268]
          fragment_36286572-ab25-4f51-8348-fb139fe593dd [size=1268]
          fragment_6ff2bb22-cff5-48bb-bfb9-dcb7bd0f4e2a [size=4180]
            viewState [size=3056]
          fragment_e2768c95-6123-4b9c-8d9e-c71a9dc06787 [size=1268]
          fragment_5743c5b0-e927-4bf7-ae71-8da7ae310096 [size=1268]
          fragment_972449af-16e1-4a34-9bab-a108fd7e855e [size=4204]
            viewState [size=3056]
          fragment_f783bd7d-572e-45bf-9432-dea2097dc8a8 [size=5680]
            viewState [size=2900]
            childFragmentManager [size=1816]
              fragment_7cbd6d0f-0ec4-4d0d-9c9b-0f227490b980 [size=1392]
          fragment_89fa7472-e4c0-4f0c-8ac6-e2cf1a51427c [size=5872]
            viewState [size=3092]
            childFragmentManager [size=1816]
              fragment_36d47144-188b-40b9-a7d2-0310d718ab32 [size=1392]
          fragment_065bc374-5293-4c28-924c-b8630eea339b [size=1268]
          fragment_f7b6555f-2b68-49ca-b1fd-45627bf4adce [size=5680]
            viewState [size=2900]
            childFragmentManager [size=1816]
              fragment_2c26ed9c-708f-45b0-b467-f8161464910a [size=1392]
          fragment_e5018696-0772-47fa-90f2-95f0547f47dc [size=4188]
            viewState [size=3056]
          fragment_bc05b4d4-51e2-4624-9b59-9b20e9abec5e [size=1268]
          fragment_6f6af553-3b6d-4c45-8518-f7303c283e22 [size=1268]
          fragment_7062ce5f-7fa1-4713-b9cc-98563544d4d0 [size=4244]
            viewState [size=3056]
          fragment_78f60212-de6f-4806-a6a2-21d647175cbb [size=1268]
          fragment_d5399722-ebb1-4ef0-943c-7b0b477ebff6 [size=1268]
          fragment_d90f4577-efea-48cb-ad7c-28c9dee0d697 [size=1268]
          fragment_f181d609-091d-47c8-99e0-28877fdd8e37 [size=4228]
            viewState [size=3696]
          fragment_3251d4d3-6384-4fab-aaba-acf05c8db776 [size=4836]
            viewState [size=3696]
          fragment_4dea841f-cc1e-495f-ba9b-7b4f51eab971 [size=4836]
            viewState [size=3696]
          fragment_dbb4d6df-3e9e-4f03-af2e-3817d485f17f [size=1268]
          fragment_8f8196ab-68bd-49e7-8243-c09e45e6bd2d [size=1304]
          fragment_51d0e49c-1d1d-46e7-aac1-880b6da4145d [size=1268]
        registryState [size=45916]
          androidx.lifecycle.BundlableSavedStateRegistry.key [size=45788]
            android-support-nav:fragment:navControllerState [size=45460]
              android-support-nav:controller:backStackStates:01526860-bca1-462a-b464-731f048ddd41 [size=2020]
              android-support-nav:controller:navigatorState [size=4932]
                fragment [size=4740]
                  androidx-nav-fragment:navigator:savedIds [size=4632]
              android-support-nav:controller:backStack [size=37604]
PersistableBundle stats:
  [null]
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:156)
	at android.os.Handler.handleCallback(Handler.java:1095)
	at android.os.Handler.dispatchMessageImpl(Handler.java:135)
	at android.os.Handler.dispatchMessage(Handler.java:125)
	at android.os.Looper.loopOnce(Looper.java:296)
	at android.os.Looper.loop(Looper.java:397)
	at android.app.ActivityThread.main(ActivityThread.java:9569)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: android.os.TransactionTooLargeException: data parcel size 529516 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:656)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1562)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:103)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:141)
	... 9 more
```

</details>
