### ISSUE TITLE
App crash after changing app icon 

### ISSUE THREAD

**Issue by soumyabratabose** [libre-tube/LibreTube#693]
### Steps to reproduce

1. First change the app icon to something other than default.
2. Then go to the same manu where you will see that the default app icon is still selected.
3. Now if you try to select the default app icon option, the app crashes. 

### Expected behavior

The app icon should change to the selected one. 

### Actual behavior

The app crashes. 

### LibreTube version

0.3.3

### Android version

10

### Other details

java.lang.IllegalArgumentException: Component class com.github.libretube.MainActivity does not exist in com.github.libretube
	at android.os.Parcel.createException(Parcel.java:2078)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.os.Parcel.readException(Parcel.java:1990)
	at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:7400)
	at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:2594)
	at y2.h.c(SourceFile:4)
	at androidx.preference.Preference.a(Unknown Source:4)
	at h1.c.o0(SourceFile:2)
	at androidx.preference.a.onDismiss(Unknown Source:11)
	at androidx.fragment.app.m$c.onDismiss(SourceFile:2)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1409)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:22046)
	at com.android.server.pm.PackageManagerService.setComponentEnabledSetting(PackageManagerService.java:21901)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3508)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4113)
	at android.os.Binder.execTransactInternal(Binder.java:1021)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thank you for providing a debug log, makes it a lot easier for me :)
It should be fixed now, I would appreciate if you could test it with the latest debug builds :p

**Comment by soumyabratabose** [comment]
The issue is fixed in the latest debug build. Thanks for the fix @Bnyro.
