### ISSUE TITLE
Subscriptions without account

### ISSUE THREAD

**Issue by niklas-fischer** [libre-tube/LibreTube#954]
### Describe your suggested feature

Regarding privacy it would be great to have the option to subscribe to channels without having any account whatsoever. 

### Other details

NewPipe has the same feature (and in my opinion it's a killer feature 😉)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Joaquin0apps** [comment]
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at d4.u0.f(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView$t.j(SourceFile:91)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(SourceFile:3)
	at androidx.recyclerview.widget.GridLayoutManager.e1(Unknown Source:95)
	at androidx.recyclerview.widget.LinearLayoutManager.R0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.i0(SourceFile:19)
	at androidx.recyclerview.widget.GridLayoutManager.i0(SourceFile:7)
	at androidx.recyclerview.widget.RecyclerView.s(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(Unknown Source:63)
	at android.view.View.measure(View.java:24824)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24824)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1414)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.widget.ScrollView.onMeasure(ScrollView.java:452)
	at android.view.View.measure(View.java:24824)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(Unknown Source:53)
	at android.view.View.measure(View.java:24824)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24824)
	at androidx.constraintlayout.widget.ConstraintLayout$b.b(SourceFile:23)
	at u.f.i0(SourceFile:11)
	at v.j.g(SourceFile:2)
	at v.j.f(SourceFile:6)
	at v.j.g(SourceFile:16)
	at v.j.g(SourceFile:30)
	at u.f.Y(SourceFile:34)
	at v.b.b(SourceFile:5)
	at androidx.constraintlayout.widget.ConstraintLayout.q(SourceFile:55)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:12)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(SourceFile:2)
	at android.view.View.measure(View.java:24824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
	at android.view.View.measure(View.java:24824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:773)
	at android.view.View.measure(View.java:24824)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3256)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2011)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2316)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1899)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8061)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:969)
	at android.view.Choreographer.doCallbacks(Choreographer.java:793)
	at android.view.Choreographer.doFrame(Choreographer.java:728)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7561)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
