### ISSUE TITLE
App crash at startup after updating to v0.4.2

### ISSUE THREAD

**Issue by soumyabratabose** [libre-tube/LibreTube#967]
### Steps to reproduce

1. Update from v0. 4.1 to 0.4.2 

### Expected behavior

The app should start fine. 

### Actual behavior

The app crashed during startup 

### LibreTube version

0.4.2

### Android version

10

### Other details

The logs are given below.

java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
	at java.util.ArrayList.get(ArrayList.java:437)
	at d4.u0.f(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView$t.j(SourceFile:91)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(SourceFile:3)
	at androidx.recyclerview.widget.GridLayoutManager.e1(Unknown Source:95)
	at androidx.recyclerview.widget.LinearLayoutManager.R0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.i0(SourceFile:19)
	at androidx.recyclerview.widget.GridLayoutManager.i0(SourceFile:7)
	at androidx.recyclerview.widget.RecyclerView.s(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(Unknown Source:63)
	at android.view.View.measure(View.java:24862)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24862)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24862)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24862)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1414)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.widget.ScrollView.onMeasure(ScrollView.java:452)
	at android.view.View.measure(View.java:24862)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(Unknown Source:53)
	at android.view.View.measure(View.java:24862)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24862)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24862)
	at androidx.constraintlayout.widget.ConstraintLayout$b.b(SourceFile:23)
	at u.f.i0(SourceFile:11)
	at v.j.g(SourceFile:2)
	at v.j.f(SourceFile:6)
	at v.j.g(SourceFile:16)
	at v.j.g(SourceFile:30)
	at u.f.Y(SourceFile:34)
	at v.b.b(SourceFile:5)
	at androidx.constraintlayout.widget.ConstraintLayout.q(SourceFile:55)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:12)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(SourceFile:2)
	at android.view.View.measure(View.java:24862)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
	at android.view.View.measure(View.java:24862)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24862)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24862)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24862)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:775)
	at android.view.View.measure(View.java:24862)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3119)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1931)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2225)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1819)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7783)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
	at android.view.Choreographer.doCallbacks(Choreographer.java:865)
	at android.view.Choreographer.doFrame(Choreographer.java:800)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by soumyabratabose** [comment]
😢

**Comment by soumyabratabose** [comment]
Also, after installing uninstalling and reinstalling, the app works but the version checker shows network error.

![Screenshot_2022-08-04-17-49-35-901_com github libretube](https://user-images.githubusercontent.com/89439748/182845524-647e9dfa-1d62-42d2-8cb3-94e795748f97.jpg)
