### ISSUE TITLE
Can't able to play any video 

### ISSUE THREAD

**Issue by Tanishk-hash** [libre-tube/LibreTube#987]
### Steps to reproduce

When I open any video it plays for 1-3 sec and then app crashes and closes 

### Expected behavior

I think video player have some issue 

### Actual behavior

.

### LibreTube version

0.4.2

### Android version

Android 11

### Other details

UI is quite good and recommendations of only 100 video is quite useful for students who don't want to be distracted by recommendation and suggested videos 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Tanishk-hash** [comment]
It shows this code 


java.lang.IndexOutOfBoundsException: Index: 9, Size: 9
	at java.util.ArrayList.get(ArrayList.java:437)
	at d4.u0.f(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView$t.j(SourceFile:91)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(SourceFile:3)
	at androidx.recyclerview.widget.GridLayoutManager.e1(Unknown Source:95)
	at androidx.recyclerview.widget.LinearLayoutManager.R0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.i0(SourceFile:19)
	at androidx.recyclerview.widget.GridLayoutManager.i0(SourceFile:7)
	at androidx.recyclerview.widget.RecyclerView.s(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(Unknown Source:63)
	at android.view.View.measure(View.java:25785)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25785)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25785)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25785)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1445)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.widget.ScrollView.onMeasure(ScrollView.java:475)
	at android.view.View.measure(View.java:25785)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(Unknown Source:53)
	at android.view.View.measure(View.java:25785)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25785)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25785)
	at androidx.constraintlayout.widget.ConstraintLayout$b.b(SourceFile:23)
	at u.f.i0(SourceFile:11)
	at v.j.g(SourceFile:2)
	at v.j.f(SourceFile:6)
	at v.j.g(SourceFile:16)
	at v.j.g(SourceFile:30)
	at u.f.Y(SourceFile:34)
	at v.b.b(SourceFile:5)
	at androidx.constraintlayout.widget.ConstraintLayout.q(SourceFile:55)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:12)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(SourceFile:2)
	at android.view.View.measure(View.java:25785)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
	at android.view.View.measure(View.java:25785)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25785)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25785)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25785)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7043)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:832)
	at android.view.View.measure(View.java:25785)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3788)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2546)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2808)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2266)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8838)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1470)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1267)
	at android.view.Choreographer.doFrame(Choreographer.java:978)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1455)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:260)
	at android.app.ActivityThread.main(ActivityThread.java:8269)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by Bnyro** [comment]
Can't reproduce. Any specific video you watched?
